### ISSUE TITLE
在使用go mod 情况下 go get dubbo-go 1.0.0  有源码使用了旧包地址不能正常依赖

### ISSUE THREAD

**Issue by veily** [apache/dubbo-go#103]
**What happened**:
go get dubbo-go 1.0.0  有源码使用了旧包地址不能正常依赖
```
go get -u github.com/apache/dubbo-go
go: github.com/apache/dubbo-go@v1.0.0: parsing go.mod: unexpected module path "github.com/dubbo/go-for-apache-dubbo"
go get: error loading module requirements
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by gaoxinge** [comment]
@veily THX. 现在应该全改过来了，你再试试，看看还有没有问题。

**Comment by AlexStocks** [comment]
pls do not use this version.
