### ISSUE TITLE
debug程序的时候,在断点处卡一会,然后放行直接触发 panic

### ISSUE THREAD

**Issue by Clever-Wang** [apache/dubbo-go#1033]
**What happened**:
debug程序的时候 需要打断点查看参数,可能卡在断点处10几秒左右时间,然后放行,程序崩溃。
每次debug都需要重新启动,有点麻烦。

**What you expected to happen**:
启动之后,可以debug多次.

**How to reproduce it (as minimally and precisely as possible)**:
dubbo go: 1.5.5 
断点位置： 自定义 Filter 下面的方法内部
func (af aopFilter) OnResponse(ctx context.Context, result protocol.Result, _ protocol.Invoker, invocation protocol.Invocation) protocol.Result {}

**Anything else we need to know?**:
异常堆栈如下：
2021/02/01 15:29:10 Connection attempt unsuccessful after 1.000242771s (greater than max timeout of 1s). Resetting connection and trying again with a new connection.
2021/02/01 15:29:10 Connection attempt unsuccessful after 1.000159587s (greater than max timeout of 1s). Resetting connection and trying again with a new connection.
2021/02/01 15:29:10 Connected to 172.17.10.157:2181
2021/02/01 15:29:10 Connected to 172.17.10.157:2181
2021/02/01 15:29:10 authentication failed: zk: session has been expired by the server
2021/02/01 15:29:10 Session expired event received
panic: close of closed channel

goroutine 872 [running]:
github.com/samuel/go-zookeeper/zk.(*Conn).Close(0xc0000eec60)
        /Users/wangsaichao/goProjects/pkg/mod/github.com/samuel/go-zookeeper@v0.0.0-20201211165307-7117e9ea2414/zk/conn.go:313 +0x4e
github.com/curator-go/curator.(*handleHolder).internalClose(0xc00013d8f0, 0x0, 0x0)
        /Users/wangsaichao/goProjects/pkg/mod/github.com/curator-go/curator@v0.0.0-20180923140012-8a961ea3b252/state.go:136 +0x11a
github.com/curator-go/curator.(*handleHolder).closeAndReset(0xc00013d8f0, 0x0, 0x0)
        /Users/wangsaichao/goProjects/pkg/mod/github.com/curator-go/curator@v0.0.0-20180923140012-8a961ea3b252/state.go:122 +0x37
github.com/curator-go/curator.(*connectionState).reset(0xc0000c2ae0, 0x0, 0x0)
        /Users/wangsaichao/goProjects/pkg/mod/github.com/curator-go/curator@v0.0.0-20180923140012-8a961ea3b252/state.go:234 +0x85
github.com/curator-go/curator.(*connectionState).handleExpiredSession(0xc0000c2ae0)
        /Users/wangsaichao/goProjects/pkg/mod/github.com/curator-go/curator@v0.0.0-20180923140012-8a961ea3b252/state.go:356 +0xcc
github.com/curator-go/curator.(*connectionState).checkState(0xc0000c2ae0, 0xffffff90, 0x0, 0x0, 0x4d1ef00, 0xc0000c0000)
        /Users/wangsaichao/goProjects/pkg/mod/github.com/curator-go/curator@v0.0.0-20180923140012-8a961ea3b252/state.go:323 +0x6e
github.com/curator-go/curator.(*connectionState).process(0xc0000c2ae0, 0xc00073d440)
        /Users/wangsaichao/goProjects/pkg/mod/github.com/curator-go/curator@v0.0.0-20180923140012-8a961ea3b252/state.go:304 +0x1e6
created by github.com/curator-go/curator.(*Watchers).Fire
        /Users/wangsaichao/goProjects/pkg/mod/github.com/curator-go/curator@v0.0.0-20180923140012-8a961ea3b252/watcher.go:64 +0xc8
Exiting.

Debugger finished with exit code 0

**Comment by wenxuwan** [comment]
why v1.5.5 use package github.com/samuel/go-zookeeper, dubbo-go should use dubbogo/go-zookeeper
