### ISSUE TITLE
Remoting metadata service is not use remoting

### ISSUE THREAD

**Issue by zouyx** [apache/dubbo-go#1038]
**What happened**:

In remoting metadata service is using inmemory now, rather than use remoting metadata center .

![image](https://user-images.githubusercontent.com/3828072/106623852-ffc95980-65af-11eb-926b-1c4732630e3c.png)

Is it right logic?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by zouyx** [comment]
@Patrick0308 Bro, what's your suggestion?

**Comment by williamfeng323** [comment]
should it be fine since the only difference between in-memory and remote service is the publish* methods?

**Comment by zouyx** [comment]
> should it be fine since the only difference between in-memory and remote service is the publish* methods?

@williamfeng323 no, i mean it uses in-memory in remote service implement rather than remote service
