### ISSUE TITLE
Replace CI icon with Github Action

### ISSUE THREAD

**Issue by zouyx** [apache/dubbo-go#1042]
**What would you like to be added**:

Replace in english and chinese doc pls.

**Why is this needed**:

Travis CI will no longer use , replace that CI icon with Github Action.

![image](https://user-images.githubusercontent.com/3828072/106734119-9ef05e80-664d-11eb-8f41-6b0c9d1066c9.png)

**Comment by xiaoliu10** [comment]
WIP
