### ISSUE TITLE
当java端的Date是null，go端decode将会报错，如果使用*time.Time可ui接收null，但是将无法接收正常Date

### ISSUE THREAD

**Issue by flixgithub** [apache/dubbo-go#105]
**What happened**:
当java端的Date是null，go端decode将会报错，如果使用*time.Time可ui接收null，但是将无法接收正常Date
**What you expected to happen**:
抛出的异常：
ERROR  getty@v1.0.7/session.go:558  [session.handlePackage] error:decObject illegal object type tag:74 github.com/dubbogo/hessian2.(*Decoder).decObject
**How to reproduce it (as minimally and precisely as possible)**:
go 作为 client 端，java作为server端，使用dubbogo框架进行调用
![struct_example](https://user-images.githubusercontent.com/6768036/60254317-549aed80-9900-11e9-9190-2f4fea193f05.png)

**Anything else we need to know?**:

**Comment by wongoo** [comment]
@flixgithub  thanks, we will check that asap!

**Comment by wongoo** [comment]
it can be closed. @AlexStocks
