### ISSUE TITLE
dubbo-go 使用naocs配置中心，报err:Get config content in dynamic configuration error , error message is config not found

### ISSUE THREAD

**Issue by 13450891497** [apache/dubbo-go#1079]
dubbo-go 使用naocs配置中心报错

Get config content in dynamic configuration error , error message is config not found

[provider config center refresh] start config center error , error message is {start config center error!: config not found}

server.yml配置
# config center config
config_center:
  protocol: "nacos"
  address: "127.0.0.1:8848"

<img width="1551" alt="dubbo-issu" src="https://user-images.githubusercontent.com/20694697/110437320-3551ed00-80f0-11eb-8b1e-be0de3953acc.png">

**Comment by lzp0412** [comment]
@13450891497 从日志看是没有配置，你这边可以在nacos控制台看下你的配置是否存在
