### ISSUE TITLE
Feature: dubbogo 中如何使用 bigdecimal [ok for usage]

### ISSUE THREAD

**Issue by dajiiu** [apache/dubbo-go#109]
> 项目对接时将bigdecimal改为string成功接收（证明不是连接问题）

1. 改回bigdecimal后使用golang中的float64测试报错

2. 然后再此时下方包中的Decimal，已经不能接收BigDecimal类型
import "github.com/shopspring/decimal"

3. 尝试使用golang中的big类型同样失败

BigDecimal在Java中是常用的精确计算包装类，实际业务不可能改为浮点类型，所以该问题依旧是需要解决的问题

**Comment by pepigo** [comment]
测试中迎来好消息，饶了一大圈后发现使用string类型居然可以接收的BigDecimal

**Java BigDecimal 对应 Golang string 测通**

**Comment by wongoo** [comment]
@pepigo  we will check and test it asap.

**Comment by pepigo** [comment]
感谢，希望尽快有解决方案

**Comment by pepigo** [comment]
经测试，最新版的dubbogo可以成功接收BigDecimal类型

![image](https://user-images.githubusercontent.com/52339367/61452826-42582080-a98f-11e9-9aed-25345ae20242.png)


![3](https://user-images.githubusercontent.com/52339367/61452583-ae865480-a98e-11e9-88c2-90ef56b67cbd.png)

![bigdecimal](https://user-images.githubusercontent.com/52339367/61452569-a4645600-a98e-11e9-9086-1b3fb9177fd4.png)

![bigdecimal2](https://user-images.githubusercontent.com/52339367/61452562-9dd5de80-a98e-11e9-97c2-84c6b7f94bc2.png)
