### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by echoiron** [apache/dubbo-go#110]
### 1. 环境变量问题

- 如果没有配置环境变量，可以将os.Getenv去掉，CONF_CONSUMER_FILE_PATH直接给配置文件地址
 - confConFile = os.Getenv(constant.CONF_CONSUMER_FILE_PATH)
 - confProFile = os.Getenv(constant.CONF_PROVIDER_FILE_PATH)
改为
 - confConFile = constant.CONF_CONSUMER_FILE_PATH
 - confProFile = constant.CONF_PROVIDER_FILE_PATH

### 2. 在IDE(vscode or Goland)项目运行时报未声明
- 选中client.go user.go version.go同时运行
`待更新中...`

**Comment by flycash** [comment]
invalid pseudo-version: does not match version-control timestamp:
![image](https://user-images.githubusercontent.com/9923838/70761408-19925680-1d88-11ea-8161-773035ddd154.png)

`
go: github.com/apache/dubbo-go@v0.1.2-0.20190923162929-95f857c89fd2: invalid pseudo-version: does not match version-control timestamp (2019-09-23T08:29:29Z)
`
After upgrading your go version to 1.3, someone may got this error.

go 1.3 add [some validations](https://tip.golang.org/doc/go1.13#version-validation)
**The solution is changing your timezone to UTC**

**Comment by zouyx** [comment]
> invalid pseudo-version: does not match version-control timestamp:
> ![image](https://user-images.githubusercontent.com/9923838/70761408-19925680-1d88-11ea-8161-773035ddd154.png)
> 
> `go: github.com/apache/dubbo-go@v0.1.2-0.20190923162929-95f857c89fd2: invalid pseudo-version: does not match version-control timestamp (2019-09-23T08:29:29Z)`
> After upgrading your go version to 1.3, someone may got this error.
> 
> go 1.3 add [some validations](https://tip.golang.org/doc/go1.13#version-validation)
> **The solution is changing your timezone to UTC**
> 
> https://go-review.googlesource.com/c/go/+/211137#message-cffdbbe51cc94dd25180fd81b426ccba58db7123
> 
> Chinese:
> 这个问题其实就是升级到go 1.13之后会出现的。go 1.13对依赖多了比较多的校验，其中一个就是校验commit id和时间戳是否匹配。
> 
> 然而时间戳它使用的是UTC。在中国，大部分人设置的时区都不是UTC，所以会出现问题。只需要将自己的时区调整到UTC就可以了。

其实只需要开发者使用UTC时间戳，不需要设置本机时区，有两个方法从两个维度调整commitid和时间戳

* 使用以下链接，将commitid修改成短commitid，就会提示正确的commitid，跟着修改就行了

```
https://proxy.golang.org/github.com/apache/dubbo-go/@v/v0.1.2-0.20191219122420-56cb00a83ba8.mod
```

* 修改commitid成正确之后，再次访问就会提示正确的时间戳。

**Comment by flycash** [comment]
Nacos Registry:  using Java internal class name as the interface value will cause registry failed.

The service configuration looks like:
```yml
services:
  "UserProvider":
    protocol : "dubbo"
    # 相当于dubbo.xml中的interface
    interface : "com.ikurento.user.UserProvider$UserService"
    loadbalance: "random"
    warmup: "100"
    cluster: "failover"
    methods:
    - name: "GetUser"
      retries: 1
      loadbalance: "random"
```
The key point is that the value `com.ikurento.user.UserProvider$UserService` contains symbol '$" which is not allowed in nacos server. The response from nacos server is 'dom name can only have these characters: 0-9a-zA-Z-._:, current: DEFAULT_GROUP@@providers:com.ikurento.user.UserProvider$UserService
'

You should rename the interface to avoid the problem. 

![image](https://user-images.githubusercontent.com/9923838/74028199-bec25780-49e4-11ea-86b6-07dc0198847d.png)

![image](https://user-images.githubusercontent.com/9923838/74028254-ddc0e980-49e4-11ea-80b3-41e7e8e96d20.png)

**Comment by echoiron** [comment]
![eht_logo](https://user-images.githubusercontent.com/52339367/84628582-80512200-af1b-11ea-945a-c6b4b9ad31f2.png)
