### ISSUE TITLE
java服务端重启后，dubbo-go客户端必须重启才能建立连接

### ISSUE THREAD

**Issue by fumenglin** [apache/dubbo-go#1126]
java服务端重启后，dubbo-go客户端必须重启才能建立连接，
java的版本：2.7.6

dubbo-go1.5.6-r1 ;dubbo-go1.5.6-r2两个版本都试过；都出现这种情况：

浮现场景：
开一个java服务，dubbo-go的客户端，
断开java服务，然后就看到dubbo-go的客户端不管是重新连接，还是做什么，都连不上

**Comment by AlexStocks** [comment]
pls use v1.5.6-rc2 to fix this issue. we make sure that this problem do not exist when using v1.5.6-rc2.
