### ISSUE TITLE
Imp: using Endpoints instead of Pod in k8s registry 

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go#1136]
**What would you like to be added**:

把 k8s resolver 里面的 Pod 信息换成 Endpoints 信息。

**Why is this needed**:

当 Pod 信息多的时候，会对consumer造成流量冲击。

当有 pod 信息变化的时候，consumer 端会收到 k8s 发来的 pod 的全量信息，但是 consumer 实际上只需要 provider 地址信息即可。而 endpoints 中就有 provider 的地址信息，这个数据已经足够。

如果只 watch endpoints 地址信息，其数据量往往只有 pods 信息的 1/n。

**Comment by chickenlj** [comment]
我目前在做应用级服务发现对接k8s的流程，我看那边消费端也是同时监听了service pod endpoints，我尝试看一下能否只监听其中部分。
