### ISSUE TITLE
dubbo-go注册service不支持自定义registry-group？

### ISSUE THREAD

**Issue by trust-freedom** [apache/dubbo-go#1139]
**What would you like to be added**:
看 servicediscovery/base_registry.go  providerRegistry() 中对registry-group是写死的，如下
```
dubboPath = fmt.Sprintf("/dubbo/%s/%s", r.service(c), common.DubboNodes[common.PROVIDER])
```
请问是不支持自定义registry-group吗？？

**Why is this needed**:
支持自定义registry-group，感觉这是比较常用的特性

**Comment by zhaoyunxing92** [comment]
一般修改这个需求很少吧，这个可以认为是一个默认的配置

**Comment by trust-freedom** [comment]
这个registry group我们主要用于环境隔离，否则都在/dubbo下，同公司包名类似，可能会出现ServiceName相同的情况，感觉应该也有不少是这么使用的吧？请问这块之后会支持吗？配置和dubbo java版本靠拢

**Comment by AlexStocks** [comment]
u can try to submit a pr to implement this feature. thx.

**Comment by zhaoyunxing92** [comment]
可以看下这个 https://github.com/apache/dubbo-go-samples/tree/master/group 支持分组的
