### ISSUE TITLE
配置文件的优化

### ISSUE THREAD

**Issue by zhaoyunxing92** [apache/dubbo-go#1140]
-  一个服务如果是provider和client有重复配置问题例如：application config就重复了
-  希望配置有一个层次例如注册是否检查单独的一个`check` `cache_file` 都是单独在外面的
-  有些配置里面有、代码里面也有一份  例如：`service config`配置了在`pkg`里面的`user.go`又写一遍

**Comment by beiwei30** [comment]
针对 3 的进一步说明，比如：

```golang
func init() {
	cat := new(CatService)
	config.SetConsumerService(cat)
	lion := new(LionService)
	config.SetConsumerService(lion)

	config.SetProviderService(&AmericanService{
		cat:  cat,
		lion: lion,
	})
}
```

既然在配置里已经配置了，那么就不应该在代码中还需要装配。

同时，针对 consumer 和 provider 需要单独在各自的配置文件中配置，对于大部分服务化应用来说，很不友好，因为大部分应用既是 provider 也是 consumer

**Comment by MedusaLeee** [comment]
补充一个建议：目前都是将provider的配置文件写在同一个yaml中，如果项目provider较多，一个yaml会较大且不好维护，有个建议是 services 节点中的 各个provider配置可以拆分小的文件，有不同的命名，这样provider配置文件可以和项目provider代码写在同一个木块下，比较好管理

**Comment by AlexStocks** [comment]
same issue https://github.com/apache/dubbo-go/issues/416

**Comment by LaurenceLiZhixin** [comment]
We upgraded configuration module and config api, please refer to https://dubbogo.github.io/zh-cn/docs/user/concept/configuration.html  , and dubbo-go-samples for details.
