### ISSUE TITLE
dubbogo 4.0

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go#1142]
**What would you like to be added**:

通过借鉴【谓之抄袭也可，但是内部技术细节差别处处可见】 dubbo，dubbogo 功能足够强大，优点是足以满足大中型公司的需求，对于中小公司来说，优点却变成了缺点。

缺点即是：一切都按照 Dubbo 的概念进行了包装，对入门者难度极高。

需要把 dubbogo 进行裁剪，使其内核足够完备且精简，其他功能作为插件供用户选择。

**Why is this needed**:

1 一个简单且完备的 dubbogo 内核；
2 各种 dubbogo plugins；
3 更丰富的配置读取机制与编程接口，且确定唯一的编程入口，不能有过多的参数，导致用户理解困难；
4 把 dubbogo 现有的 gRPC 和 triple-go 等生产工具进一步强化，

**Comment by AlexStocks** [comment]
@LaurenceLiZhixin

**Comment by AlexStocks** [comment]
把 init()全部删掉 cc @georgehao

**Comment by AlexStocks** [comment]
@zouyx

**Comment by hxmhlt** [comment]
dubbogo plugins
Sounds cool !

**Comment by zouyx** [comment]
> dubbogo plugins
> Sounds cool !

It sounds will kill me，boss he
