### ISSUE TITLE
reduce connection number when connection registry

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go#1143]
**What would you like to be added**:

现在的 dubbogo 与 nacos/etcd/consul/k8s 等注册中心使用的连接过多，导致 dubbogo 内存使用居高不下。

可以借鉴zk的改进，继续优化。

**Comment by AlexStocks** [comment]
cc @zhaoyunxing92

**Comment by AlexStocks** [comment]
etcd/consul @gaoxinge

**Comment by gaoxinge** [comment]
I will check and fix consul first.

**Comment by gaoxinge** [comment]
Related pull reuqest: https://github.com/apache/dubbo-go/pull/1010.

**Comment by gaoxinge** [comment]
@AlexStocks Is goroutine number or tcp number? In https://github.com/apache/dubbo-go/pull/1010, it reduce the number of tcp connection.

**Comment by AlexStocks** [comment]
> @AlexStocks Is goroutine number or tcp number? In #1010, it reduce the number of tcp connection number.

u r right. reduce the connection number.
