### ISSUE TITLE
建议增加lumberjack组件，增加日志分割功能

### ISSUE THREAD

**Issue by whitekeyboard** [apache/dubbo-go#1210]
当前使用zap日志库，不支持日志分割，以及压缩功能，长时间运行服务，会导致日志无限增大。
查询、分析日志较为困难，建议增加lumberjack组件，增加日志分割功能，以及压缩等功能。
谢谢

**Comment by AlexStocks** [comment]
a pr is welcome. thx.

**Comment by zouyx** [comment]
zap 是默认的日志组件，你可以通过实现logger 接口自定义日志组件。

https://github.com/apache/dubbo-go/blob/cc74aa54b25ece8060e55f279eddd9aa383ae39c/common/logger/logger.go#L146

**Comment by LaurenceLiZhixin** [comment]
This is added in #1335
