### ISSUE TITLE
CI test of 3.0 with two "Integrate Test" procedure

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [apache/dubbo-go#1264]
**What would you like to be added**:

**Why is this needed**:

**Comment by LaurenceLiZhixin** [comment]
![图片](https://user-images.githubusercontent.com/45508533/122445119-cda31c00-cfd3-11eb-81f6-64bb67c2d7e8.png)

**Comment by EnableAsync** [comment]
The first one will be triggered by `pull_request` event and the second one by `push` event, should the names be changed to distinguish them?

**Comment by LaurenceLiZhixin** [comment]
If you can make it shows only one procedure under specific condition, it's better. Else you can rename them to distinguish them.
