### ISSUE TITLE
Just one character is enough for the name of the receiver.

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go#1276]
**What would you like to be added**:

I know give a name of a var is a very difficult problem  in computer science. However, just one character for a receiver name should be enough. 

the shorter receiver name of AttachmentMatchJudger in router/v3router/judger/attachment_match_judger.go should not be 'amj'. The same problem exists in the following items too.

     router/v3router/judger/bool_match_judger.go BoolMathJudger
     router/v3router/judger/double_match_judger.go DoubleMatchJudger
     router/v3router/judger/double_range_match_judger.go DoubleRangeMatchJudger
     router/v3router/judger/list_double_match_judger.go ListDoubleMatchJudger
     router/v3router/judger/list_string_match_judger.go ListStringMatchJudger
     router/v3router/judger/method_match_judger.go MethodMatchJudger
     router/v3router/judger/string_match_judger.go StringMatchJudger
     router/v3router/dubbo_rule.go DubboRouterRule

**Comment by AlexStocks** [comment]
cc @LaurenceLiZhixin

**Comment by LaurenceLiZhixin** [comment]
@Mulavar Do you think it's necessary to change name?

**Comment by Mulavar** [comment]
It‘s a good question about how to assign the name of a variable better.In my opnion, I think there's no difference between `a` and `amj` when we use them for a receiver name, because both they lost the meaning of the receiver. A unified standard is enough.

**Comment by AlexStocks** [comment]
Just one char is enough for a receiver name as Go programming rule.
