### ISSUE TITLE
tencentcloud-sdk-go v3.0.83 not found ,move v3.x to v1.x

### ISSUE THREAD

**Issue by IceFoxs** [apache/dubbo-go#1281]
dobbo go v3.0.0-rc2

go mod tidy

project build  failed ,because github.com/tencentcloud/tencentcloud-sdk-go  v3.0.83 not found

I add  the following content  to go.mod , project build  is success!
Hope fixed it!
```
replace github.com/tencentcloud/tencentcloud-sdk-go => github.com/tencentcloud/tencentcloud-sdk-go v1.0.195
```

![image](https://user-images.githubusercontent.com/26451038/123516624-9f0dfb00-d6cf-11eb-832b-9fd2d2ced325.png)

**What happened**:

![image](https://user-images.githubusercontent.com/26451038/123516545-3fafeb00-d6cf-11eb-873d-5e0d37307978.png)
![image](https://user-images.githubusercontent.com/26451038/123516578-63733100-d6cf-11eb-932a-0ceae4ca0c0c.png)

**What you expected to happen**:
project build success!
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by AlexStocks** [comment]
你这个 issue 是不是提交错了，我们是 dubbo-go，不是 tencentcloud-sdk-go。

**Comment by IceFoxs** [comment]
> 你这个 issue 是不是提交错了，我们是 dubbo-go，不是 tencentcloud-sdk-go。

没有提错啊，项目依赖找不到啊，虽然不是dubbo-go直接依赖的，因为tencentcloud-sdk-go v3.0.83现在是拉不到了，所以希望能添加 replace修正一下tencentcloud-sdk-go 版本啊，要不执行go mod tidy总是报找不到

**Comment by georgehao** [comment]
麻烦把你replace 之前的 go.mod 贴一下

**Comment by IceFoxs** [comment]
> 麻烦把你replace 之前的 go.mod 贴一下
我就是在dubbo-go项目 go.mod中添加了replace,其他的没改动
![image](https://user-images.githubusercontent.com/26451038/123953172-82c4d380-d9d9-11eb-817b-32e245ca1d89.png)
![image](https://user-images.githubusercontent.com/26451038/123953322-ad169100-d9d9-11eb-8fcc-5380f90a6ddd.png)

**Comment by IceFoxs** [comment]
> 麻烦把你replace 之前的 go.mod 贴一下
我就是在dubbo-go项目 go.mod中添加了replace,其他的没改动
![image](https://user-images.githubusercontent.com/26451038/123954561-219dff80-d9db-11eb-9bf3-c0a0ded15cb0.png)

![image](https://user-images.githubusercontent.com/26451038/123954549-1cd94b80-d9db-11eb-80e2-2f81f0add578.png)

**Comment by EnableAsync** [comment]
> 没有提错啊，项目依赖找不到啊，虽然不是dubbo-go直接依赖的，因为tencentcloud-sdk-go v3.0.83现在是拉不到了，所以希望能添加 replace修正一下tencentcloud-sdk-go 版本啊，要不执行go mod tidy总是报找不到

请尝试在您自己工程的 go.mod 文件中添加 replace 来解决该问题

**Comment by georgehao** [comment]
@IceFoxs 你不能在dubbogo的源码里加自己的业务逻辑呀。请参考下面例子：https://github.com/apache/dubbo-go-samples
