### ISSUE TITLE
goroutine leak in taskPoolSimple.worker

### ISSUE THREAD

**Issue by LvBay** [apache/dubbo-go#1295]
**What happened**:
Dubbogo upgraded from 1.4.5 to 1.5.6, there was a goroutine leak

**What you expected to happen**:
dont leak
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Through the comparison of pprof at different times, I found the leaked stack information

```
1109 @ 0x442c65 0x40c68f 0x40c30b 0x6d73d6 0x478a01
#       0x6d73d5        github.com/dubbogo/gost/sync.(*taskPoolSimple).worker+0x95      /home/docker/go/pkg/mod/github.com/dubbogo/gost@v1.11.2/sync/task_pool.go:304
```

**Comment by AlexStocks** [comment]
the same as another issue. pls check this problem in v1.5.7-rc1
