### ISSUE TITLE
v3 support consul ?

### ISSUE THREAD

**Issue by telanflow** [apache/dubbo-go#1305]
**What would you like to be added**:

please, why not support consul in dubbo-go v3.0.0 ?

**Why is this needed**:

we need this feature

**Comment by AlexStocks** [comment]
pls register ur user info in https://github.com/apache/dubbo-go/issues/2.

What's more, we plan to delete consul in dubbogo 3.0 https://github.com/apache/dubbo-go/pull/1280. If u need it realy, pls left ur comment in this pr.

**Comment by telanflow** [comment]
what is the reason for removing `consul` support ?

**Comment by bilinxing** [comment]
3.0 为啥要删除consul的支持？ 相对nacos，consul要轻量级得多

**Comment by bilinxing** [comment]
我们的java团队用得都是consul，结果golang团队想要选用的框架居然不支持consul

**Comment by AlexStocks** [comment]
@bilinxing @telanflow r u willing to help us to support consul in dubbogo? If so, we are happy to accept ur pr.

**Comment by AlexStocks** [comment]
we will discuss this feature support in recent days. what's more, if u think the consul register feature is indeed helpful for u, pls register ur user info in github.com/issues/2 .

**Comment by LaurenceLiZhixin** [comment]
@bilinxing 
After discussion, we got the conclusion that continuing consul support in dubbo-go v3.0. The module would be added back soon.
