### ISSUE TITLE
perhaps exists dead lock

### ISSUE THREAD

**Issue by Da-Hong** [apache/dubbo-go#1310]
When provider has many instances such as 50，consumer start fail !

**What happened**:

Error msg: No provider available for the service to the consumer use dubbo version 1.5.6

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Register use zookeeper, 50 or more provider instances ,then start consumer , use grpc protocol, watch start success or not.

**Anything else we need to know?**:

As I debug:
In zkRegistry struct's InitListeners method and getListener method.

dataListener := r.dataListener
dataListener.mutex.Lock()
defer dataListener.mutex.Unlock()

or

oldDataListener := r.dataListener
oldDataListener.mutex.Lock()
defer oldDataListener.mutex.Unlock()

may conflict ！

**Comment by Da-Hong** [comment]
func NewRegistryConfigurationListener(client *gxzookeeper.ZookeeperClient, reg *zkRegistry, conf *common.URL) *RegistryConfigurationListener {
	reg.WaitGroup().Add(1)
	return &RegistryConfigurationListener{
		client:       client,
		registry:     reg,
		events:       make(chan *config_center.ConfigChangeEvent, 32),
		isClosed:     false,
		close:        make(chan struct{}, 1),
		subscribeURL: conf}
}

Cause by events chan 32 
First InitListeners will fill events more than 32 so getListener locked.

**Comment by LaurenceLiZhixin** [comment]
Thanks for your issue. We have solved it in pr: 
#1314 
and
#1330
