### ISSUE TITLE
problems with registry cache of key

### ISSUE THREAD

**Issue by XiaoWeiKIN** [apache/dubbo-go#1311]
![image](https://user-images.githubusercontent.com/20626345/125034382-1aee4700-e0c3-11eb-8612-f437b3651fef.png)

注册中心缓存的key，应该是ip为维度的，整个实例共享一个注册中心的。

like dubbo key is

zookeeper://xxxx:2181/org.apache.dubbo.registry.RegistryService

**Comment by LaurenceLiZhixin** [comment]
This would be fixed in 3.0, as the config of this part would be refactoried.
