### ISSUE TITLE
希望有详细的文档

### ISSUE THREAD

**Issue by tylitianrui** [apache/dubbo-go#1318]
**What would you like to be added**:
希望有dubbo go的详细文档。如果没有dubbo java的开发经验，直接使用成本有些高，希望能用文档。

**Comment by AlexStocks** [comment]
agree with u. we are working hard on our doc recently. At present u can get some refs from http://alexstocks.github.io/html/dubbogo.html.

**Comment by LaurenceLiZhixin** [comment]
You can refer [dubbo-go 官网](https://dubbogo.github.io)
