### ISSUE TITLE
为什么使用`func () cluster.LoadBalance` 作为入参?

### ISSUE THREAD

**Issue by JiaLiangoooo** [apache/dubbo-go#1321]
正在使用的版本是1.5.5rc1
目前正在尝试自定义loadbalance，但是balance里面会有一些自定义的参数.
```
type Compare func(invocation protocol.Invocation, invoker protocol.Invoker) bool
func NewBalance(compare Compare) cluster.LoadBalance {
	return &Balance{f: compare}
}
```
但是extension.SetLoadbalance支持的是`func () cluster.LoadBalance`
```
// SetLoadbalance sets the loadbalance extension with @name
// For example: random/round_robin/consistent_hash/least_active/...
func SetLoadbalance(name string, fcn func() cluster.LoadBalance) {
	loadbalances[name] = fcn
}

// GetLoadbalance finds the loadbalance extension with @name
func GetLoadbalance(name string) cluster.LoadBalance {
	if loadbalances[name] == nil {
		panic("loadbalance for " + name + " is not existing, make sure you have import the package.")
	}

	return loadbalances[name]()
}

```
所以有个疑问 为什么不使用`SetLoadbalance(name string, cluster.LoadBalance) `, 而使用`func () cluster.LoadBalance` ?

**Comment by LaurenceLiZhixin** [comment]
1. 为什么现在这么做：使用工厂函数的原因就是防止一个实例被多次使用，如果用户定义的实例内有map字段，会造成线程安全问题，多个地方都会改动同一个实例也会造成逻辑错乱。
2. 现有工厂函数并没有提供入参，这的确不好。我认为这一点需要针对3.0重新定义。给一个用户可扩展参数metaadata，类型可以是interface。
@JiaLiangoooo 您觉得如何。

**Comment by Mulavar** [comment]
> 1. 为什么现在这么做：使用工厂函数的原因就是防止一个实例被多次使用，如果用户定义的实例内有map字段，会造成线程安全问题，多个地方都会改动同一个实例也会造成逻辑错乱。
> 2. 现有工厂函数并没有提供入参，这的确不好。我认为这一点需要针对3.0重新定义。给一个用户可扩展参数metaadata，类型可以是interface。
>    @JiaLiangoooo 您觉得如何。

再补充一下，关于第一点我们的讨论是如果额外提供注册单例实例的方式目前会有增一些复杂度，所以我们更加倾向于在第二点上为用户提高易用性，欢迎您任何宝贵的意见。

**Comment by JiaLiangoooo** [comment]
关于第一点因为如果用户使用的话是使用了存在类似于map之类的，在多线程内会不安全，我认为这个应该是写这个plugin应该考虑的事情，可以通过事例或者文档来说明，是否会更灵活呢？ dubo-go是不是只需要面对的是一个filter，不管是struct、function.

关于第二点如果只是添加一个参数metadata的话，多个参数怎么办？ 这个事例里面只有一个比较方法，如果我需要再额外增加一个cache呢，cache能支持多种存储方式？ 这种也能满足吗？

**Comment by LaurenceLiZhixin** [comment]
> 关于第一点因为如果用户使用的话是使用了存在类似于map之类的，在多线程内会不安全，我认为这个应该是写这个plugin应该考虑的事情，可以通过事例或者文档来说明，是否会更灵活呢？ dubo-go是不是只需要面对的是一个filter，不管是struct、function.
> 
> 关于第二点如果只是添加一个参数metadata的话，多个参数怎么办？ 这个事例里面只有一个比较方法，如果我需要再额外增加一个cache呢，cache能支持多种存储方式？ 这种也能满足吗？

第一点我还是保留现在工厂函数的意见。
第二点，interface你可以自己定义结构传进来，然后在你的实现中断言成你想要的结构，多少个参数都可以。cache当然也可以，你自己定义好。

**Comment by Mulavar** [comment]
或者针对第二点我们可以提供一个 Interface... 这样多参数的方法
