### ISSUE TITLE
set the common getty params

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go#1340]
**What would you like to be added**:

1 升级 getty 版本到 1.4.4
2 当前 getty 一些 session 参数如下
![image](https://user-images.githubusercontent.com/7959374/126867818-c55a7b55-6dee-4678-a827-60f0aa84f369.png)

2.1 需要删除上面红线出过时的参数，也许还有其他一些过时参数，请参阅最新 getty ；
2.2 需要把 getty 配置参数公共化，不要让用户不断反复配置；

**Comment by AlexStocks** [comment]
cc @djh

**Comment by Mulavar** [comment]
关于2.2，和云兴大哥讨论了下，如果用户既用了triple又用了dubbo，那两者底层的网络配置应该是各有一套，云兴大哥在调研配置优化的时候看了dubbo的实现也是这样的，所以我们觉得2.2是不是还是先保留现状。

**Comment by AlexStocks** [comment]
> 关于2.2，和云兴大哥讨论了下，如果用户既用了triple又用了dubbo，那两者底层的网络配置应该是各有一套，云兴大哥在调研配置优化的时候看了dubbo的实现也是这样的，所以我们觉得2.2是不是还是先保留现状。

ok

**Comment by LaurenceLiZhixin** [comment]
Can this pr be closed?
