### ISSUE TITLE
Unit Test can't be run locally caused by zk.

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [apache/dubbo-go#1349]
**What happened**:
When running go test ./... locally, zk unit test would panic because there isn't zk jar and zk environment locally. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by LaurenceLiZhixin** [comment]
Replacement of branch 1.5's go mod `github.com/shirou/gopsutil => github.com/shirou/gopsutil v0.0.0-20181107111621-48177ef5f880` should be delete soon. And other replacement should be checked if necessary.

**Comment by tydhot** [comment]
assign to me

**Comment by LaurenceLiZhixin** [comment]
complete！
