### ISSUE TITLE
triple协议对于单向流生成pb.go异常的问题

### ISSUE THREAD

**Issue by lethexixin** [apache/dubbo-go#1360]
**proto文件: stream.proto**
```proto
syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.grpc.examples.proto";
option java_outer_classname = "Stream";
option objc_class_prefix = "HL";

package proto;
option go_package = ".;tri_demos";

service Stream {
  rpc TwoSidesStream (stream Request) returns (stream Reply) {}
  rpc ClientStream(stream Request) returns (Reply) {}
  rpc ServerStream(Request) returns (stream Reply) {}
}

message Request {
  string name = 1;
}

message Reply {
  string message = 1;
}
```

> 平台: Win10
> protoc-gen-dubbo3.exe 工具由 `https://github.com/apache/dubbo-go/tree/3.0/protocol/dubbo3/protoc-gen-dubbo3` (2021年8月2日)编译而成
> 编译命令: protoc -I ./ stream.proto  --dubbo3_out=plugins=grpc+dubbo:.  

上面的proto文件,生成triple协议的pb.go文件的时候, 对于 `rpc ServerStream(Request) returns (stream Reply) {} `方法, 生成error, 如下:  

![image](https://user-images.githubusercontent.com/46220496/127845478-ff80db7c-2bcb-40d2-823b-1c0b99c315d3.png)

![image](https://user-images.githubusercontent.com/46220496/127845372-37800099-dc0e-4c0b-970b-dfb846eb0ce4.png)

**Comment by LaurenceLiZhixin** [comment]
单向流数据尚不支持。预计后续会支持上。 @lethexixin

**Comment by LaurenceLiZhixin** [comment]
@lethexixin 请问贵公司在考虑使用triple的流模式RPC调用么？

**Comment by LaurenceLiZhixin** [comment]
@xavier-niu

**Comment by LaurenceLiZhixin** [comment]
After community discussion, we have no plan to support this feature in the short term. You can discuss with us on the DingTalk group: 23331795. @lethexixin
