### ISSUE TITLE
提供一个接口，在服务发现准备好之前，等待准备好

### ISSUE THREAD

**Issue by gaohuag** [apache/dubbo-go#1364]
**What would you like to be added**:
提供一个接口，在服务发现准备好之前，等待准备好
**Why is this needed**:
目前的策略是sleep 3s,见代码：
"""
func init() {
	config.Load()
	referenceConfig.GenericLoad(appName) //appName is the unique identification of RPCService
	time.Sleep(3 * time.Second)
}
"""

**Comment by LaurenceLiZhixin** [comment]
I updated the default reference config's check field to true, and consumerConfig would wait for invoker ready until timeout.
Refer to #1531
