### ISSUE TITLE
[QUESTION]首页文档页面好多都打不开?

### ISSUE THREAD

**Issue by xmsz** [apache/dubbo-go#1371]
**What would you like to be added**:

**Why is this needed**:

3.0下的
配置模块  配置中心模块全部都不打不开

**Comment by LaurenceLiZhixin** [comment]
配置模块？配置中心模块？贴个链接看下？

**Comment by LaurenceLiZhixin** [comment]
@xmsz

**Comment by xmsz** [comment]
> 配置模块？配置中心模块？贴个链接看下？

https://dubbogo.github.io/dubbo-go-website/zh-cn/docs/user/configuration/provider.html
https://dubbogo.github.io/dubbo-go-website/zh-cn/docs/user/registry/nacos.html
...


https://github.com/dubbogo/dubbo-go-website/blob/master/docs/zh-cn/user/registry/nacos.md
我看源站里也是空的

![image](https://user-images.githubusercontent.com/5879146/128819690-f45cd493-909f-46f7-9c88-c7cd22c1f953.png)

**Comment by LaurenceLiZhixin** [comment]
@xmsz 
Please move on to https://dubbogo.github.io
the document of 1.5 is collecting, and there is some docs for 3.0. The official website is restarted lately and we are working on progress.

@cjphaha 
Pls close the old website for https://dubbogo.github.io/dubbo-go-website
And try to handing over documentation for 1.5 to new community members

**Comment by xmsz** [comment]
> @xmsz
> Please move on to https://dubbogo.github.io
> the document of 1.5 is collecting, and there is some docs for 3.0. The official website is restarted lately and we are working on progress.

ok noticed
