### ISSUE TITLE
自定义log

### ISSUE THREAD

**Issue by tonyjt** [apache/dubbo-go#1415]
**What happened**:
需要自定义的log，然后通过logger.SetLogger设置，但是init方法中会先从本地文件初始化log，就出现了warning：
 InitLog with error ioutil.ReadFile(file:../profiles/dev/log.yml) = error:open ../profiles/dev/log.yml: no such file or directory

init 方法中这段代码似乎也没意义
// forbidden to executing twice.
	if logger != nil {
		return
	}

**What you expected to happen**:
logger.log 改成logger.Log
getty.log 改成logger.Log

**How to reproduce it (as minimally and precisely as possible)**:

调用logger.SetLogger

**Anything else we need to know?**:

**Comment by fangyincheng** [comment]
这个图的默认file path是没必要的吧
![image](https://user-images.githubusercontent.com/18375310/131216687-c1072369-f8e4-47bd-a0e6-2520d452ebb8.png)

这个图的error可以考虑不做返回？
![image](https://user-images.githubusercontent.com/18375310/131216699-d1a23fc2-0244-4235-ab40-e62d4fa6fa74.png)

**Comment by Mulavar** [comment]
你这边目前在用 dubbo-go 哪个版本，目前3.0这边在做配置优化，优化过程会把这边的错误信息直接去掉，如果是1.5，我们这边针对性修一下吧。

**Comment by tonyjt** [comment]
3.0的，非常感谢！
