### ISSUE TITLE
Why define method name "JavaClassName" as hessian pojo type interface method?

### ISSUE THREAD

**Issue by hxmhlt** [apache/dubbo-go#143]
**What happened**:
I use go client to call go server.  Why I have to implement the pojo method named "JavaClassName"?

**What you expected to happen**:
Rename name .Or I do not need to register pojo when go client calling go server.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by AlexStocks** [comment]
can not agree with u. Our project's main target is go-client --> java server.

**Comment by hxmhlt** [comment]
Main target is not same as only target. We should take care of gopher's feelings. @AlexStocks
