### ISSUE TITLE
使用apisix2.9 grpc 调用 tri 协议 失败提示错误 599 network connect timeout error

### ISSUE THREAD

**Issue by imandarava** [apache/dubbo-go#1447]
参考dubbo-go 3.0 快速开始 做的测试代码 (https://dubbogo.github.io/zh-cn/docs/user/quickstart/3.0/quickstart.html)
环境 go1.16 +nacos +apisix2.9 

1.协议 tri 直接用client.go调用成功  apisix 调用失败 
2. 协议tri 移除 server.go setConfigByAPI (改用service.yml) 用apisix 调用失败
3. 修改协议为grpc 使用 setConfigByAPI (配置文件) 用apisix 调用 失败
4. 修改协议为grpc 移除 server.go  setConfigByAPI (改用service.yml) 用apisix 调用 成功

tri 没有测试通过  grpc 感觉配置setConfigByAPI 中 用到的 config.NewProviderConfig 有问题 ,我发现缺少 ProtocolConf 但我用 map 格式构建后 用apisix依然调用不起

**Comment by ChangedenCZD** [comment]
由配置未对齐造成的异常
