### ISSUE TITLE
init中包含了命令行的相关逻辑导致告警产生

### ISSUE THREAD

**Issue by zhangdaohuai** [apache/dubbo-go#1451]
检查下来 1.5 版本 3.0的版本
发现在：
1、logger.go
2、config_loader.go
init函数中包含了 命令行分析的相关逻辑；这样会导致使用命令行进行配置时，flag库会产生一系列的报警。

**Comment by xavier-niu** [comment]
Hi, daohuai, thanks for your feedback. Could you provide details about the warning information? It is acceptable for a screenshot or log text. And it could be better to tell us how to reproduce it. Thanks.

**Comment by LaurenceLiZhixin** [comment]
@zhangdaohuai Can you join dingtalk group 23331795 to discuss with us ?

**Comment by LaurenceLiZhixin** [comment]
这一问题已经在3.0 修复。
