### ISSUE TITLE
建议重构 dubbo grpc protobuf 代码生成工具与社区保持一致

### ISSUE THREAD

**Issue by win5do** [apache/dubbo-go#1460]
**What would you like to be added**:
https://github.com/apache/dubbo-go/blob/f192c1eaf847fdd38f3cda3d73dea6b02d0654b5/protocol/grpc/protoc-gen-dubbo/plugin/dubbo/dubbo.go#L28
```
// Deprecated: Use the "google.golang.org/protobuf/compiler/protogen" package
// instead to write protoc plugins in Go.
```

dubbo-go 源码引用的 github.com/golang/protobuf 已经被标记为弃用。plugin 生成 grpc 的方式已经不被支持，相关 [issue](https://github.com/golang/protobuf/issues/1070)。

建议参考 [grpc-go](https://github.com/grpc/grpc-go/blob/938f6e2f7550e542bd78f3b9e8812665db109e02/cmd/protoc-gen-go-grpc/main.go) 的方式，重构 protoc-gen-go-dubbo。

使用 [grpc 官方文档](https://grpc.io/docs/languages/go/quickstart/#regenerate-grpc-code)的风格生成代码，protoc-gen-xxx 命令各司其职：
```sh
protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    --go-dubbo_out=. --go-dubbo_opt=paths=source_relative \
    helloworld.proto
```

**Why is this needed**:
跟 protobuf 社区保持一致，让 dubbo-go 中使用 protobuf 更顺滑。

**Comment by LaurenceLiZhixin** [comment]
@win5do 请加入钉钉群 23331795 和我们一起讨论这个问题。

**Comment by LaurenceLiZhixin** [comment]
经过跟领导协商，原生 grpc 将不作为主要支持的协议。建议直接使用与grpc 完全兼容的 triple 协议。 @win5do
