### ISSUE TITLE
method name '$invoke' is used to retrieve method level configs like 'retries' or 'loadbalance' in generic service call.

### ISSUE THREAD

**Issue by awayings** [apache/dubbo-go#1511]
**What happened**:
failover_cluster_invoker/failback_cluster_invoker/zone_aware_cluster_invoker  use method name '$invoke' to retrieve method level configs like 'retries'  or 'loadbalance' in generic service call.
**What you expected to happen**:
use the real method name to retrieve configs for generic service call.
**How to reproduce it (as minimally and precisely as possible)**:
custom 'retries' or 'locabalance' in server side config. launch a request by genericservice client.
**Anything else we need to know?**:

**Comment by luky116** [comment]
fixed by:https://github.com/apache/dubbo-go/pull/1674/files
