### ISSUE TITLE
怎么自定义服务提供者的请求IP

### ISSUE THREAD

**Issue by anden007** [apache/dubbo-go#1518]
目前情况：微服务发布到百度云服务器，由于百度的公网IP是影射到服务器的，所以我们不能用外网IP直接用来设置triple的ip（如果直接用，会无法启动）
`  protocols:
    triple:
      name: tri
      ip: 192.168.32.5 #只能用真实本地ip，否则无法启动
      port: 20000`
如果无法在外网访问服务，本地开发就很纠结了！
请大佬们帮忙指教一二！

**Comment by LaurenceLiZhixin** [comment]
@anden007 Any question? I guess this pr is able to be closed.  if you have any questions, pls contact us in dingtalk group. Thanks.
