### ISSUE TITLE
the request package size can not be greater than 8MiB

### ISSUE THREAD

**Issue by ChangedenCZD** [apache/dubbo-go#1526]
**What happened**:
dubbo-go/protocol/dubbo/impl/codec.go    第231行
Data length %d too large, max payload %d
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
1.5.7-rc2

**Comment by AlexStocks** [comment]
![image](https://user-images.githubusercontent.com/7959374/137751036-2e503e10-9f37-4723-9cb3-a3ade639f7bd.png)
