### ISSUE TITLE
dubbo proxy rpc err log

### ISSUE THREAD

**Issue by XiaoWeiKIN** [apache/dubbo-go#1539]
https://github.com/apache/dubbo-go/blob/a45fd29e8a6d6c61090d237950aa35070bef8b4f/common/proxy/proxy.go#L207

1. 这err.Cause() 会把dubbo 内部Wrap 的异常吃掉，比如failover内的重试异常信息。

2. 另外我觉得这里不需要打印err , 应该把异常打印返回给用户就可以了。因为用户一定会处理这个异常的，如果没有处理那就是用户的代码由问题了。如果用户打印了warn，这的日志就是重复打印了。

**Comment by LaurenceLiZhixin** [comment]
我认为这块的逻辑是合理的。
1. failover 重试信息我认为没有必要返回给用户层，按照现在的逻辑，只需要打印出来即可。
2. 用户层希望拿到的是用户层的error，在triple协议中，这个err.Cause() 拿到的才是真实的用户层error，其内部包含了报错堆栈信息/attachemnt等内容，可供用户在用户层取出来。如果包在了wrap里面，就不方便拿出来了。 @XiaoWeiKIN 您觉得呢？

**Comment by XiaoWeiKIN** [comment]
重试失败后的的err需要提供出来，不然怎么知道重试了。proxy是否打印err日志可以暂时不做修改。
