### ISSUE TITLE
Fix: improve the unit coverage ratio

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go#1562]
**What happened**:

the ut of the following source files are remarked.

```
    protocol/dubbo/dubbo_protocol_test.go
    registry/etcdv3/service_discovery_test.go
    registry/zookeeper/service_discovery_test.go
    registry/nacos/service_discovery_test.go
    registry/file/service_discovery_test.go
```

**What you expected to happen**:

1 delete out of date ut files;
2 fix the left source file's wrong uts.

**Comment by LaurenceLiZhixin** [comment]
registry/file/service_discovery_test.go 可以直接删掉
service-discovery：file 相关的可以全部在3.0 删掉。

**Comment by LaurenceLiZhixin** [comment]
@Mulavar @justxuewei

**Comment by beiping0** [comment]
github:m18827119865_2@163.com

**Comment by AlexStocks** [comment]
https://github.com/apache/dubbo-go/blob/master/registry/zookeeper/service_discovery_test.go
