### ISSUE TITLE
nacos开启权限之后，报错service XXXProvider export failed! err: Registry protocol new exporter error, registry is

### ISSUE THREAD

**Issue by guoxf** [apache/dubbo-go#1594]
Nacos版本是2.0.3
nacos开启了NACOS_AUTH_ENABLE=true

dubbogo版本是v3.0.0-rc3

ERROR   config/provider_config.go:93    service IdentityProvider export failed! err: Registry protocol new exporter error, registry is {nacos://nacos:nacos@127.0.0.1:8848?group=&namespace=&registry=nacos&registry.label=true&registry.preferred=false&registry.role=3&registry.timeout=3s&registry.ttl=10s&registry.weight=0&registry.zone=&simplified=false}, url is {tri://:20003/org.atali.Identity?accesslog=&app.version=1.0.0&application=usercenter&auth=&bean.name=IdentityProvider&cluster=failover&environment=dev&execute.limit=&execute.limit.rejected.handler=&export=true&group=&interface=org.atali.Identity&loadbalance=random&message_size=4&metadata-type=local&module=local&name=usercenter&organization=atali&owner=&param.sign=&registry.role=3&release=dubbo-golang-3.0.0&retries=&serialization=&service.filter=echo%2Cmetrics%2Ctoken%2Caccesslog%2Ctps%2Cgeneric_service%2Cexecute%2Cpshutdown&side=provider&timestamp=1637199522&tps.limit.interval=&tps.limit.rate=&tps.limit.rejected.handler=&tps.limit.strategy=&tps.limiter=&version=&warmup=}
dubbo.apache.org/dubbo-go/v3/config.(*ProviderConfig).Load
        /home/xxxx/project/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.0-rc3/config/provider_config.go:93
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Start.func1
        /home/xxx/project/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.0-rc3/config/root_config.go:198
sync.(*Once).doSlow
        /opt/go/src/sync/once.go:68
sync.(*Once).Do
        /opt/go/src/sync/once.go:59
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Start
        /home/xx/project/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.0-rc3/config/root_config.go:197
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Init
        /home/xxx/project/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.0-rc3/config/root_config.go:192
dubbo.apache.org/dubbo-go/v3/config.Load
        /home/xx/project/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.0-rc3/config/config_loader.go:51
main.main
        /home/xxx/project/src/github.com/nooocode/usercenter/main.go:30
runtime.main
        /opt/go/src/runtime/proc.go:255
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by justxuewei** [comment]
cc @zhaoyunxing92

**Comment by guoxf** [comment]
这是复现测试代码 https://github.com/guoxf/dubbogo-demo

**Comment by LaurenceLiZhixin** [comment]
目前需要将username和password放置在param里，之后会防止在配置字段中。@zhaoyunxing92

**Comment by sanxun0325** [comment]
pr:https://github.com/apache/dubbo-go/pull/1645

**Comment by LaurenceLiZhixin** [comment]
The problem is fixed.
