### ISSUE TITLE
i hope dubbo-go can support register to polarismesh

### ISSUE THREAD

**Issue by chuntaojun** [apache/dubbo-go#1601]
**What would you like to be added**:

i hope dubbo-go can support register to polarismesh

**Why is this needed**:

i hope dubbo-go can support register to polarismesh

**Comment by chuntaojun** [comment]
i will resolve it

**Comment by AlexStocks** [comment]
Pls attention that the current develop branch is v3.0 which is compatible with dubbo 3.0. Dubbo-go has another maintainable branch v1.5 compatible with dubbo 2.7.

So pls let us know the dubbo-go version u want to use.

**Comment by chuntaojun** [comment]
may be i want to suppor dubbo v3.0 now，and latter i will support v1.5

**Comment by LaurenceLiZhixin** [comment]
Thanks for your great deal. I guess the feature is fixed and samples is needed.
