### ISSUE TITLE
cannot find method [$invokeAsync] of service 

### ISSUE THREAD

**Issue by xfstart07** [apache/dubbo-go#1627]
**What happened**:

报错信息:

```
filter_impl/echo_filter.go:50  $invokeAsync,3
proxy_factory/default.go:110  cannot find method [$invokeAsync] of service 
```

Dubbo-Java 使用异步泛化调用 dubbo-go ,但是没有 invokeAsync 方法,导致报错

**What you expected to happen**:

期望dubbo-go支持 invokeAsync 方法

**Anything else we need to know?**:

Dubbo-Java 客户端版本 2.7 
Dubbo-go 版本 1.5.7

**Comment by LaurenceLiZhixin** [comment]
目前的确没有这个方法。只提供了$invoke方法。可以加我们钉钉群聊一下你们的应用场景。 @xfstart07

**Comment by LaurenceLiZhixin** [comment]
cc @luck116

**Comment by luky116** [comment]
fixed by : https://github.com/apache/dubbo-go/pull/1674/files
