### ISSUE TITLE
copier 0.3.4 nested struct, struct starts with lowercase, cannot copy

### ISSUE THREAD

**Issue by sanxun0325** [apache/dubbo-go#1646]
**What happened**:
in dubbo go url.SubURL.Clone cannot copy, see:https://github.com/jinzhu/copier/issues/122
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by win5do** [comment]
dubbo-go 作为一个基础 rpc 库应该减少非必要的外部依赖。

copier.Copy 只在 URL clone 中使用了，建议自己实现一下。

”A little copying is better than a little dependency.“
