### ISSUE TITLE
dubbo-go 使用1.5.7-rc1版本，运行时偶现getty相关的panic导致重启。

### ISSUE THREAD

**Issue by Threadalive** [apache/dubbo-go#1650]
**What happened**:
dubbo-go 使用1.5.7-rc1版本，运行时偶现getty相关的panic导致重启。看现象是有session close变为空导致的。

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
相关日志如下：
2021/12/02 17:21:01 executing load method in ticker
2021/12/02 17:21:02 get rootDomains number:131
2021/12/02 17:21:02 get params number: 13316
2021/12/02 17:21:02 get entity number:7679
2021/12/02 17:21:02 get whiteListModels number:3632
2021-12-02T17:21:02.977+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:21:02.982+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:21:11.251+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:21:14.322+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:21:17.960+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:21:30.464+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:21:30.472+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:21:30.477+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:21:36.212+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:21:55.448+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:22:00.102+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:22:03.321+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:22:03.327+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:22:11.860+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:22:17.961+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:22:18.003+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:22:31.155+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:22:31.162+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:22:31.185+0800	[33mWARN[0m	there is no cache invoker.
2021-12-02T17:22:36.664+0800	[33mWARN[0m	there is no cache invoker.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10fc3af]

goroutine 150500200 [running]:
github.com/apache/dubbo-getty.(*session).GetActive(0xc002774a80, 0x0, 0x0, 0xc0027fb890)
	<autogenerated>:1 +0x2f
git.n.xiaomi.com/open-lib/dubbo-go/remoting/getty.(*gettyRPCClient).close.func1.2(0xc00658c1f0, 0xc006b91fe0)
	/go/pkg/mod/git.n.xiaomi.com/open-lib/dubbo-go@v1.5.7-rc1-fix-blacklist-mi/remoting/getty/getty_client.go:541 +0x138
created by git.n.xiaomi.com/open-lib/dubbo-go/remoting/getty.(*gettyRPCClient).close.func1
	/go/pkg/mod/git.n.xiaomi.com/open-lib/dubbo-go@v1.5.7-rc1-fix-blacklist-mi/remoting/getty/getty_client.go:535 +0xbe

**Comment by cjphaha** [comment]
服务端/客户端的配置可以提供下吗，我看看能否复现出问题

**Comment by Threadalive** [comment]
> 服务端/客户端的配置可以提供下吗，我看看能否复现出问题

go端通过泛化调用，调用java服务端，client端配置如下：
go client端配置：
# dubbo client yaml configure file

# client
request_timeout: "1s"
# connect timeout
connect_timeout: "1s"

# application config
application:
  organization: "dubbo.io"
  name: "dubbo-go apisdk"
  module: "dubbo-go client"
  version: "1.0"
  environment: "pro"

# registry config
registries:
  "nacos":
    protocol: "nacos"
    timeout: "3s"
    address: "nacos.systech.b2c.srv:80"
    username: "read-users"
    password: "read-users"

# reference config
references:
  "GoodsStockService":
    registry: "nacos"
    protocol: "dubbo"
    interface: "com.xiaomi.goods.gis.api.GoodsStockService"
    cluster: "failfast"
    group: "online"
    version: "0.1"
    generic: true
  "OrgInfoService":
    registry: "nacos"
    protocol: "dubbo"
    interface: "com.xiaomi.goods.gis.api.OrgInfoService"
    cluster: "failfast"
    group: "online"
    version: "0.1"
    generic: true
  "GoodsInfoNewService":
    registry: "nacos"
    protocol: "dubbo"
    interface: "com.xiaomi.goods.gis.api.GoodsInfoNewService"
    cluster: "failfast"
    group: "online"
    version: "0.1"
    generic: true

# shutdown_conf:
shutdown_conf:
  timeout: "60s" # 接收推出信号之后，等待的最大时长
  step_timeout: "10s" # 接收推出信号之后，每隔10s检查一下是否还有待处理

# protocol config
protocol_conf:
  dubbo:
    connection_number: 2
    heartbeat_period: "5s"
    session_timeout: "180s"
    getty_session_param:
      compress_encoding: false
      tcp_no_delay: true
      tcp_keep_alive: true
      keep_alive_period: "120s"
      tcp_r_buf_size: 262144
      tcp_w_buf_size: 65536
      pkg_rq_size: 1024
      pkg_wq_size: 512
      tcp_read_timeout: "1s"
      tcp_write_timeout: "5s"
      wait_timeout: "1s"
      max_msg_len: 1024000
      session_name: "client"

**Comment by debuginn** [comment]
remoting/getty/getty_client.go:452

对于 remove session 的时候判断了 len(c.session) ==0 之后进行 close

![image](https://user-images.githubusercontent.com/28979768/146122065-11ea5e59-8479-4a2e-89e7-24919edf2ace.png)

之后在 close 操作的时候 len(c.session) == 0   for range 操作并没有啥问题

**Comment by wenxuwan** [comment]
@debuginn @Threadalive hi guys, can you provider more detail  logs before panic ?

**Comment by debuginn** [comment]
@wenxuwan 目前只有这些信息，panic 之后容器就被销毁了，这个问题挺常见的 再出现我这边联系 sre 试着看看可否获取到更多的堆栈信息

**Comment by debuginn** [comment]
@wenxuwan 

目前做了 防御处理，但是为啥出现 nil 未能复现
```go
if s == nil || s.session == nil {
	logger.Error("s or session is nil, s: %+v", s)
	continue
}
```

上线了这个代码之后 又出现了panic 
感觉离真相更近了

在panic 之前报了这个错误
```base
[31mERROR[0m	WritePkg error: session Already Closed, &remoting.Response{ID:407426, Version:"2.0.2", SerialID:0x2, Status:0x14, Event:true, Error:error(nil), Result:interface {}(nil)}
```

**Comment by debuginn** [comment]
@wenxuwan 
![image](https://user-images.githubusercontent.com/28979768/146525551-1ee42365-4d15-4c83-8b67-03e5976519a6.png)
出现panic 是这里，可以先修复一下 将日志打印优化一下

**Comment by wenxuwan** [comment]
> getty_client.go

![image](https://user-images.githubusercontent.com/11661906/146530054-54b94e92-1197-4d45-94a3-eab66ce078b9.png)

肯定是session被置为nil了，但目前还没找到哪里做的操作，你对照日志看看有什么发现没。

**Comment by AlexStocks** [comment]
@debuginn another question, we have release v1.5.7. After u fixed this problem, pls upgrade to this latest version.

**Comment by debuginn** [comment]
@AlexStocks ok, we will upgrade as soon as possible.

**Comment by wenxuwan** [comment]
@debuginn 

我看了一下代码，感觉是在gc函数里面，把Connection 置为nil了，能帮忙看下标红的log有打印没？

![image](https://user-images.githubusercontent.com/11661906/146645795-a49ca658-d9bb-412c-83bb-cf24eb4a7c6f.png)


![image](https://user-images.githubusercontent.com/11661906/146645780-a0ddd33a-842e-4a73-83f7-acd4262b8510.png)

**Comment by debuginn** [comment]
@wenxuwan 好的 我这边观察下。thanks

**Comment by wenxuwan** [comment]
> @wenxuwan 好的 我这边观察下。thanks

可以在s.Connection=nil前面加个log看看，应该是session里面的Connection被置为nil了.

**Comment by debuginn** [comment]
@wenxuwan 好。但是我们的版本没有 handleLoop函数 我们计划先升级一下 dubbo-go。之后在观察对应的问题

**Comment by AlexStocks** [comment]
@debuginn After u upgrade your dubbogo version, is there any feedback now?

**Comment by Lvnszn** [comment]
看着是链接超时被关闭的时候，session里面的connection会被设置为nil， close中开启了新的协程去关闭但是没有加锁，这样会出现在引用connection中的方法的时候会出现panic的问题。
