### ISSUE TITLE
dubbo rpc异步调用和同步的接口方式一样，对上层使用则无感知，不用自己维护异步请求和回复的关联关系

### ISSUE THREAD

**Issue by yechongwei** [apache/dubbo-go#1657]
现在场景是 代理网关对外提供https同步接口，dubbo对内rpc调用
希望dubbo rpc对内使用异步调用时 能在底层帮忙适配，做到和dubbo rpc同步接口一样 对上层无感知
现在用dubbo rpc同步接口的情况是如果一条连接超时，这个连接就会占用直到超时返回

**Comment by justxuewei** [comment]
> 能在底层帮忙适配，做到和dubbo rpc同步接口一样 对上层无感知

这句话应该怎么理解？能给出更详细的使用场景吗？

**Comment by yechongwei** [comment]
同步非阻塞，针对socket连接 对方没回复数据，这个连接还能继续发送请求
