### ISSUE TITLE
dubbo 服务端向客户端发起请求

### ISSUE THREAD

**Issue by yechongwei** [apache/dubbo-go#1658]
业务上基本上都是dubbo代理网关客户端向dubbo服务端发起请求，然后服务端回复给客户端
现在有另外一种场景，服务端下有业务需要向上dubbo代理网关请求，希望能实现这种的业务场景

**Comment by AlexStocks** [comment]
> 业务上基本上都是dubbo代理网关客户端向dubbo服务端发起请求，然后服务端回复给客户端 现在有另外一种场景，服务端下有业务需要向上dubbo代理网关请求，希望能实现这种的业务场景

要不你看看这个项目 github.com/apache/dubbo-go-pixiu ，能否满足你的需求？

**Comment by LaurenceLiZhixin** [comment]
@yechongwei Any problem? If there is no feed back, we would close this issue soon, please join our dingtalk group if you want to discuss with us.
