### ISSUE TITLE
start dubbogo server, node already  exists  but program exit 

### ISSUE THREAD

**Issue by phial3** [apache/dubbo-go#1660]
![image](https://user-images.githubusercontent.com/27754514/145510902-7b07c48a-bbe5-485f-817b-42366d00c338.png)

**Comment by LaurenceLiZhixin** [comment]
请问是用的版本是？可以加入我们钉钉群讨论一下。 @phial3

**Comment by Mulavar** [comment]
请发一下使用的 dubbogo 版本，以及说明下具体的使用场景。
