### ISSUE TITLE
When using the Polaris registry, InstanceRegisterRequest needs to set the value of the TTL field

### ISSUE THREAD

**Issue by chuntaojun** [apache/dubbo-go#1687]
**What happened**:

If the TTL field is not set, polaris will think that this instance does not need to perform the heartbeat health check operation, then after the instance goes offline, the instance cannot be converted to unhealthy normally.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by LaurenceLiZhixin** [comment]
Can this issue be closed? @chuntaojun
