### ISSUE TITLE
3.0版本下 http协议是否能正常使用

### ISSUE THREAD

**Issue by ztelur** [apache/dubbo-go#1692]
**What happened**:

3.0版本的 http 协议似乎有些问题，看代码 `"dubbo.apache.org/dubbo-go/v3/protocol/rest/config/reader"` 虽然可以添加特殊的配置读取器，但是没有任何地方使用到，导致启动时`GetRestProviderServiceConfig`返回nil，然后panic。

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by zhaoyunxing92** [comment]
目前不支持

**Comment by LaurenceLiZhixin** [comment]
3.0 版本目前并不直接支持http协议，推荐开发人员自己写http接口。如有生产诉求，可以提给我们

**Comment by PhilYue** [comment]
@PhilYue
