### ISSUE TITLE
when i run server.go in the sample_code, it reported an type error

### ISSUE THREAD

**Issue by zhou-yong-long** [apache/dubbo-go#1705]
# github.com/apache/dubbo-go/remoting/zookeeper
..\pkg\mod\github.com\apache\dubbo-go@v1.5.7\remoting\zookeeper\listener.go:252:35: cannot use &event (value of type *chan struct{}) as type chan zk.Event in argument to l.client.RegisterEvent
..\pkg\mod\github.com\apache\dubbo-go@v1.5.7\remoting\zookeeper\listener.go:255:38: cannot use &event (value of type *chan struct{}) as type chan zk.Event in argument to l.client.UnregisterEvent
..\pkg\mod\github.com\apache\dubbo-go@v1.5.7\remoting\zookeeper\listener.go:260:38: cannot use &event (value of type *chan struct{}) as type chan zk.Event in argument to l.client.UnregisterEvent
..\pkg\mod\github.com\apache\dubbo-go@v1.5.7\remoting\zookeeper\listener.go:263:38: cannot use &event (value of type *chan struct{}) as type chan zk.Event in argument to l.client.UnregisterEvent
..\pkg\mod\github.com\apache\dubbo-go@v1.5.7\remoting\zookeeper\listener.go:268:38: cannot use &event (value of type *chan struct{}) as type chan zk.Event in argument to l.client.UnregisterEvent

**Comment by justxuewei** [comment]
What is `sample_code` you mentioned on the title? Please append more information to make us reproduce it, instead copy & paste the error logs.

**Comment by AlexStocks** [comment]
@zhou-yong-long Pls append ur dubbo-go version. U'd better append ur test example to let us reproduce this bug.

**Comment by zhou-yong-long** [comment]
`import (
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	hessian "github.com/apache/dubbo-go-hessian2"
	"github.com/apache/dubbo-go/common/logger"
	"github.com/apache/dubbo-go/common/yaml"
	"github.com/apache/dubbo-go/config"
	_ "github.com/apache/dubbo-go/common/proxy/proxy_factory"
	_ "github.com/apache/dubbo-go/registry/protocol"
    _ "github.com/apache/dubbo-go/registry/zookeeper" // @v1.5.7
)`

i had debug the code, and find the problem is " 'extension' package in 'dubbo-go/common' which would load registry for zookeeper needs 'zookeeper' package init its registry before, so i changed the original code about zookeeper/listener.go and it runs well
