### ISSUE TITLE
When service discovery is enabled, if the consumer exits, the producer will report an error

### ISSUE THREAD

**Issue by titanhw** [apache/dubbo-go#1722]
**What happened**:
producer throws an error : An existing connection was forcibly closed by the remote host
```
ERROR   dubbo-getty@v1.4.5/session.go:549   [session.conn.read] = error:read tcp *** -> ***: 
wsarecv: An existing connection was forcibly closed by the remote host.
github.com/apache/dubbo-getty.(*gettyTCPConn).recv
```

**What you expected to happen**:

No error should be reported when the consumer is closed

**How to reproduce it (as minimally and precisely as possible)**:
make sure service discovery is enabled, exit the consumer process normally, the producer will report the error

**Anything else we need to know?**:

Comparing the results of these two samples, you will find the difference
[https://github.com/apache/dubbo-go-samples/tree/master/helloworld](https://github.com/apache/dubbo-go-samples/tree/master/helloworld)
[https://github.com/apache/dubbo-go-samples/tree/master/registry/servicediscovery/nacos](https://github.com/apache/dubbo-go-samples/tree/master/registry/servicediscovery/nacos)

"servicediscovery/nacos' will throw "wsarecv: An existing connection was forcibly closed by the remote host." error

**Comment by TitanHW** [comment]
This problem occurs in sample
https://github.com/apache/dubbo-go-samples/tree/master/registry/servicediscovery/nacos

**Comment by XiaoWeiKIN** [comment]
hi boy，describe the version of dubo-go in the case.

**Comment by XiaoWeiKIN** [comment]
i'm going to try to reproduce this case.

**Comment by AlexStocks** [comment]
@sanxun0325
