### ISSUE TITLE
Does the dubbo-go client has supported nacos?

### ISSUE THREAD

**Issue by lizhenmxcz** [apache/dubbo-go#173]
**What happened**:
when import nacos registry, it report errors: panic: Failed to check the status of the service XXXlService . No provider available for the service to the consumer use dubbo version 2.7.3
**What you expected to happen**:
i use the nacos registry for dubbo 2.7.3 and use spring boot as provider
**How to reproduce it (as minimally and precisely as possible)**:
i just import "github.com/apache/dubbo-go/registry/nacos" in examples helloword app go-client client.go file,and run it
**Anything else we need to know?**:

**Comment by AlexStocks** [comment]
@lixiaojiee yes. u can got it in the develop branch.

**Comment by lizhenmxcz** [comment]
@AlexStocks when to release this feature

**Comment by AlexStocks** [comment]
I do not know. u can use it now in ur test env.
