### ISSUE TITLE
word spell error

### ISSUE THREAD

**Issue by lazyfighter** [apache/dubbo-go#176]
**What happened**:

remote/listener.go
```go
const (
	EventTypeAdd = iota
	EventTypeDel
	EvnetTypeUpdate
)
```

`EvnetTypeUpdate` should be `EventTypeUpdate`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by gaoxinge** [comment]
@lazyfighter Thanks! We have fixed typo in https://github.com/apache/dubbo-go/pull/177. This has been merged into [develop branch](https://github.com/apache/dubbo-go/tree/develop), and will be merged into master later.

**Comment by lazyfighter** [comment]
@gaoxinge multiplex this issue, another question ,is there necessary use goroutine start `time.AfterFunc`  at `examples/helloworld/dubbo/go-server/app/server.go`

```go
func initSignal() {
	signals := make(chan os.Signal, 1)
	// It is not possible to block SIGKILL or syscall.SIGSTOP
	signal.Notify(signals, os.Interrupt, os.Kill, syscall.SIGHUP, syscall.SIGQUIT, syscall.SIGTERM, syscall.SIGINT)
	for {
		sig := <-signals
		logger.Infof("get signal %s", sig.String())
		switch sig {
		case syscall.SIGHUP:
			// reload()
		default:
			go time.AfterFunc(time.Duration(survivalTimeout), func() {
				logger.Warnf("app exit now by force...")
				os.Exit(1)
			})

			// The program exits normally or timeout forcibly exits.
			fmt.Println("provider app exit now...")
			return
		}
	}
}
```
because, `time.AfterFunc()` is  async , dont need a goroutine wrap

**Comment by AlexStocks** [comment]
@lazyfighter will u submit a pull request to fix this issue? thx so much.
