### ISSUE TITLE
Enhance Observability with support of OpenTelemetry

### ISSUE THREAD

**Issue by hanyuancheung** [apache/dubbo-go#1774]
### What would you like to be added
As the migration of OpenTracing and OpenCensus, [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-go) becomes the standard in the observability field. I've checked the related module in dubbo-go(including [dubbo-go-sample](https://github.com/apache/dubbo-go-samples/tree/master/tracing)), and now still use OpenTracing to exporter trace signal to Jaeger or Zipkin backend, as well as use Prometheus to exporter metrics signal to backend.

### Proposed Solution
I wonder if you guys like to integrate the ability of the OpenTelemetry, package into the independent module, which is for the use of external users, code structure like below:
- observability
  - tracing
  - metrics
  - other signals

#### Alternatives
Because [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver) provides all different kinds of receivers, so users could deploy collector component by using like jaegerreceiver or zipkinreceiver, and the data model is transformed from OpenTracing to OpenTelemetry automatically.
I do not know which way dubbo-go community prefer.
If the former way looks good, I'll work on it to provide an OpenTelemetry version module. If latter, I'll add doc or readme to let users know how to use OpenTracing to export trace and metrics into OpenTelemetry backend.

**Comment by hanyuancheung** [comment]
@AlexStocks PTAL.

**Comment by AlexStocks** [comment]
I prefer the former solution. So pls add an solution to integrate the OpenTelemetry into dubbogo.

**Comment by LaurenceLiZhixin** [comment]
cc @pherzheyu

**Comment by pherzheyu** [comment]
OpenTelemetry trace is already a stable feature. Going on.

**Comment by hanyuancheung** [comment]
> @hanyuancheung how is this task going now?

Yeah, I've working on it. Sorry that I've been slowed down by being too busy recently. I'll finish it as soon as possible.

cc @pherzheyu @AlexStocks
