### ISSUE TITLE
有关于dubbogo官方文档中的错误

### ISSUE THREAD

**Issue by quiet-xu** [apache/dubbo-go#1796]
[https://dubbogo.github.io/zh-cn/docs/user/concept/configuration.html](url)
在该文档中request_timeout: 3s 是错误的，在源代码中
`RequestTimeout string `default:"3s" yaml:"request-timeout" json:"request-timeout,omitempty" property:"request-timeout"``
序列化是request-timeout

**Comment by zhaojames0707** [comment]
官方文档中仍然是错误的：https://dubbo.apache.org/zh/docs/languages/golang/dubbo-go-3.0/concept/configuration/
