### ISSUE TITLE
GSoC 2022: Observasibility and Metrics 

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [apache/dubbo-go#1807]
Please read the [Observasibility](https://github.com/apache/dubbo-awesome/blob/master/proposals/D4-observability.md) here first to know about the ultimate goal behind this issue.

If you are interested in this project and the objective described in the proposal, please leave comments below so we can further exchange information on the tasks that need to be done.

After you submited proposal in https://summerofcode.withgoogle.com/
Please join DingTalk group 35345725 for gsoc consulting, and group 23331795 for Dubbo-go community.

**Comment by txfs19260817** [comment]
Hello, I am interested in this project.

My name is Zishuo Ding and I am a current graduate student at Carnegie Mellon University. I have some experience in both working and contributing to open source. 

Thank you.

**Comment by jyz0309** [comment]
Hello, I am interested in this project too.

I am a PingCAP employee and have graduated from school. I have contributed some code to open source project, and also have some experience in Observasibility, want to take part in this idea.

Looking forward to exchanging information with you.

**Comment by AlexStocks** [comment]
@jyz0309 would you please join the dingding group 23331795 and then have a talk with me, in which I am the group owner.

**Comment by LaurenceLiZhixin** [comment]
@jyz0309 @txfs19260817 
After you submited proposal in https://summerofcode.withgoogle.com/
Please join DingTalk group 35345725 for gsoc consulting, and group 23331795 for Dubbo-go community.
