### ISSUE TITLE
GSoC 2022: Thin SDK for Proxy Mesh

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [apache/dubbo-go#1809]
Please read the [detailed proposal of Dubbo Proxy Mesh](https://github.com/apache/dubbo-awesome/blob/master/proposals/D3.1-thinsdk-sidecar-mesh.md) here first to know about the ultimate goal behind this issue.

We have started the development of Dubbo Proxy Mesh for a while, so that means you don't have to start the project from the scratch, anyone who gets involved needs to start with a specific task at hand. As for the specific tasks to do in GSoC 2022, we are still working on it, we do have some tasks that can be distributed but we hope to discuss them with the contributors first.

So if you are interested in this project and the objective described in the proposal, please leave comments below so we can further exchange opinions.

Please don't forget to apply for GSoC from its official website when the application slot opens.

After you submited proposal in https://summerofcode.withgoogle.com/
Please join DingTalk group 35345725 for gsoc consulting, and group 23331795 for Dubbo-go community.

**Comment by sheny1xuan** [comment]
您好，我对这个项目比较感兴趣，请问有没有更多的资料可以参考呢？

**Comment by LaurenceLiZhixin** [comment]
@sheny1xuan 
After you submited proposal in https://summerofcode.withgoogle.com/
Please join DingTalk group 35345725 for gsoc consulting, and group 23331795 for Dubbo-go community.
