### ISSUE TITLE
dubbogo日志打印建议

### ISSUE THREAD

**Issue by leapig** [apache/dubbo-go#1815]
版本：v3.0.2-0.20220316080055-f481b16d363c

打印了过多nacos的日志信息，影响开发和调试。日志级别设为error也关闭不了

**Comment by leapig** [comment]
![image](https://user-images.githubusercontent.com/92301116/162173821-cac15339-e294-4f82-8c05-8e1a258a9c6a.png)

**Comment by debuginn** [comment]
附议  这种对于业务开发没有必要保留。或者指定对应级别及路径打印就可以了

**Comment by sanxun0325** [comment]
dubbo:
  registries:
    nacosWithCustomGroup:
      protocol: nacos
      address: 127.0.0.1:8848
      group: myGroup # default is DEFAULT_GROUP
      params:
        nacos.logDir: /tmp
        nacos.logLevel:error

**Comment by sanxun0325** [comment]
1.5.7参考：
``` yaml
registries:
  "demoNacos":
    protocol: "nacos"
    timeout: "3s"
    address: "127.0.0.1:8848"
    params:
         logDir: /tmp
         logLevel: error

**Comment by debuginn** [comment]
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/28979768/162350851-b9885f17-c4f8-4375-93d2-e80757a6679b.png">
看了下1.5.7的代码。发现对应制定日志位置可以，但是指定打印级别并没有声明。是不是在该版本是一个无效的设置项？

**Comment by zhaoyunxing92** [comment]
> <img alt="image" width="1033" src="https://user-images.githubusercontent.com/28979768/162350851-b9885f17-c4f8-4375-93d2-e80757a6679b.png">
> 
> 看了下1.5.7的代码。发现对应制定日志位置可以，但是指定打印级别并没有声明。是不是在该版本是一个无效的设置项？
