### ISSUE TITLE
1.5.7 不支持设置日志等级

### ISSUE THREAD

**Issue by debuginn** [apache/dubbo-go#1818]
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/28979768/162350851-b9885f17-c4f8-4375-93d2-e80757a6679b.png">
看了下1.5.7的代码。发现对应制定日志位置可以，但是指定打印级别并没有声明，是不是可以支持下

**Comment by zhaoyunxing92** [comment]
> <img alt="image" width="1033" src="https://user-images.githubusercontent.com/28979768/162350851-b9885f17-c4f8-4375-93d2-e80757a6679b.png">
> 
> 看了下1.5.7的代码。发现对应制定日志位置可以，但是指定打印级别并没有声明，是不是可以支持下

可以使用[v1.5.8-rc1](https://github.com/apache/dubbo-go/releases/tag/v1.5.8-rc1)这个版本
