### ISSUE TITLE
RPCResult code is not standard

### ISSUE THREAD

**Issue by lazyfighter** [apache/dubbo-go#182]
```go

type RPCResult struct {
	Attrs map[string]string
	Err   error
	Rest  interface{}
}

func (r *RPCResult) SetError(err error) {
	r.Err = err
}

func (r *RPCResult) Error() error {
	return r.Err
}

func (r *RPCResult) SetResult(rest interface{}) {
	r.Rest = rest
}

func (r *RPCResult) Result() interface{} {
	return r.Rest
}

func (r *RPCResult) SetAttachments(attr map[string]string) {
	r.Attrs = attr
}

func (r *RPCResult) Attachments() map[string]string {
	return r.Attrs
}

func (r *RPCResult) AddAttachment(key, value string) {
	r.Attrs[key] = value
}

func (r *RPCResult) Attachment(key, defaultValue string) string {
	v, ok := r.Attrs[key]
	if !ok {
		v = defaultValue
	}
	return v
}

```
member should be private ,`rest` rename to `body` maybe is better

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by fangyincheng** [comment]
member should be private, but `rest` is only result, it isn't a body for http.

**Comment by lazyfighter** [comment]
@fangyincheng body is not only for http, for example， MQ message has properties and messageBody ,i want to rename this member ,because i think `rest` cant  express result， i will create pr for private member , lay over rename

**Comment by lazyfighter** [comment]
`common/utils/net.go#GetLocalIP` will return empty string, 
![20190830192758](https://user-images.githubusercontent.com/17143488/64017590-89276180-cb5c-11e9-91ce-a4c2ca964726.jpg), on my mac network ,only have public interface and lookup interface ,so cant get ip
