### ISSUE TITLE
GSoC 2022: Dubo-go-boot project enriches other middleware adaptations

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [apache/dubbo-go#1837]
Similar to the Spring Boot project, which makes it easier for users to use dubo-Go projects, importing related packages provides middleware capabilities

So if you are interested in this project and the objective described in the proposal, please leave comments below so we can further exchange opinions.

After you submited proposal in https://summerofcode.withgoogle.com 
Please join DingTalk group 35345725 for gsoc consulting, and group 23331795 for Dubbo-go community.

Please don't forget to apply for GSoC from its official website when the application slot opens.

**Comment by jay-li-csck** [comment]
Hi, I am interested in go and middleware technology.
About me ,currently working in the airline ticket department of trip. Internship experience with XiaoMi.
Looking forward to replying with you.

**Comment by AlexStocks** [comment]
@jay-li-csck welcome. maybe u can join our dingding group 23331795 and then have a talk with me, in which I am the group owner.

**Comment by AlexStocks** [comment]
@pengjiaxin
