### ISSUE TITLE
Bug: the package size should not be greater than 8MiB

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go#1839]
**What happened**:

在 dubbogo 中，很多处定义 package size 不能大于 8MiB

![image](https://user-images.githubusercontent.com/7959374/163675817-9ff64482-6ec5-4e9e-a160-c0b1dd0f4cea.png)

**What you expected to happen**:

![image](https://user-images.githubusercontent.com/7959374/163675895-b003774b-f59a-42a0-ad4e-d5e25b4a92e8.png)

如上，既然给用户开了 getty session param 中 设定 max msg len 的口子，就不应该有上面这个限制

**Comment by sheny1xuan** [comment]
I am new here. Plz assign to me，I'll do it.

**Comment by zonghaishang** [comment]
@AlexStocks  dubbo框架限制了8M大小: https://github.com/apache/dubbo/blob/868c02cbc3d1f85a92b0cdc1a98ad49372228a23/dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Constants.java#L74

**Comment by sheny1xuan** [comment]
我

**Comment by AlexStocks** [comment]
> @AlexStocks dubbo框架限制了8M大小: https://github.com/apache/dubbo/blob/868c02cbc3d1f85a92b0cdc1a98ad49372228a23/dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Constants.java#L74

The reply from dubbo is "netty这边用的是共享链接，也就是所有服务共用一条tcp", so "dubbo 有个限制，包的长度不能超过 8MiB".
