### ISSUE TITLE
tri协议暴露服务，随机端口不可用

### ISSUE THREAD

**Issue by wujincheng2333** [apache/dubbo-go#1850]
![image](https://user-images.githubusercontent.com/39256897/164215358-7b48d729-f4e1-4151-b2bd-e36e52e2a2af.png)
port <= 0的时候无法成立，应该转Int再比较？

**Comment by LaurenceLiZhixin** [comment]
我认为可以的，可以提交个pr修一下

**Comment by wujincheng2333** [comment]
> 我认为可以的，可以提交个pr修一下 @wujincheng2333

#1857
