### ISSUE TITLE
the document should be update

### ISSUE THREAD

**Issue by 106umao** [apache/dubbo-go#1878]
I checked the dubbogo-cli source code and found that the protoc-gen-go plugin is not relied on, but the quick start page of the documentation uses this plugin, dubbogo-cli install all does not install the protoc-gen-go plugin, and there are many steps to follow The description lacks the use of this plugin, resulting in the plugin not found problem. It should be that you updated the code and then forgot to maintain the documentation. If you need to maintain it, please assign this issue to me

**Comment by LaurenceLiZhixin** [comment]
Thanks, could you help up to fix it ? @106umao

**Comment by CherishCai** [comment]
the same problem and I install protoc-gen-go use Mac: Homebrew ...
> brew install protoc-gen-go

**Comment by 106umao** [comment]
> the same problem and I install protoc-gen-go use Mac: Homebrew ...
> 
> > brew install protoc-gen-go

You can try to download protoc-gen-dubbo3grpc through dubbogo-cli, it may solve your problem

**Comment by 106umao** [comment]
Sorry, this issue may be because I don't know enough about dubbogo-cli. I don't know why the package downloaded using `dubbogo-cli install all` is missing protoc-gen-go, but it was successfully downloaded today in the same environment. , the console output is as follows
` 
go install github.com/dubbogo/tools/cmd/imports-formatter@latest
go install github.com/dubbogo/tools/cmd/protoc-gen-dubbo3grpc@latest
go install github.com/dubbogo/tools/cmd/protoc-gen-go-triple@v1.0.10-rc2
`
I didn't read the code of `github.com/dubbogo/tools/cmd/protoc-gen-dubbo3grpc` carefully before, but I just saw that protoc-gen-go is depended on by this plugin. I guess the download was not successful because of network problems. So I will close this issue
