### ISSUE TITLE
Ref: Maybe use the same const in graceful_shutdown_config.go and graceful_shutdown.go?

### ISSUE THREAD

**Issue by CherishCai** [apache/dubbo-go#1892]
https://github.com/apache/dubbo-go/blob/4a62aa28e4f942db4c02c0725ad2a77cbbbd9db7/config/graceful_shutdown_config.go#L36

https://github.com/apache/dubbo-go/blob/4a62aa28e4f942db4c02c0725ad2a77cbbbd9db7/config/graceful_shutdown.go#L54

**What would you like to be added**:
Just use the same const.
使用同一个常量值便可。

Should it be changed in config/graceful_shutdown.go?
是否应该在 config/graceful_shutdown.go 中更改？
```go
const defaultShutDownTime = defaultTimeout
```

**Why is this needed**:
Const that seem to have the same effect are now defined in two places.
现在看似同样作用的常量值被定义在两个地方。

**Comment by CherishCai** [comment]
`defaultShutDownTime` 承担了两个责任：默认值和最小可配置值；

https://github.com/apache/dubbo-go/blob/4a62aa28e4f942db4c02c0725ad2a77cbbbd9db7/config/graceful_shutdown.go#L216-L223

我是 Java 开发者，看了一段时间 Golang，现在以 dubbogo 作为更深入学习的途径，哈哈也不知道上述描述的常量是否应该统一成一个。

**Comment by AlexStocks** [comment]
> https://github.com/apache/dubbo-go/blob/4a62aa28e4f942db4c02c0725ad2a77cbbbd9db7/config/graceful_shutdown_config.go#L36
> 
> https://github.com/apache/dubbo-go/blob/4a62aa28e4f942db4c02c0725ad2a77cbbbd9db7/config/graceful_shutdown.go#L54
> 
> **What would you like to be added**: Just use the same const. 使用同一个常量值便可。
> 
> Should it be changed in config/graceful_shutdown.go? 是否应该在 config/graceful_shutdown.go 中更改？
> 
> ```go
> const defaultShutDownTime = defaultTimeout
> ```
> 
> **Why is this needed**: Const that seem to have the same effect are now defined in two places. 现在看似同样作用的常量值被定义在两个地方。

变量意义不一样，不宜统一成一个吧。

**Comment by CherishCai** [comment]
好咧，看着用的地方也只有一个，看起来费解了一丢丢，所以提了个疑问。
