### ISSUE TITLE
[ASoC 2022] Dubbo-go supports token verification mechanism

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo-go#1906]
## Background

This is an basic subject of [ASoC 2022](https://opensource.alibaba.com/asoc2022) and https://github.com/apache/dubbo/issues/10088 .

Token verification refers to controlling permissions in the registry to decide whether to issue tokens to consumers, which can prevent consumers from bypassing the registry to access providers. In addition, the authorization method can be changed flexibly through the registration center without modifying the provider.

## Difficulty

Basic

## Mentor

- @LaurenceLiZhixin laurence@apache.org

## Output Requirement

When the Java-side Provider is configured with token="true", Dubbo-go needs to be able to call the service normally.

There is no prize for dubo-go community subject.

# 

## 背景

这是一个[阿里巴巴编程之夏 2022](https://opensource.alibaba.com/asoc2022) 的基础课题 https://github.com/apache/dubbo/issues/10088 。

令牌验证是指在注册中心控制权限，以决定要不要下发令牌给消费者，可以防止消费者绕过注册中心访问提供者。另外通过注册中心可灵活改变授权方式，而不需修改提供者。

## 难度

基础

## 导师

- @LaurenceLiZhixin laurence@apache.org

## 产出要求

当 Java 端 Provider 配置 token="true" 时，Dubbo-go 需要能够正常调用服务。

注：
Dubbo-go 社区 Asoc 题目没有申请到奖金，有开源之夏证书。

**Comment by tobehardest** [comment]
Does this problem still need to be solved?
