### ISSUE TITLE
[ASoC 2022] Dubbo-go Observasibility Support

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [apache/dubbo-go#1909]
## Background

This is an basic subject of [[ASoC 2022](https://opensource.alibaba.com/asoc2022)](https://opensource.alibaba.com/asoc2022) and https://github.com/apache/dubbo/issues/10088 .

Please read the [[Observasibility](https://github.com/apache/dubbo-awesome/blob/master/proposals/D4-observability.md)](https://github.com/apache/dubbo-awesome/blob/master/proposals/D4-observability.md) here first to know about the ultimate goal behind this issue.

## Difficulty

Middle

## Mentor

- @LaurenceLiZhixin [laurence@apache.org](mailto:laurence@apache.org)

## Output Requirement

Create Dubbo-go's observable capabilities based on the opentelementry protocol, Samples, Documentation.

There is no prize for dubo-go community subject.

# 

## 背景

这是一个[[阿里巴巴编程之夏 2022](https://opensource.alibaba.com/asoc2022)](https://opensource.alibaba.com/asoc2022) 的基础课题 https://github.com/apache/dubbo/issues/10088 。

参考 [[可视化](https://github.com/apache/dubbo-awesome/blob/master/proposals/D4-observability.md)](https://github.com/apache/dubbo-awesome/blob/master/proposals/D4-observability.md) Proposal，进行 Dubbo-go 框架可视化能力的扩展和完善，对齐 opentelementry 协议暴露。

## 难度

中等

## 导师

- @LaurenceLiZhixin [laurence@apache.org](mailto:laurence@apache.org)

## 产出要求

形成 Dubbo-go 基于opentelementry 协议的可观察能力， Samples，文档 。

注：
Dubbo-go 社区 Asoc 题目没有申请到奖金，有开源之夏证书。

**Comment by jyz0309** [comment]
I am interested to take part in, can you assign me? Thanks!

**Comment by AlexStocks** [comment]
@pengjiaxin

**Comment by pengjiaxin** [comment]
朋友，您的邮件我已收到，我将以超光速回复您。
