### ISSUE TITLE
consumer requests a offline provider without reporting an error

### ISSUE THREAD

**Issue by kep-w** [apache/dubbo-go#1946]
**What happened**: 
dubbo-go v3.0.1 (both consumer and provider).
Used nacos as registration Center. 
When the provider is upgraded, the new provider is online, and the old provider is offline, but the consumer will still request the old service without reporting an error. If configure retries=2, it is useless, because there is no error in the first request, and the request is considered to be successful.

**What you expected to happen**: we hope the consumer can request new provider or reporting an error at least.

**How to reproduce it (as minimally and precisely as possible)**: can offline the provider sees whether an error is reported after the consumer request.

**Anything else we need to know?**: 
golang version 1.15
cluster=failover 
retries=0 or retries=2 both no use.
<img width="458" alt="image" src="https://user-images.githubusercontent.com/23651144/176399165-9859d2ce-361e-45b4-b844-8ff50cab1c14.png">

**Comment by AlexStocks** [comment]
@sanxun0325

**Comment by sanxun0325** [comment]
@kep-w problem cannot be reproduced，could you provide more information, such as the metadata information of service registration in NACOS
such as:
<img width="504" alt="image" src="https://user-images.githubusercontent.com/28588342/178217767-b0c6cfa5-fbd3-4905-89e8-b9485eea6d78.png">

**Comment by AlexStocks** [comment]
@kep-w hey, guy, could u pls tell us how to reproduce this bug? Or can u tell me ur dingding name?

**Comment by kep-w** [comment]
> @kep-w hey, guy, could u pls tell us how to reproduce this bug? Or can u tell me ur dingding name?

hi, thanks for following and replying.
u can try the following process to reproduce：
1. one consumer and one provider start normally, and nacos has online info, consumer can request and get reply from provider
2. just offline the provider from nacos. at this time, consumer will still request the offlined provider. But now nacos has no available provider, consumer should not request provider that have been offline. --> this is the first question
3. stop the provider, means now no provider available in nacos and the offline  provider is not running. But now, consumer still request the provider that are offline and not running, and got no error. --> this is the second question
