### ISSUE TITLE
zookeeper注册中心的心跳包bug 

### ISSUE THREAD

**Issue by bakineW** [apache/dubbo-go#1949]
项目上提供者节点往返zookeeper注册中心流量还是一直很大  我的提供者大概有80个节点  每一个提供者节点都和zk注册中心通信发送100k/每秒的数据  有拦包看了下像是一些用于缓存的所有提供者的列表，注册中心一直发给提供者节点，提供者也在发给注册中心；

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by bakineW** [comment]
用的是版本是最新的3.0.2

**Comment by AlexStocks** [comment]
@Mulavar

**Comment by bakineW** [comment]
试试应用级服务发现
