### ISSUE TITLE
config.GetConsumerServiceByInterfaceName方法bug

### ISSUE THREAD

**Issue by fightGitHub93** [apache/dubbo-go#1952]
同一个interface，group不同，注册多个服务的时候，config.GetConsumerServiceByInterfaceName只会返回最后一个服务实列

**Comment by fightGitHub93** [comment]
使用config.SetConsumerService注册服务时，也不能通过传参的方式注册不同group的服务，只能硬编码注册。

**Comment by AlexStocks** [comment]
@zhaoyunxing92

**Comment by zhaoyunxing92** [comment]
`GetConsumerServiceByInterfaceName` 这个方法只能在启动的时候才用到

**Comment by AlexStocks** [comment]
@fightGitHub93 或许是我们没有get 到你的诉求。
 在这个 issue 中 @zhaoyunxing92 给你的这个 answer 是否满意？如果有异议，请及时在 issue 中回复。

**Comment by AlexStocks** [comment]
用户是想获取 Group 下的所有的服务。
