### ISSUE TITLE
Prometheus reporters fail to prevent creating concurrently

### ISSUE THREAD

**Issue by CoolIceV** [apache/dubbo-go#1953]
**What happened:**
When I want to collect custom metrics in filter, some metrics never changed. I think it may be caused by concurrent creation of metrics objects, the code tries to use syncMap's Load to avoid duplicate creation, but this is useless. 
https://github.com/apache/dubbo-go/blob/b7e348319f82444e18ecda284e20656d7ed3b861/metrics/prometheus/reporter.go#L296-L309
When I debug, I find that the Register() returns an AlreadyExist error, but this error is incorrectly ignored

**What you expected to happen:**
The same metrics object should be created only once and needs to be guaranteed to be registered successfully.

**How to reproduce it (as minimally and precisely as possible):**
![image](https://user-images.githubusercontent.com/42159666/177264112-791eb009-5cd2-4296-acb3-9fd1d7a4e521.png)

**Anything else we need to know?:**
In addition to counter, metrics such as Gauge should also have this problem

**Comment by AlexStocks** [comment]
@CoolIceV if you think this issue have been fixed by ur pr, pls close this issue. thx.
