### ISSUE TITLE
Go client调用远程服务时，报错：panic: reflect: call of reflect.Value.IsZero on zero Value

### ISSUE THREAD

**Issue by hgdhfq** [apache/dubbo-go#1956]
**What happened**:
Go client调用远程服务时，报错：panic: reflect: call of reflect.Value.IsZero on zero Value

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

注册发现 使用nacos2.0.3（docker：zhusaidong/nacos-server-m1:2.0.3）
JAVA和GO同时提供provider

JAVA-client正常调用，并且能够负载均衡
<img width="631" alt="image" src="https://user-images.githubusercontent.com/24693592/177749034-8a26b108-bea1-4f82-92da-0b3d717ddb7d.png">

Go-client 调用会出现报错
报错1：panic: reflect: call of reflect.Value.IsZero on zero Value

报错2：could not get the metadata info from remote provider: don't have this exporter, key: DEFAULT_GROUP@@dubbo.io/org.apache.dubbo.metadata.MetadataService:1.0.0

<img width="1540" alt="image" src="https://user-images.githubusercontent.com/24693592/177749298-3950a9dc-0d13-4483-bee3-1554a38c4068.png">

**Anything else we need to know?**:
java 代码： 
[spring-boot-gradle-test 2.zip](https://github.com/apache/dubbo-go/files/9062579/spring-boot-gradle-test.2.zip)

go 代码：
[dubbo-test.zip](https://github.com/apache/dubbo-go/files/9062584/dubbo-test.zip)

**Comment by AlexStocks** [comment]
@pengjiaxin

**Comment by Lvnszn** [comment]
可以提供一下复现步骤么 @hgdhfq

**Comment by Lvnszn** [comment]
> 可以提供一下复现步骤么 @hgdhfq

复现了

**Comment by pengjiaxin** [comment]
朋友，您的邮件我已收到，我将以超光速回复您。
