### ISSUE TITLE
received rpc err: Failed to invoke the method

### ISSUE THREAD

**Issue by aprileven** [apache/dubbo-go#1959]
[CallProxy] received rpc err: Failed to invoke the method selectById in the service com.xxxxxx.RpcTaskInfoService. Tried 1 times of the providers [dubbo://:@192.0.0.0:20881/?interface=com.crm.gateway.xxxxx.RpcTaskInfoService&group=&version= dubbo://:@192.0.0.0:20881/?interface=com.crm.gateway.xxxx.RpcTaskInfoService&group=&version=] (2/1)from the registry zookeeper://192.0.0.0:2181?registry=zookeeper&registry.group=&registry.label=true&registry.namespace=&registry.preferred=false&registry.role=0&registry.timeout=10s&registry.ttl=10s&registry.weight=0&registry.zone=&remote-client-name=dubbo.registries-zookeeper-192.0.0.0%3A2181%2C192.0.0.0%3A2181%2C192.0.0.0%3A2181&simplified=false on the consumer 172.0.0.1 using the dubbo version 3.0.0. Last error is request need @response.: request need @response

**What happened**: go 调用 java时出现

**What you expected to happen**: 初始化调用方法时出现

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by AlexStocks** [comment]
@zhaoyunxing92

**Comment by AlexStocks** [comment]
中石化

**Comment by AlexStocks** [comment]
@aprileven pls contact @zhaoyunxing92 whose dingding name is 云兴 in  dingding group.

**Comment by AlexStocks** [comment]
@aprileven ping again. pls contact us to reproduce this bug. If can not get your reply in a while, we will close this issue next month.
