### ISSUE TITLE
shutdown config [internal-signal] value [false] not used

### ISSUE THREAD

**Issue by huangjun0124** [apache/dubbo-go#1974]
**What happened**:
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/4506450/179438158-dcf23370-2971-4796-8852-2c71fb0985a1.png">

**What you expected to happen**:
value should be false
**How to reproduce it (as minimally and precisely as possible)**:
config [shutdown.internal-signal] to false
**Anything else we need to know?**:
nothing

**Comment by AlexStocks** [comment]
@zhaoyunxing92 pls follow this issue and give a solution. thank you.

**Comment by zhaoyunxing92** [comment]
这个问题在跟 defaults https://github.com/creasty/defaults/issues/30#issuecomment-1193363183 沟通

**Comment by AlexStocks** [comment]
> creasty/defaults#30 (comment)

good  news for this issue.
