### ISSUE TITLE
配置模块支持递归查找

### ISSUE THREAD

**Issue by zhaoyunxing92** [apache/dubbo-go#1983]
**What would you like to be added**:
如图希望可以key的值可以递归查找,这样假如nacos的地址发生变化只用修改一处简化配置工作量

![image](https://user-images.githubusercontent.com/18088210/180109443-9bc1f2c7-e13f-4c3f-bbd8-cf968ecd8e13.png)

**Comment by ZLBer** [comment]
@zhaoyunxing92 i  will do this, assign me pls
