### ISSUE TITLE
服务端获取不到客户端传的metadata数据

### ISSUE THREAD

**Issue by rsaLive** [apache/dubbo-go#1984]
问题背景：想用grpc的metadata传送token鉴权数据
测试过程：我用纯grpc测试了 client发送，server接收是可以收到的。
问题描述：同样的代码复制到dubbo-go 框架，server收不到数据。
代码：
client:
![image](https://user-images.githubusercontent.com/14867935/180118429-a93bcef9-aa46-49be-b1fe-7e92c957548d.png)
server:
![image](https://user-images.githubusercontent.com/14867935/180118474-a3206d81-a866-4fe4-adb8-a2b3a9234ab2.png)
![image](https://user-images.githubusercontent.com/14867935/180118710-d186cf29-f31f-473e-8d54-f15d45e120bf.png)

疑问：请问该怎么修改？

**Comment by zhaoyunxing92** [comment]
可以下这个 https://github.com/apache/dubbo-go/issues/1410

**Comment by rsaLive** [comment]
解决了，metadata 在dubbo-go 里面，不支持，要用框架自带的 attachment。

**Comment by rsaLive** [comment]
问题已解决 用 AttachmentKey

**Comment by AlexStocks** [comment]
> 问题已解决 用 AttachmentKey

那跟你上一条回复有冲突啊，AttachmentKey 是dubbogo 的东西。我们支持带上 attachment 的。
