### ISSUE TITLE
请问该怎么学习dubbo-go

### ISSUE THREAD

**Issue by rsaLive** [apache/dubbo-go#1985]
1. 我看了dubbo-go 的文档（https://dubbogo.github.io/zh-cn/docs/user/tasks/rpc/tps_limiter.html），感觉文档内容比较少，想多了解一些，该去哪里看？

2. 比如过滤器filter，官网的示例是 自定义和tps，那其他的token 等过滤器没有提到，这些要到哪里去看，该如何配置？是要翻源码吗？

**Comment by AlexStocks** [comment]
@rsaLive 感谢对项目的关注。可以从 https://github.com/apache/dubbo-go-samples 入手。这个项目有两个分支，master分支是 v3.0 的例子，兼容 dubbo 3.x。1.5 分支是 dubbogo 1.5.x 的代码示例，兼容 dubbo 2.7.

**Comment by rsaLive** [comment]
@AlexStocks   我有看这个samples，我有个疑问，比如过滤器那一栏，文档和demo只有两个，自定义和tps，但我看到源码里面还有 token 等很多过滤器，有哪些过滤器？那些过滤器怎么使用？有哪些配置项，应该从哪里去看？只能看源码吗？

**Comment by AlexStocks** [comment]
> @AlexStocks 我有看这个samples，我有个疑问，比如过滤器那一栏，文档和demo只有两个，自定义和tps，但我看到源码里面还有 token 等很多过滤器，有哪些过滤器？那些过滤器怎么使用？有哪些配置项，应该从哪里去看？只能看源码吗？

提交 issue，我让社区同学提交 samples。

**Comment by rsaLive** [comment]
好的  谢谢
