### ISSUE TITLE
请问如何使用token过滤器

### ISSUE THREAD

**Issue by rsaLive** [apache/dubbo-go#1989]
我想验证用户请求，看到代码里面有tokenfilter ，但是不知道怎么使用，能不能出个client和server的samples，让我学习参考一下？
谢谢！

**Comment by Mulavar** [comment]
已跟进，目前 dubbo-go 的 token filter 机制有一点问题，正在修复，等 dubbo-go 修复完后 samples 就可以跟上。
#1998

**Comment by Mulavar** [comment]
refer to https://github.com/apache/dubbo-go-samples/pull/402

**Comment by Mulavar** [comment]
请问对这块是否还有其他疑问，如果没有的话我们这边关闭issue了哈。

**Comment by rsaLive** [comment]
好的 没有问题了

**Comment by rsaLive** [comment]
不好意思，我看到samples 有token示例代码了就以为好了。我调试了samples ，发现两个问题。
示例代码 server 的配置文件里面配置了 filter token ，客户端那么没有配置，这样请求是没有任何异常可以直接访问？
1、client 不配置token 过滤器可以直接访问？服务器不拦截？
2、我在client filter配置了token，发现不管怎么配置，server都会拦截，我不知道要怎么配置token参数值，（我在samples没看到怎么配置这个token）。
![image](https://user-images.githubusercontent.com/14867935/183380893-0dee8b48-ef38-45e3-9fd4-628b75659e4e.png)
![image](https://user-images.githubusercontent.com/14867935/183381188-f7c3c093-1cfa-4f2f-84ae-a093af05ad1b.png)

**Comment by Mulavar** [comment]
token filter机制是服务端在调用服务前检测客户端传来的token（remote token）和当前自己保存的token是否一致，试想一下，服务端的 remote token 是客户端，那客户端的 remote token 是什么呢？因此客户端不需要配置 token filter。
dubbo 的 token 机制略微特殊，不用客户端显式传递，它的目标是避免用户不经过注册中心直接使用客户端调用服务端，token 是实际存在注册中心上的，因此只需要服务端配置好 token filter，客户端会自动去注册中心拉取对应 token。

**Comment by rsaLive** [comment]
懂了，谢谢解答
