### ISSUE TITLE
polaris的支持dubbo接口级别注册发现，订阅服务变化功能未正常执行

### ISSUE THREAD

**Issue by chuntaojun** [apache/dubbo-go#1994]
**What happened**:

https://github.com/apache/dubbo-go/blob/de6fcfbccd909aa75edb23025687eb6271110cba/registry/polaris/registry.go#L159

在这个方法内，没有注入对应的 PolarisWatcher，实际上这个 Subscribe 动作是没有真正向北极星发起订阅动作的

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by jasondeng1997** [comment]
ok
