### ISSUE TITLE
URL.params concurrent map read and map write problem

### ISSUE THREAD

**Issue by giantpoplar** [apache/dubbo-go#200]
**What happened**:
program crash due to URL.params concurrent map read and map write problem

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

A paramsLock (common/url.go baseUrl struct) is introduced in recent commit to fix concurrent map read and write problem of params. However,  this problem has not been completely solved. In  function "MergeUrl", params are set without this lock guard.

**Comment by hxmhlt** [comment]
TKS. I will commit a bug fix pr.

**Comment by hxmhlt** [comment]
resloved
