### ISSUE TITLE
how to know if a Filter is running in Consumer or Provider?

### ISSUE THREAD

**Issue by huangjun0124** [apache/dubbo-go#2005]
For a common Filter, how to know is it invoked as a Provider by other clients, or it is invoked as a consumer before calling to other service?
For exmaple, below filter is configured both in provider and consumer in dubbo.yaml, how do i know which side i'm on when running?
`myCommonFilter(ctx context.Context, invoker filter.Invoker, invocation filter.Invocation) filter.ServiceResult`

**Comment by justxuewei** [comment]
The filter does not distinguish client and provider, and it only providers its own functionality. For example, if we want to encrypt data at client side, and decrypt data at server side, you should implement two filters, named "EncryptingFilter" and "DecryptFilter" respectively. The "EncryptingFilter" should be deployed on client side, and another should be deployed on server side. Note that neither "EncryptingFilter" nor "DecryptFilter" knows which side they are deployed on.

**Comment by huangjun0124** [comment]
> 

understood
