### ISSUE TITLE
dubbo-go 全局异常拦截器该如何使用

### ISSUE THREAD

**Issue by rsaLive** [apache/dubbo-go#2007]
想使用  defer recover() ，全局捕获异常，请问该怎么写？

defer func() {
	if errP := recover(); errP != nil {
		fmt.Println("errp =================", errP)
	}
}()

**Comment by Mulavar** [comment]
This problem is the go recovery mechanism itself, and it seems to have nothing to do with dubbo-go?
@rsaLive

**Comment by rsaLive** [comment]
ok  thanks
