### ISSUE TITLE
使用配置 API 启动应用，部分方法不存在

### ISSUE THREAD

**Issue by rsaLive** [apache/dubbo-go#2009]
##  问题背景
客户端我是gin结合dubbo-go ，来调用server端，我想写单元测试，所以想使用配置 API 启动应用。
 但是文档的示例，我放到项目里面，部分方法不存在，不知道什么情况
## 问题展现
![image](https://user-images.githubusercontent.com/14867935/183397431-9e6df69c-fba4-4467-8d96-732aaa91d795.png)
## 尝试解决
执行命令  dubbogo-cli install all
但是没有用

**Comment by zhaoyunxing92** [comment]
那个版本可以看下这个代码：[reference_config_test.go#L425-L454](https://github.com/apache/dubbo-go/blob/3.0/config/reference_config_test.go#L425-L454)

**Comment by rsaLive** [comment]
收到，我看下
