### ISSUE TITLE
How to unsubscribe Dubbo Mailing list

### ISSUE THREAD

**Issue by wecloud2008** [apache/dubbo-go#203]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by gaoxinge** [comment]
我还以为你的unsubscribe是指unsubscibe注册中心这个功能呢：）

如果你要取消订阅dubbo的mailing list，可以看一下https://dubbo.apache.org/zh-cn/docs/developers/contributor-guide/mailing-list-subscription-guide_dev.html。
