### ISSUE TITLE
client 重启后，server端也要重启

### ISSUE THREAD

**Issue by rsaLive** [apache/dubbo-go#2033]
发现一个奇怪的问题，我client端重启后，访问server端，会报错   runtime error: invalid memory address or nil pointer dereference
server端也重启后就可以访问，应该是我配置问题，之前不是这样的，但是我反复检查配置，没发现什么特殊配置

**Comment by rsaLive** [comment]
我写了个简单的client（B），有问题的是（A）,prodiver 是同一个，发现B 不管怎么重启就是没事，能调，A就是报上面的错误

**Comment by zhaoyunxing92** [comment]
有代码

**Comment by rsaLive** [comment]
好的，我整理一下

**Comment by rsaLive** [comment]
我尝试整理出来，但是
1 是不方便整体出来，2 是代码关联比较多，有点小复杂，请问我应该怎么去调试，那边能看出来大致的问题？
@AlexStocks 
@zhaoyunxing92

**Comment by rsaLive** [comment]
> 只能说大概率是你使用有啥不当之处了

请问大概率是 是Producer 还是 Consumer有问题？

**Comment by rsaLive** [comment]
> > > 只能说大概率是你使用有啥不当之处了
> > 
> > 
> > 请问大概率是 是Producer 还是 Consumer有问题？
> 
> 这个没法猜啊。你要不在钉钉群里找我【于雨】，咱们周末约个时间，远程给你看下？

好的，我再尝试找找问题，不行再麻烦大佬你

**Comment by rsaLive** [comment]
找到了问题，我使用了自定义filter，注释掉 consumer，dubbogo.yaml 里面的filter 就可以了。
以防自己哪里写错了，我把dubbogo-sample里面的 myClientFilter复制到 comsumer 端，myServerFilter复制到 producer端，还是一样的问题，复现步骤：producer启动之后，comsumer 启动，调用接口没问题，当comsumer 重启一次之后，再次调用接口，comsumer 就提示 runtime error: invalid memory address or nil pointer dereference，看日志都没到producer那端
