### ISSUE TITLE
Bug: protocol/dubbo/client.go代码判断空错误

### ISSUE THREAD

**Issue by joeyzhouy** [apache/dubbo-go#204]
branch：master
line：62
判断变量dubboConf【配置文件中dubbo的配置】是否为空，但62行，重复判断了protocolConf是否为空

**Comment by AlexStocks** [comment]
@joeyzhouy maybe u can submit a pr to develop?

**Comment by joeyzhouy** [comment]
OK

**Comment by joeyzhouy** [comment]
@AlexStocks protocol/dubbo/server.go init() 也存在类似的问题
