### ISSUE TITLE
README 指向文档的链接不是最新的 

### ISSUE THREAD

**Issue by stulzq** [apache/dubbo-go#2063]
<img width="864" alt="image" src="https://user-images.githubusercontent.com/13200155/192420263-04316558-28c5-416d-a9bc-4cefac721e8d.png">

<img width="824" alt="image" src="https://user-images.githubusercontent.com/13200155/192420340-a0f435c9-213d-4f5d-9de1-91f1191bba5a.png">

**Comment by justxuewei** [comment]
Thank you for reporting this issue, we'll fix it asap.
