### ISSUE TITLE
client不支持ms级别的timeout

### ISSUE THREAD

**Issue by aeternae** [apache/dubbo-go#2086]
opts := []triConfig.OptionFunction{
		triConfig.WithClientTimeout(uint32(timeout.Seconds())),
		triConfig.WithCodecType(triCodecType),
		triConfig.WithLocation(url.Location),
		triConfig.WithHeaderAppVersion(url.GetParam(constant.AppVersionKey, "")),
		triConfig.WithHeaderGroup(url.GetParam(constant.GroupKey, "")),
		triConfig.WithLogger(logger.GetLogger()),
	}
ms级别的timeout会被转化成秒级后，被uint32类型转化成0值

func (o *Option) Validate() {
	if o.Timeout == uint32(0) {
		o.Timeout = uint32(constant.DefaultTimeout)
	}
       ...
}
0值被修改成默认的15s

**What would you like to be added**:

**Why is this needed**:

**Comment by zhaoyunxing92** [comment]
我建议修改`WithClientTimeout`的参数类型会比较合理点
