### ISSUE TITLE
Ftr:registry interface should define function "unregister"

### ISSUE THREAD

**Issue by hxmhlt** [apache/dubbo-go#21]
java registry unregister部分的源码，unregister这个的用途是：
1.provider在启动时也会启动registry的监听，当发现registry上注册的service内容跟本地刚启动时注册的service不一致时，就会刷新registry。
2.qos，允许运维人员对服务进行动态上下限。http://dubbo.apache.org/zh-cn/blog/introduction-to-dubbo-qos.html

1和2需求，暂时非紧急需求，先记个issue后面再完善。

**Comment by AlexStocks** [comment]
sounds good.

**Comment by zouyx** [comment]
done
