### ISSUE TITLE
[BUG] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mark4z** [apache/dubbo-go#2126]
**What happened**:
Just see https://github.com/mark4z/dubbo-go-npe/tree/master

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by zhaoyunxing92** [comment]
有完整的堆栈信息吗

**Comment by LaurenceLiZhixin** [comment]
@mark4z 
Do not use `go run server.go` . Use `go run .` instead, to make sure go files under main pkg are included during compiling.

**Comment by mark4z** [comment]
tks
