### ISSUE TITLE
如何在client过滤器中获取http header

### ISSUE THREAD

**Issue by rsaLive** [apache/dubbo-go#2158]
客户端是gin加dubbo-go ，现在想把http请求的header传到生产者那边，为了不要每个请求都写传入上下文代码，就放到了filter中，filter中去设置上下文，但是filter中不知道怎么去获取header参数，我断点看到了传递的body参数，但是没看到header

**Comment by rsaLive** [comment]
> header 放在 attachment 是可以传到 server 端的。

我知道放在attachment可以传，但是在过client的 滤器里面不知道怎么获取。

**Comment by binbin0325** [comment]
在dubbo 的client中肯定没有办法获取header，因为dubbo就没有这个概念。  但是可以在gin中获取header，然后把header的k、v转换成dubbo的attachment。这样就能发送到server端了。  

如何设置attachment可以参考：https://github.com/apache/dubbo-go-samples/blob/master/context/dubbo/go-client/cmd/client.go#L64
