### ISSUE TITLE
 No provider available of the service xxx

### ISSUE THREAD

**Issue by bobtthp** [apache/dubbo-go#2162]
**What happened**:

dubbogo version：v3.0.4-rc1
注册中心： nacos
协议： triple
注册类型： service

应用级服务发现有两个 provider 实现相同接口，consumer 启动时会一定几率启动失败（ No provider available of the service xxx）

2022-12-15T13:49:06.410+0800    ERROR   config/consumer_config.go:158   No provider available of the service com.apache.dubbo.sample.basic.IGreeter.please check configuration.
dubbo.apache.org/dubbo-go/v3/config.(*ConsumerConfig).Load
        /Users/bobtthp/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.4-rc1/config/consumer_config.go:158
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Start.func1
        /Users/bobtthp/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.4-rc1/config/root_config.go:205
sync.(*Once).doSlow
        /usr/local/go/src/sync/once.go:68
sync.(*Once).Do
        /usr/local/go/src/sync/once.go:59
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Start
        /Users/bobtthp/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.4-rc1/config/root_config.go:203
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Init
        /Users/bobtthp/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.4-rc1/config/root_config.go:198
main.main
        /Users/bobtthp/Desktop/bob/dev/test/dubbo-go-test/consumer-app/cmd/client.go:94
runtime.main
        /usr/local/go/src/runtime/proc.go:255
panic: No provider available of the service com.apache.dubbo.sample.basic.IGreeter.please check configuration.

![image](https://user-images.githubusercontent.com/23113152/207783958-1a0dadaa-4351-4fa0-a91d-57aab63157bd.png)

**Comment by justxuewei** [comment]
Please try the latest version of the Dubbo-go, which contains [this pull request](https://github.com/apache/dubbo-go/pull/2139). Or please sleep 3 seconds after the Dubbo-go launched.

**Comment by bobtthp** [comment]
https://github.com/apache/dubbo-go/pull/2139/files
