### ISSUE TITLE
服务端返回isXxxx字段的问题

### ISSUE THREAD

**Issue by LvBay** [apache/dubbo-go#2165]
场景：服务端是java实现的dubbo服务；调用方是dubbo-go泛化调用。服务端返回的结构体是{"isSuccess":true}，但是dubbo-go收到的却是{"success":true}

请问如何接收到原始的isSuccess字段呢

**Comment by CodingAdai** [comment]
> 场景：服务端是java实现的dubbo服务；调用方是dubbo-go泛化调用。服务端返回的结构体是{"isSuccess":true}，但是dubbo-go收到的却是{"success":true}
> 
> 请问如何接收到原始的isSuccess字段呢

@LvBay   
这个跟Dubbo实现泛型调用机制有关，SDK中的GenericFilter会拦截调用来实现泛型调用，在返回结果时会装换成map结构并序列化，其中map的字段名通过反射获取getter来获取（getXXX/isXXX 取XXX首字母小写）。
 
可以检查下Java提供者服务的接口返回值 中的 isSuccess 的getter方法名，如果为isSuccess()，则修改为getIsSuccess()，Go client中可以获取到isSuccess字段名。

注：[GenericFilter.java中转换并返回结果的具体代码](https://github.com/apache/dubbo/blob/cc6e1aea8949206be571ccc8d7719702679a4c72/dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java#L269)

**Comment by LvBay** [comment]
@CodingAdai 
你好，线上有一批接口都是isSuccess()命名的，通知业务方改造成本有些大。是否可以通过修改dubbo-go的consumer侧代码，兼容掉这个问题

**Comment by CodingAdai** [comment]
> @CodingAdai 你好，线上有一批接口都是isSuccess()命名的，通知业务方改造成本有些大。是否可以通过修改dubbo-go的consumer侧代码，兼容掉这个问题

@LvBay  需要兼容的话，可以在加一个getIsSuccess()的getter方法，这样可以返回success和isSuccess两个字段。

**Comment by LvBay** [comment]
> > @CodingAdai 你好，线上有一批接口都是isSuccess()命名的，通知业务方改造成本有些大。是否可以通过修改dubbo-go的consumer侧代码，兼容掉这个问题
> 
> @LvBay 需要兼容的话，可以再加一个getIsSuccess()的getter方法，这样可以返回success和isSuccess两个字段。

在java provider侧添加getIsSuccess代码确实可以兼容这个问题👍
还有个疑问，是否可以通过修改dubbo-go的consumer侧代码来兼容呢？

**Comment by CodingAdai** [comment]
让consumer 端来做兼容的话，我个人认为不太合理。如果确实要这样做的话，可以考虑扩展filter来拦截实现。

**Comment by LvBay** [comment]
明白了，谢谢 @CodingAdai
