### ISSUE TITLE
the msg size of provider is invalid

### ISSUE THREAD

**Issue by rsaLive** [apache/dubbo-go#2176]
## 问题
grpc: received message larger than max (7292359 vs. 4194304)，提示传送的数据超过大小限制
#1644 
参考这个issue，进行配置，但是并没有用
![image](https://user-images.githubusercontent.com/14867935/210711430-6ab34410-f17d-4055-9e66-b97b41479a53.png)

**Comment by mark4z** [comment]
@rsaLive 请问对应的dubbo-go版本是什么

**Comment by mark4z** [comment]
provider和consumer必须都做对应配置，参考以下配置：

Provider:

dubbo:
  provider:
    services:
      # you may refer to `Reference()` method defined in `protobuf/triple/helloworld.pb.go`
      GreeterProvider:
        # interface read from pb file, after generated from protoc-gen-go-triple v1.0.5 later
        interface: ""
        params:
          max-server-send-msg-size: 6000000
          max-server-recv-msg-size: 6000000
Consumer:

  consumer:
    references:
      GreeterClientImpl:
        protocol: tri
        params:
          max-call-send-msg-size: 6000000
          max-call-recv-msg-size: 6000000

**Comment by rsaLive** [comment]
版本是：v3.0.2
@mark4z 
我发现triple那边生效了，但是dubbo-grpc-go 那边又拦截了，实在没办法我改用上下文传这个值了

**Comment by mark4z** [comment]
> 
已经确认这是一个问题，稍后我们会安排版本修复。
