### ISSUE TITLE
registry.Subscribe 不支持模糊匹配

### ISSUE THREAD

**Issue by wudong5** [apache/dubbo-go#2236]
希望能支持 registry.Subscribe 接口对 InterfaceKey、GroupKey、VersionKey 的模糊匹配机制

**Comment by wudong5** [comment]
> dubbo-go 3.0 目前支持类似于 ‘*’ 这种模糊匹配机制，不知道是否满足你的需求。如果不满足，请更进一步描述你的问题。

抱歉，我目前使用过程中发现没有生效，不知道是不是用错了。
使用的是 dubbo.apache.org/dubbo-go/v3/registry 的 Subscribe 方法。包括 InterfaceKey 在内的相关参数使用的都是 "*"。

**Comment by chickenlj** [comment]
`/dubbo/*`

`/dubbo/` 变化都监听 -> `/dubbo/{interface}/providers`监听

**Comment by chickenlj** [comment]
admin订阅url格式：`consumer://ip:port/*?version=*&group=*`
