### ISSUE TITLE
请问如何让go-server同时支持java-client和go-client的调用

### ISSUE THREAD

**Issue by tiantianlikeu** [apache/dubbo-go#2253]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/35363659/224748336-48f37eca-006f-4afa-8560-4dbf49b9f407.png)

**Why is this needed**:

**Comment by tiantianlikeu** [comment]
![image](https://user-images.githubusercontent.com/35363659/224748452-f45026b2-def3-4eac-a1b6-13b841c398fe.png)
这是我api的截图

**Comment by justxuewei** [comment]
See [here](https://cn.dubbo.apache.org/zh-cn/overview/mannual/golang-sdk/tutorial/develop/interflow/call_java/)

```go
// UserProvider 客户端存根类
type UserProvider struct {
  // dubbo标签，用于适配go侧客户端大写方法名 -> java侧小写方法名，只有 dubbo 协议客户端才需要使用
	GetUser  func(ctx context.Context, req int32) (*User, error) `dubbo:"getUser"` 
}
```

**Comment by tiantianlikeu** [comment]
tks，it working .
