### ISSUE TITLE
can dubbo config file use redirect path either use export

### ISSUE THREAD

**Issue by Zeb-D** [apache/dubbo-go#226]
now dubbo-go use consumer config and son by export, that produced other devOps things，for example docker or k8s or apollo config center.

I hope dubbo-go can provided  the way that more convenient and fast, either given the bound that used export or restrict integrated go and dubbo some features！

some advise： 
1.CommandLine.Parse(os.Args[1:])
2.provided function Set config file path

**Comment by joeyzhouy** [comment]
can you  join the Dingding Group  (No. 23331795)?
Talk about your idea in detail.

**Comment by hxmhlt** [comment]
The third-party config center configuration is supported now . You can refer the example as https://github.com/dubbogo/dubbogo-samples.  Also you can add my weixin number: 'hxmhlt'  if you have some problem.  :)
