### ISSUE TITLE
Implement condition routing

### ISSUE THREAD

**Issue by FinalT** [apache/dubbo-go#2284]
实现dubbo-go流量管控中的条件路由，对路由集的匹配过滤能力与官网描述一致

对于匹配/过滤条件，具备参数支持，条件支持，值支持，并且对通用逻辑做了抽象，只需实现对应的接口(pattern_value.ValuePattern)或者继承相关的父类(matcher.BaseConditionMatcher)，再利用dubbo-go中的extension机制，能够实现自定义扩展

**Comment by FinalT** [comment]
https://github.com/apache/dubbo-go/pull/2276

**Comment by FinalT** [comment]
#2276

**Comment by justxuewei** [comment]
This is a new feature of the Dubbo-go. Please give an example and add it into [dubbo-go-samples](github.com/apache/dubbo-go-samples).

Ref: https://cn.dubbo.apache.org/zh-cn/overview/core-features/traffic/condition-rule/

**Comment by FinalT** [comment]
https://github.com/apache/dubbo-go-samples/pull/551

**Comment by justxuewei** [comment]
> [apache/dubbo-go-samples#551](https://github.com/apache/dubbo-go-samples/pull/551)

Ok, I'll take a look. It is a very huge pitch, so it might take longer.

**Comment by chickenlj** [comment]
Please notice that this is part of the effort to provide complete traffic management support instructed by the Dubbo official website.

https://cn.dubbo.apache.org/zh-cn/overview/core-features/traffic/

**Comment by FinalT** [comment]
#2299
