### ISSUE TITLE
Updating code of conduct

### ISSUE THREAD

**Issue by justxuewei** [apache/dubbo-go#2288]
There are more and more people coming to the community and contributing code. We need to have a strict code of conduct to maintain efficient collaboration.

## Contributing

The format of the title of PRs should be:

```
<type>: One line summary of the PR
```

The types are including(https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/):

- feat – a new feature is introduced with the changes
- fix – a bug fix has occurred
- chore – changes that do not relate to a fix or feature and don't modify src or test files (for example updating dependencies)
- refactor – refactored code that neither fixes a bug nor adds a feature
- docs – updates to documentation such as a the README or other markdown files
- style – changes that do not affect the meaning of the code, likely related to code formatting such as white-space, missing semi-- - colons, and so on.
- test – including new or correcting previous tests
- perf – performance improvements
- ci – continuous integration related
- build – changes that affect the build system or external dependencies
- revert – reverts a previous commit

If this PR is to backport to other branchs, e.g. `3.0`, then the title would be:

```
[3.0] <type>: One line summary of the PR
```

Each pull request *MUST* have a corresponding issue to explain what does this PR do. The format of message should be:

```
(A brief description about this PR.) Lorem ipsum dolor sit amet, consectetur
adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
ut aliquip ex ea commodo consequat.

Fixes: #1000

Signed-off-by: Example <example@example.com>
```

The signed-off message will be appended automaticaly if the developers commit with `-s` option, for example, `git commit -s`.

Besides, the workflows (GitHub actions) will be updated to check if PRs follow the rules.

## Issue Template

If bug reporters do not give enough information about their environment, it is too hard to debug and find which part is not working properly. Therefore, we need to update our issue template to guide users to provide more information. It should be:

### Environment

- Server: Dubbo-go, v3.0.5
- Client: Dubbo-go, v3.0.5
- Protocol: Triple
- Registry: Nacos, v2.0.0

### Issue description

(Here is a brief description about the issue.) Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

### Logs

<details><summary>Click me to check logs</summary>

```
2023-03-31T09:10:44.039+0800 ERROR proxy_factory/default.go:111 cannot find method [getSubscribedURLs] of service [org.apache.dubbo.metadata.MetadataService] in dubbo
dubbo.apache.org/dubbo-go/v3/proxy/proxy_factory.(*ProxyInvoker).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/proxy/proxy_factory/default.go:111
dubbo.apache.org/dubbo-go/v3/filter/graceful_shutdown.(*providerGracefulShutdownFilter).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/filter/graceful_shutdown/provider_filter.go:80
dubbo.apache.org/dubbo-go/v3/protocol/protocolwrapper.(*FilterInvoker).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/protocol/protocolwrapper/protocol_filter_wrapper.go:127
dubbo.apache.org/dubbo-go/v3/filter/exec_limit.(*executeLimitFilter).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/filter/exec_limit/filter.go:119
dubbo.apache.org/dubbo-go/v3/protocol/protocolwrapper.(*FilterInvoker).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/protocol/protocolwrapper/protocol_filter_wrapper.go:127
dubbo.apache.org/dubbo-go/v3/filter/generic.(*genericServiceFilter).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/filter/generic/service_filter.go:64
dubbo.apache.org/dubbo-go/v3/protocol/protocolwrapper.(*FilterInvoker).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/protocol/protocolwrapper/protocol_filter_wrapper.go:127
dubbo.apache.org/dubbo-go/v3/filter/tps.(*tpsLimitFilter).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/filter/tps/filter.go:95
dubbo.apache.org/dubbo-go/v3/protocol/protocolwrapper.(*FilterInvoker).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/protocol/protocolwrapper/protocol_filter_wrapper.go:127
dubbo.apache.org/dubbo-go/v3/filter/accesslog.(*Filter).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/filter/accesslog/filter.go:113
dubbo.apache.org/dubbo-go/v3/protocol/protocolwrapper.(*FilterInvoker).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/protocol/protocolwrapper/protocol_filter_wrapper.go:127
dubbo.apache.org/dubbo-go/v3/filter/token.(*tokenFilter).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/filter/token/filter.go:94
dubbo.apache.org/dubbo-go/v3/protocol/protocolwrapper.(*FilterInvoker).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/protocol/protocolwrapper/protocol_filter_wrapper.go:127
dubbo.apache.org/dubbo-go/v3/filter/metrics.(*Filter).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/filter/metrics/filter.go:50
dubbo.apache.org/dubbo-go/v3/protocol/protocolwrapper.(*FilterInvoker).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/protocol/protocolwrapper/protocol_filter_wrapper.go:127
dubbo.apache.org/dubbo-go/v3/filter/echo.(*echoFilter).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/filter/echo/filter.go:64
dubbo.apache.org/dubbo-go/v3/protocol/protocolwrapper.(*FilterInvoker).Invoke
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/protocol/protocolwrapper/protocol_filter_wrapper.go:127
dubbo.apache.org/dubbo-go/v3/protocol/dubbo.doHandleRequest
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/protocol/dubbo/dubbo_protocol.go:161
dubbo.apache.org/dubbo-go/v3/protocol/dubbo.(*DubboProtocol).openServer.func1
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/protocol/dubbo/dubbo_protocol.go:128
dubbo.apache.org/dubbo-go/v3/remoting/getty.(*RpcServerHandler).OnMessage
E:/dev-work/gorun/GOPATH/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.5/remoting/getty/listener.go:275
github.com/apache/dubbo-getty.(*session).addTask.func1
E:/dev-work/gorun/GOPATH/pkg/mod/github.com/apache/[dubbo-getty@v1.4.9-0.20221022181821-4dc6252ce98c](mailto:dubbo-getty@v1.4.9-0.20221022181821-4dc6252ce98c)/session.go:565
github.com/dubbogo/gost/sync.(*taskPoolSimple).worker
E:/dev-work/gorun/GOPATH/pkg/mod/github.com/dubbogo/gost@v1.13.2/sync/task_pool.go:303
```

</details>

**Comment by justxuewei** [comment]
@zhaoyunxing92 @AlexStocks @chickenlj What do you think about this?

**Comment by chickenlj** [comment]
I think it's a good practice to provide templates as a guide for contributors.

It's always good to see an issue or pull request that is clearly stated its purpose, the scope of changes, etc. But I think we should also notice that it could be more practical for us to apply an agile policy at present to allow quick iteration, especially for the development branch, so it should not be seen a mandatory request.
