### ISSUE TITLE
本地debug调试 github.com/apache/dubbo-go v1.5.8 出现  No provider available for the service dubbo://:@:/?interface=&group=&version=

### ISSUE THREAD

**Issue by drama10096** [apache/dubbo-go#2309]
1、dubbo-go的tag：v1.5.8 ；
2、问题产生的背景：利用dubbo-go调用本地“idea软件启动的dubbo服务”，并执行debug调试，超过3秒时间以后，就会出现“dubbo://:@:/?interface=”问题；
3、个人看底层分析是：dubbo-go/cluter/cluter_impl.failoverClusterInvoker 故障转移的原因；
4、只要出现一次“dubbo://:@:/?interface=”，后面再次调用全都是这样的错误结果；
5、重启consumer golang应用后，问题依然没解决（感觉有本地缓存），再次出现；
6、全堆栈error信息为："Failed to invoke the method $invoke. No provider available for the service dubbo://:@:/?interface=&group=&version= from registry zookeeper://10.202.244.23:32181?group=&registry=zookeeper&registry.label=true&registry.preferred=false&registry.role=0&registry.timeout=3s&registry.ttl=&registry.weight=0&registry.zone=&simplified=false on the consumer 10.202.162.95 using the dubbo version 1.5.8 .Please check if the providers have been started and registered.","errorVerbose":"Failed to invoke the method $invoke. No provider available for the service dubbo://:@:/?interface=&group=&version= from registry zookeeper://10.202.244.23:32181?group=&registry=zookeeper&registry.label=true&registry.preferred=false&registry.role=0&registry.timeout=3s&registry.ttl=&registry.weight=0&registry.zone=&simplified=false on the consumer 10.202.162.95 using the dubbo version 1.5.8 .Please check if the providers have been started and registered.\ngithub.com/apache/dubbo-go/cluster/cluster_impl.(*baseClusterInvoker).checkInvokers

**Comment by drama10096** [comment]
切换升级dubbo-go的tag到v1.5.9，也是一样（所访问的dubbo服务应用在“开发环境的k8s”里是正常的）

**Comment by zhaoyunxing92** [comment]
换 3.x 版本可以么

**Comment by justxuewei** [comment]
We are not maintaining v1.5.x anymore, please upgrade to our the latest version.
