### ISSUE TITLE
Print logs of registered providers and consumers 

### ISSUE THREAD

**Issue by justxuewei** [apache/dubbo-go#2319]
Print logs of registered providers and consumers for earier debugging, e.g.

For provider

```
Registered provider services are "Service1", "Service2", "Service3".
```

For consumer

```
Registered consumer clients are "Service1", "Service2", "Service3".
```

**Comment by ev1lQuark** [comment]
> Please take a look, @ev1lQuark. Thanks!

ok, I will submit a PR later
