### ISSUE TITLE
MetricConfig 无法设置 Enable 为 false

### ISSUE THREAD

**Issue by jiangy** [apache/dubbo-go#2335]
### Environment

- Server: Dubbo-go, v3.0.5
- Client: 
- Protocol: 
- Registry: 

### Issue description
这个 Enable 的默认值处理有问题，如果设置为 false 的话会当作 0 值被 defaults 设置为默认值 true，也就是说用户永远无法设置 false

![image](https://github.com/apache/dubbo-go/assets/2594973/f078c9aa-e863-46f7-a950-e8804f0c8e28)

### Logs

<details><summary>Click me to check logs</summary>

```
Copy logs to here.
```

</details>

**Comment by ev1lQuark** [comment]
Thank you, this is the [PR](https://github.com/apache/dubbo-go/pull/2310/files#diff-b302e39f38f857c8e3d9d38c2b7329c70ab2408d249f82987790af3dfd9cfd35) that fixes the bug. But it hasn't been released yet.

**Comment by ev1lQuark** [comment]
This [PR](https://github.com/apache/dubbo-go/pull/2336) resolve the bug.

**Comment by justxuewei** [comment]
@ev1lQuark Please backport the bugfixes to the main branch.
