### ISSUE TITLE
dubbo-go的配置文件 可以指定加载路径吗？

### ISSUE THREAD

**Issue by zoleo9527** [apache/dubbo-go#2345]
dubbo-go的配置文件 可以指定加载路径吗？好像默认是绝对路径，想改成相对路径

**Comment by zhaoyunxing92** [comment]
有两种方式

- env 里面读取 [DUBBO_GO_CONFIG_PATH](https://github.com/apache/dubbo-go/blob/main/config/config_loader_options.go#L51-L54)
- 手动指定配置文件：[WithPath](https://github.com/apache/dubbo-go/blob/main/config/provider_config_test.go#L33)
