### ISSUE TITLE
/registry/protocol/protocol.go:83 getRegistry获取zk对象错误问题

### ISSUE THREAD

**Issue by TXYan** [apache/dubbo-go#2348]
### Environment

- Client: Dubbo-go, v3.0.5
- Protocol: dubbo
- Registry: zookeeper

### Issue description

yaml中配置了两个注册中心：R1，R2，都是zk，地址一样，只是group不一样。配置了两个消费接口S1，S2，S1注册中心配置R1，S2注册中心配置R2，程序中S1，S2都有调用，发现其中一个会找不到提供者，通过跟代码发现获取注册对象是根据registryUrl.PrimitiveURL进行唯一识别获取，但此URL中没有group因素，导致R1，R2获取的是同一个对象，就看哪个先加载了，在查找提供者拼接路径时会使用registry的group属性，所以导致随机找不到其中一个提供者

### Logs

<details><summary>Click me to check logs</summary>

```
Copy logs to here.
```

</details>

**Comment by justxuewei** [comment]
Thank you for reporting this issue. We will take a look at this.

**Comment by TXYan** [comment]
顺便问下，有没有类似RpcContext的对象，我想拿到本次调用的远程ip

**Comment by justxuewei** [comment]
Assign to @wudong5
