### ISSUE TITLE
dubbo service group功能不可用

### ISSUE THREAD

**Issue by apollo-go** [apache/dubbo-go#238]
Finished List:
Other feature: generic invoke/start check/connecting certain provider/multi-protocols/multi-registries/multi-versions/service group

protocol/dubbo/client.go并未支持group的处理
p := &DubboPackage{}
p.Service.Path = strings.TrimPrefix(svcUrl.Path, "/")
p.Service.Interface = svcUrl.GetParam(constant.INTERFACE_KEY, "")
p.Service.Version = svcUrl.GetParam(constant.VERSION_KEY, "")
p.Service.Method = method
p.Service.Timeout = opts.RequestTimeout

**Comment by apollo-go** [comment]
fix to master

**Comment by AlexStocks** [comment]
@apollo-go u should issue a new pr to develop branch. thank you.
