### ISSUE TITLE
[zookeeper][service_discovery] rootPath support customize，not just "/services"

### ISSUE THREAD

**Issue by xiaomiusa87** [apache/dubbo-go#2428]
**What would you like to be added**:
Use zookeeper as registryCenter，expected customize 'rootPath'，not just "/services"

**Why is this needed**:
We use 'rootPath' to manage multiple clusters， want to call Java through dubbo-go

**Comment by FoghostCn** [comment]
why not use different application name or group name to manage multiple clusters

**Comment by xiaomiusa87** [comment]
> why not use different application name or group name to manage multiple clusters

application name or group name is business attributes，has already been used. 
we are middleware developer ，plan multiple clusters by business type.  may use multi zk or one zk，so need use different 
 rootPath
