### ISSUE TITLE
加入opentelemetry后，启动异常

### ISSUE THREAD

**Issue by WPZC** [apache/dubbo-go#2434]
### Environment

- Server: Dubbo-go, v3.1.0
- Client: Dubbo-go, v3.1.0
- Protocol: gRPC
- Registry: Nacos, v2.1.0

### Issue description

引入opentelemetry出现问题
`panic: proto: file "grpc/health/v1/health.proto" has a name conflict over grpc.health.v1.HealthCheckResponse
        previously from: "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3/health/triple_health_v1"
        currently from:  "google.golang.org/grpc/health/grpc_health_v1"`

### Logs

<details><summary>Click me to check logs</summary>

```
Copy logs to here.
```

</details>

**Comment by FoghostCn** [comment]
maybe related to  #2394 ,you can take a look
