### ISSUE TITLE
Fix 'golangci-lint run' error report of feature-triple

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo-go#2443]
![image](https://github.com/apache/dubbo-go/assets/18097545/1ca5e314-7ddb-4b48-8a89-48a12e4ad18c)

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo-go/actions/runs/6482536491/job/17602249331

**Comment by chickenlj** [comment]
Run `make lint` to try to reproduce the above issues.

**Comment by DMwangnima** [comment]
@FinalT These are some parts related to protoc-gen-triple. We should take a look together.

**Comment by FinalT** [comment]
This issue has been fixed in #2456
