### ISSUE TITLE
Ftr: Graceful exit

### ISSUE THREAD

**Issue by flycash** [apache/dubbo-go#249]
The propal:
After dubbo receives the shutdown signal, it will try to do those things:

1. Unregister the services from all registries, and then close the connection between registries and provider;

2. Notify the client that the services will be shutdown. The client should remove the provider from its cache;

3. Provider waits short time. In this phase, the provider keep receiving request. The keypoint is that there is a time window between unrigstering services and the client received the notification. So the provider may receives some requests after it unregister from registries. The user could make the desicion that how long waiting for or ignored this phase.

4. Provider rejects new requests and waits for processing request. If all requests had been processed or the waiting time reach the limitation, go next step;

5. Invoking all the shutdown callbacks. User can register their custom callback by implementing some interfaces.

**What would you like to be added**:

**Why is this needed**:

**Comment by hxmhlt** [comment]
Good job and LGTM.

**Comment by hxmhlt** [comment]
http://dubbo.apache.org/zh-cn/docs/user/demos/graceful-shutdown.html
We can learn from what the Java version has done, of course I know you've already read it :)
