### ISSUE TITLE
metadata service tri protocol support 

### ISSUE THREAD

**Issue by FoghostCn** [apache/dubbo-go#2540]
**What would you like to be added**:

metadata service support tri protocol, include server and client

include version ~~3.1~~ and 3.2 related to #2539 

java tri wrapper mode will not support

**Why is this needed**:

Compatible with dubbo-java

related to https://github.com/apache/dubbo-go/issues/2403

dependent on [内置服务发布流程\#2539](https://github.com/apache/dubbo-go/issues/2539)

**Comment by FoghostCn** [comment]
assign to me

**Comment by chickenlj** [comment]
I think we can define a unified `metadata_service.proto` MetadataService, so it can be used to support MetadataService running on triple protocol within dubbo-go, while at the same time being used for MetadataService in dubbo-java. 

The work for dubbo-java is in progress here https://github.com/apache/dubbo/issues/13584

**Comment by FoghostCn** [comment]
ref https://github.com/apache/dubbo-go/pull/2723
