### ISSUE TITLE
go客户端设置了接口超时时间，在java 服务端无法获取到正确的值

### ISSUE THREAD

**Issue by Jafeyyu** [apache/dubbo-go#2546]
### Environment

- Server: dubbo java 3.2.9
- Client:  dubbo go 3.1.0
- Protocol:  dubbo
- Registry:  nacos

### Issue description
go cliend调用java server的dubbo server，可以成功调用，但是go client接收到的时超时响应，设置了超时时间也无效，经调试，发现go client发送请求时，invocation的attachment里是设置了超时时间的，如下图
![1](https://github.com/apache/dubbo-go/assets/13826823/65f7d09a-9717-41ee-ab5b-41ceb847a3d6)
但是java server端的org.apache.dubbo.rpc.filter.ProfilerServerFilter类中的dumpIfNeed方法中，从invocation的attachement获取timeout的值是0，如下图
![2](https://github.com/apache/dubbo-go/assets/13826823/f3046df6-59fc-41bb-8c3f-64262e2f1aa4)

### Logs

<details><summary>Click me to check logs</summary>

```
#服务端日志
2023-12-26T10:16:44.780[0;39m [2m[DubboServerHandler-10.6.8.106:20880-thread-56][0;39m [35m16100[0;39m [33m WARN[0;39m [36mo.a.d.r.filter.ProfilerServerFilter[0;39m [2m:[0;39m  [DUBBO] [Dubbo-Provider] execute service com.netpro.dubbo.dems.baseconfig.AlarmDubboService#add cost 160.479300 ms, this invocation almost (maybe already) timeout. Timeout: 0ms
client: 10.6.8.106:1947
invocation context:
path=com.netpro.dubbo.dems.baseconfig.AlarmDubboService;
async=false;
input=764;
environment=dev;
dubbo=2.0.2;
interface=com.netpro.dubbo.dems.baseconfig.AlarmDubboService;
version=;
timeout=0;
thread info: 
Start time: 1041345319061500
+-[ Offset: 0.000000ms; Usage: 160.479300ms, 100% ] Receive request. Server invoke begin.
  +-[ Offset: 0.248700ms; Usage: 160.072500ms, 99% ] Receive request. Server biz impl invoke begin., dubbo version: 3.2.9, current host: 10.6.8.106, error code: 3-7. This may be caused by , go to https://dubbo.apache.org/faq/3/7 to find instructions. 



#go客户端日志：
2023-12-26 10:46:06	WARN	proxy/proxy.go:212	[CallProxy] received rpc err: Failed to invoke the method add in the service com.netpro.dubbo.dems.baseconfig.AlarmDubboService. Tried 1 times of the providers [dubbo://:@10.6.8.106:20880/?interface=com.netpro.dubbo.dems.baseconfig.AlarmDubboService&group=&version= dubbo://:@10.6.8.106:20880/?interface=com.netpro.dubbo.dems.baseconfig.AlarmDubboService&group=&version=] (2/1)from the registry service-discovery-registry://10.5.0.15:8848?registry=nacos&registry.group=&registry.label=true&registry.namespace=dubboboot3&registry.preferred=false&registry.role=0&registry.timeout=5s&registry.ttl=15m&registry.weight=0&registry.zone=&remote-client-name=dubbo.registries-nacos-10.5.0.15%3A8848%2C10.5.0.16%3A8848%2C10.5.0.17%3A8848&simplified=false on the consumer 10.6.0.6 using the dubbo version 3.0.4. Last error is maybe the client read timeout or fail to decode tcp stream in Writer.Write.: maybe the client read timeout or fail to decode tcp stream in Writer.Write

```

</details>

**Comment by Jafeyyu** [comment]
进一步调试发现，在hessian.go中的marshalRequest方法中，对时间做了处理
```go
func marshalRequest(encoder *hessian.Encoder, p DubboPackage) ([]byte, error) {
	service := p.Service
	request := EnsureRequestPayload(p.Body)
	_ = encoder.Encode(DEFAULT_DUBBO_PROTOCOL_VERSION)
	_ = encoder.Encode(service.Path)
	_ = encoder.Encode(service.Version)
	_ = encoder.Encode(service.Method)

	args, ok := request.Params.([]interface{})

	if !ok {
		logger.Infof("request args are: %+v", request.Params)
		return nil, perrors.Errorf("@params is not of type: []interface{}")
	}
	types, err := GetArgsTypeList(args)
	if err != nil {
		return nil, perrors.Wrapf(err, " PackRequest(args:%+v)", args)
	}
	_ = encoder.Encode(types)
	for _, v := range args {
		_ = encoder.Encode(v)
	}

	request.Attachments[PATH_KEY] = service.Path
	request.Attachments[VERSION_KEY] = service.Version
	if len(service.Group) > 0 {
		request.Attachments[GROUP_KEY] = service.Group
	}
	if len(service.Interface) > 0 {
		request.Attachments[INTERFACE_KEY] = service.Interface
	}
	if service.Timeout != 0 {
		request.Attachments[TIMEOUT_KEY] = strconv.Itoa(int(service.Timeout / time.Millisecond))
	}

	err = encoder.Encode(request.Attachments)
	return encoder.Buffer(), err
}
```
当timeout不等于0时，将timeout除以了time.Millisecond，但是在dubbo_invoker.go的getTimeout中，已经将时间处理成存入到attachment中
```
// get timeout including methodConfig
func (di *DubboInvoker) getTimeout(ivc *invocation.RPCInvocation) time.Duration {
	methodName := ivc.MethodName()
	if di.GetURL().GetParamBool(constant.GenericKey, false) {
		methodName = ivc.Arguments()[0].(string)
	}
	timeout := di.GetURL().GetParam(strings.Join([]string{constant.MethodKeys, methodName, constant.TimeoutKey}, "."), "")
	if len(timeout) != 0 {
		if t, err := time.ParseDuration(timeout); err == nil {
			// config timeout into attachment
			ivc.SetAttachment(constant.TimeoutKey, strconv.Itoa(int(t.Milliseconds()))) // 已经将timeout处理成毫秒存入attachment，应该将.Milliseconds()换成.Nanoseconds()
			return t
		}
	}
	// set timeout into invocation at method level
	ivc.SetAttachment(constant.TimeoutKey, strconv.Itoa(int(di.timeout.Milliseconds())))  // 已经将timeout处理成毫秒存入attachment，应该将.Milliseconds()换成.Nanoseconds()
	return di.timeout
}
```
最终导致timeout被缩小了1000000倍，变成了0，将上述方法中的两处Milliseconds()更改成Nanoseconds()，测试timeout获取正常

**Comment by DMwangnima** [comment]
We would be appreciated if you could help to submit a PR to resolve this issue. If not, I would fix this bug.

**Comment by chickenlj** [comment]
Please remember to backport to the main branch once fixed.

**Comment by Jafeyyu** [comment]
> Please remember to backport to the main branch once fixed.

I have submit a PR, please check and verify, thanks

**Comment by DMwangnima** [comment]
When analyzing the logic of ```DubboInvoker.getTimeout()``` and comparing it with dubbo's. We found another problem:

<img width="817" alt="image" src="https://github.com/apache/dubbo-go/assets/33331974/e5639bed-adfb-4617-a8e5-0727f0e121ee">


If users pass Reference.RequestTimeout directly, getTimeout could retrieve attachTimeout successfully, but it does not overwrite the value corresponding to constant.TimeoutKey with the parsed timeout value.

**Comment by chickenlj** [comment]
> If users pass Reference.RequestTimeout directly, getTimeout could retrieve attachTimeout successfully, but it does not overwrite the value corresponding to constant.TimeoutKey with the parsed timeout value.

Yeah, we need to move `ivc.SetAttachment(constant.TimeoutKey, strconv.Itoa(int(timeout.Milliseconds())))` out of the else  branch to make sure it always gets executed.

**Comment by chickenlj** [comment]
> 最终导致timeout被缩小了1000000倍，变成了0，将上述方法中的两处Milliseconds()更改成Nanoseconds()，测试timeout获取正常

hessian最开始的实现中为什么要做 `service.Timeout / time.Millisecond` 那？是有什么特殊原因吗

**Comment by Jafeyyu** [comment]
> > 最终导致timeout被缩小了1000000倍，变成了0，将上述方法中的两处Milliseconds()更改成Nanoseconds()，测试timeout获取正常
> 
> hessian最开始的实现中为什么要做 `service.Timeout / time.Millisecond` 那？是有什么特殊原因吗

我看了一下提交记录，dubbo_invoker.go从四年前添加getTimeout方法时就做了转换成millisecond的处理，而hession从3年前创建的时候就做了 `service.Timeout / time.Millisecond` 的处理，我个人感觉这个处理没有什么特殊原因，而是这两个地方没有协调好造成的。我当初选择更改dubbo_invoker.go中的getTimout处，是考虑在此处使用最基础的单位，然后其他地方可以按照各自的需求处理成想要的时间单位。但是如果决定要统一所有地方的时间单位，后续可以在dubbo_invoker的getTimeout方法中统一进行时间格式化，然后对hession进行变更，改为直接使用

**Comment by drama10096** [comment]
这个问题，使用dubbo-go的3.0.5版本经常出现，有没有解决掉，在哪一个版本修复了呢？？
