### ISSUE TITLE
I can not remove this waring.

### ISSUE THREAD

**Issue by majintao** [apache/dubbo-go#2558]
2024-01-03 18:47:45.742	WARN	tag/router.go:87	[-]	config center does not start, please check if the configuration center has been properly configured in dubbogo.yml%!(EXTRA []interface {}=[])	{"SW_CTX": "[xf-app,639f89eeaa2511eebcf552f3f496997d@192.168.24.77,N/A,N/A,-1]"}

**Comment by majintao** [comment]
func Start(conf Conf) error {
	if conf.LogLevel == "" {
		conf.LogLevel = "error"
	}
	logger.SetLoggerLevel(conf.LogLevel)

	applicationConfig := config.NewApplicationConfigBuilder().SetName(conf.AppName).Build()

	protocolConfigs := make(map[string]*config.ProtocolConfig, 0)
	if conf.ProtocolConfig.Name != "" {
		// 根据配置设置启动参数
		clientConfig := getty.GetDefaultClientConfig()
		params := conf.ProtocolConfig.Params
		if params.GrPoolSize != 0 {
			clientConfig.GrPoolSize = params.GrPoolSize
		}

		if params.ConnectionNumber != 0 {
			clientConfig.ConnectionNum = params.ConnectionNumber
		}

		if params.MaxMsgLen != 0 {
			clientConfig.GettySessionParam.MaxMsgLen = params.MaxMsgLen
		}

		if params.SessionName != "" {
			clientConfig.GettySessionParam.SessionName = params.SessionName
		}

		dubboPort := strconv.Itoa(conf.ProtocolConfig.Port)
		if dubboPort == "" {
			dubboPort = "-1"
		}
		dubboProtocolConfig := config.NewProtocolConfigBuilder().
			SetName(conf.ProtocolConfig.Name).SetPort(dubboPort).SetParams(clientConfig).Build()
		protocolConfigs[conf.ProtocolConfig.Name] = dubboProtocolConfig
	} else {
		// 默认配置
		defaultProtocolName := "dubbo"
		defaultDubboProtocolConfig := config.NewProtocolConfigBuilder().
			SetName(defaultProtocolName).SetPort("-1").Build()
		protocolConfigs[defaultProtocolName] = defaultDubboProtocolConfig
	}

	consumerConfig := config.NewConsumerConfigBuilder().SetCheck(false).SetReferences(References).Build()
	providerConfig := config.NewProviderConfigBuilder().SetServices(Services).Build()

	registryConfigs := make(map[string]*config.RegistryConfig, 0)
	for _, registry := range conf.Registries {
		registryConfigs[registry.Name] = config.NewRegistryConfigBuilder().
			SetProtocol(registry.Protocol).
			SetTimeout(registry.Timeout).
			SetRegistryType(registry.RegistryType).
			SetAddress(registry.Address).Build()
	}

	loggerConfig := config.NewLoggerConfigBuilder().SetDriver("zap").SetLevel("error").Build()
	rootConfig := config.NewRootConfigBuilder().
		SetApplication(applicationConfig).
		SetConsumer(consumerConfig).
		SetProvider(providerConfig).
		SetProtocols(protocolConfigs).
		SetLogger(loggerConfig).
		SetConfigCenter(config.NewConfigCenterConfigBuilder().Build()).
		SetRegistries(registryConfigs).Build()

	err := config.Load(config.WithRootConfig(rootConfig))

	if err != nil {
		return err
	}

	// 处理日志替换
	logger.SetLogger(NewCustomLogger(xflog.GetLogger().AddCallerSkip(2)))
	logger.SetLoggerLevel(conf.LogLevel)

	return nil
}

**Comment by FinalT** [comment]
I will fix this soon

**Comment by DMwangnima** [comment]
Resolved by #2559
