### ISSUE TITLE
Avoid unnecessary dependency on `dubbogo/grpc-go`

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo-go#2560]
Details in https://github.com/apache/dubbo-go/pull/2545#discussion_r1439132523

How about we make a copy of the definitions needed in dubbogo/grpc-go? I think it would be better to not depend on dubbogo/grpc-go except for some compatibility needs.

**Comment by shikharish** [comment]
Hello, I would like to work on this issue. Can you explain the issue bit more in detail?

**Comment by DMwangnima** [comment]
> Hello, I would like to work on this issue. Can you explain the issue a bit more in detail?

In protocol/triple/triple_protocol, there are some necessary dubbogo/grpc-go dependencies in files ended with "_compat" suffix. They are used for being compatible with dubbo3(old triple). But for other parts(e.g. protocol/triple/triple_protocol/codec.go), we have better make a copy of these definitions in dubbogo/grpc-go.

You can have a look and just comment here if you have any question :)

**Comment by shikharish** [comment]
@DMwangnima I have a few doubts.
- `server.go` uses `grpc.ServerStream` interface which is a parameter in the function `NewCompatStreamHandler()`, defined in `handler_stream_compat.go`. How should this be handled?

- Where exactly should I make these definitions?

**Comment by DMwangnima** [comment]
> @DMwangnima I have a few doubts.
> 
> * `server.go` uses `grpc.ServerStream` interface which is a parameter in the function `NewCompatStreamHandler()`, defined in `handler_stream_compat.go`. How should this be handled?
> * Where exactly should I make these definitions?

1. You do not need to do anything with this part. It is for compatibility.
2. For proto_wrapper_api, you can create a directory /protocol/triple/triple_protocol/internal/interoperability and put the proto file and pb.go file in it. For other definitions, you can just put them in /protocol/triple/triple_protocol/codec.go temporarily.

**Comment by shikharish** [comment]
@DMwangnima Opened a PR.
