### ISSUE TITLE
sentinel.TraceError和sentinel.Exit没有被调用

### ISSUE THREAD

**Issue by r27153733** [apache/dubbo-go#2620]
### Environment

- Server: Dubbo-go, v3.1.1
- Client: Dubbo-go, v3.1.1
- Protocol: Triple

### Issue description

context.WithValue 只能往子ctx存value，这导致OnResponse无法通过ctx.Value获取entry，导致entry没退出，sentinel.TraceError也不会被调用。

**Comment by DMwangnima** [comment]
Can you provide more detailed descriptions like the concrete code location or code screenshot?

**Comment by r27153733** [comment]
> 您能否提供更详细的描述，例如具体代码位置或代码截图？

![图片](https://github.com/apache/dubbo-go/assets/69096367/be285e59-9889-4496-973f-e7aa76b8a537)
![图片](https://github.com/apache/dubbo-go/assets/69096367/2f918915-5606-452a-bac0-986283cb55c9)
![图片](https://github.com/apache/dubbo-go/assets/69096367/e9bbf598-7c0b-4e56-bc09-5a26b2c07fb9)
![图片](https://github.com/apache/dubbo-go/assets/69096367/0d45851c-17d1-4725-a6ab-99e5532dd21a)
