### ISSUE TITLE
Fail to decode request due to: RpcInvocation

### ISSUE THREAD

**Issue by fionawp** [apache/dubbo-go#264]
**What happened**:

Java server dubbo version:  2.6.6 or 2.6.5.  
client: apache/dubbo-go  v1.2.0    apache/dubbo-go-hessian2 v1.3.0

The server interface is :
![image](https://user-images.githubusercontent.com/47594512/69522027-580fcf00-0f9b-11ea-98ac-242a62c6f496.png)
![image](https://user-images.githubusercontent.com/47594512/69522046-5e05b000-0f9b-11ea-993b-f0da275b7f41.png)

Golang errors:
using the dubbo version 2.6.0. Last error is java exception:Fail to decode request due to: RpcInvocation [methodName=queryDataDictionary, parameterTypes=[class java.lang.Object, class java.lang.Object], arguments=null, attachments={path=xx.xx.mt.MyProcessor, input=355, dubbo=2.0.2, version=}].

Jave errors:
WARN:com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:73) -  [DUBBO] Decode rpc invocation failed: readObject: unexpected end of file, dubbo version: 2.6.5
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
These errors happen everytime（必现)

**Anything else we need to know?**:

**Comment by fionawp** [comment]
Here is golang config:
![image](https://user-images.githubusercontent.com/47594512/69522773-331c5b80-0f9d-11ea-811d-c85d08419004.png)

Here is golang interface:
![image](https://user-images.githubusercontent.com/47594512/69522781-3879a600-0f9d-11ea-973e-fc89773827ee.png)

**Comment by fangyincheng** [comment]
you can try to use `func(ctx context.Context, req *DictionaryDto) (interface{}, error)`

**Comment by fangyincheng** [comment]
Hi, Has the problem been solved? @fionawp

**Comment by fionawp** [comment]
@fangyincheng  Yes, it has been solved. Thank you very much！
