### ISSUE TITLE
出现 --go-triple_out: exit status 127

### ISSUE THREAD

**Issue by linfun486** [apache/dubbo-go#2695]
### Environment

go version go1.22.4 darwin/arm64
dubbogo-cli Version: 1.0.0
protoc: libprotoc 27.1
protoc-gen-go v1.34.2
protoc-gen-go-triple 3.0.0

- Server: Dubbo-go,v3.2.0-rc1
- Client: Dubbo-go,v3.2.0-rc1
- Protocol: Triple
- Registry: nacos, v2.3.2

### Issue description

发现用新版本的triple.go文件有差异，多了Register******Handler方法，并在通过config-center启动时，需调用该方法进行注册。
故想尝试 protoc --go_out=. --go-triple_out=. ./user.proto    重新生成对应的*.triple.go文件 ，就报错走不下去了

目前发现windows版本可以正常生成*.triple.go文件，但是mac上就如下错误 `--go-triple_out: exit status 127`

### Logs
<details><summary>Click me to check logs</summary>
--go-triple_out: exit status 127 // 就这么一行
</details>

**Comment by chickenlj** [comment]
这里是新版本 triple 的使用示例，可以参考：

https://github.com/apache/dubbo-go-samples/tree/main/helloworld

**Comment by chickenlj** [comment]
我们这边建议是直接使用最新版本的 protoc 插件和生成的代码。基于这一点，我没完全理解你这边的问题，是新版本的代码生成遇到问题？还是不知道如何生成旧版本的代码？

**Comment by linfun486** [comment]
> 我们这边建议是直接使用最新版本的 protoc 插件和生成的代码。基于这一点，我没完全理解你这边的问题，是新版本的代码生成遇到问题？还是不知道如何生成旧版本的代码？

我昨晚找到问题了， 我的项目里面存在go.work 影响了module_path的获取，所以就报错了， 在[gen-triple](https://github.com/dubbogo/protoc-gen-go-triple)那边提交了一个pr 可以参考下哈

**Comment by chickenlj** [comment]
![image](https://github.com/apache/dubbo-go/assets/18097545/177f2b10-b3b7-4719-ac44-3e1cfecfe5bd)
