### ISSUE TITLE
 release the allocated memory of the ‘url’ field when destroy invoker

### ISSUE THREAD

**Issue by No-SilverBullet** [apache/dubbo-go#2701]
**What would you like to be added**:

 https://github.com/apache/dubbo-go/blob/faf6f2a27922f0259fa2b2779d238e8865779fe7/protocol/invoker.go#L92-L96

here is my question, since the invoker is destroyed ,so why do we  not set the url field in invoker to nil ,like below

func (bi *BaseInvoker) Destroy() {
	  logger.Infof("Destroy invoker: %s", bi.GetURL()) 
	  **bi.url = nil //add this**
	  bi.destroyed.Store(true)
	  bi.available.Store(false)
}

**Why is this needed**:
in this line, the invoker will be add to a global var dubboProtocol
https://github.com/apache/dubbo-go/blob/faf6f2a27922f0259fa2b2779d238e8865779fe7/protocol/dubbo/dubbo_protocol.go#L98

https://github.com/apache/dubbo-go/blob/faf6f2a27922f0259fa2b2779d238e8865779fe7/protocol/dubbo/dubbo_protocol.go#L59

so when destroy the invoker, the 'url' is useless and still it cannot be gc（unless destroy the global var）,which i think may cause memory leaks

**Comment by mark4z** [comment]
#2223
