### ISSUE TITLE
关于metadata的一些现象

### ISSUE THREAD

**Issue by leapig** [apache/dubbo-go#2706]
### Environment

- Server: Dubbo-go, v3.2.0-rc1
- Client: Dubbo-go, v3.2.0-rc1
- Protocol: Triple+pb
- Registry: Nacos, v2.3.2

### Issue description
service：core模块
client: gateway模块
两个服务启动后nacos配置中心会生成map文件，里面包含一个名字（如下图）
客户端的目录会生成dubbo.metadata.api文件
服务端启动日志报WARN    configurable/exporter.go:95     [Metadata Service] Dubbo-go 3.2.0 version's MetadataService only support dubbo protocol,MetadataService will use random port

### Logs
<details><summary>metadata</summary>
<img width="688" alt="截屏2024-07-17 10 26 23" src="https://github.com/user-attachments/assets/90c7e681-3407-4cc7-a5df-cf5841d3de23">

</details>

**Comment by FoghostCn** [comment]
这个日志是说 metadata service只支持 dubbo 协议，如果用户没有配置 dubbo 协议的端口，metadata service就会使用随机端口

**Comment by FoghostCn** [comment]
两个服务启动后nacos配置中心会生成map文件，里面包含一个名字（如下图）

这个是没问题的，mapping 是 接口到应用名的映射
