### ISSUE TITLE
yaml配置兼容性问题，目前能读取yaml后缀，无法读取yml后缀

### ISSUE THREAD

**Issue by leapig** [apache/dubbo-go#2708]
### Environment
- Server: Dubbo-go, v3.2.0-rc1
- Client: Dubbo-go, v3.2.0-rc1
- Protocol: Triple
- Registry: Nacos, v2.3.2

### Issue description

dubbo-go-sample项目部分文件配置文件是dubbogo.yml，无法跑起来，只能识别dubbogo.yaml文件

**Comment by YarBor** [comment]
目前来看，这是预期的行为，配置文件的路径由环境变量`DUBBO_GO_CONFIG_PATH`指定，
默认的配置路径是 `“../conf/dubbogo.yaml”`，
https://github.com/apache/dubbo-go/blob/cb400b2c8d464e5c0ad1d41478cfa734dd8c63e5/loader.go#L82C1-L108C2

dubbo-go-sample 在测试时，需要设置环境变量、指定配置文件。
```bash
    cd helloworld/go-server/cmd
    export DUBBO_GO_CONFIG_PATH="../conf/dubbogo.yml"
    go run .
```

**Comment by FoghostCn** [comment]
dubbo-sample 项目 需要配置 DUBBO_GO_CONFIG_PATH 环境变量
