### ISSUE TITLE
一些不成熟的社区发展意见和想法

### ISSUE THREAD

**Issue by walter211** [apache/dubbo-go#285]
**The following is based on the domestic situation in China：**

- 目前对dubbo-go给外界的整体感觉就是一个golang版的dubbo，是一个微服务框架，现在微服务圈go没有像java那么强的生态，也没有专业的机构出来微服标准，这样的话对dubbo-go这个项目本身的生态比较不利。比较好的方案就是结合K8S，做基于“云原生”的概念的做一套自己独有的解决方案，之前了解团队在为service mesh做一些方案规划，因为mesh和dubbogo这两个东西在架构上是两个完全独立的模块，彼此没有直接关联性，dubbo-go做为一个项目本身的定位，并不适合硬性切入到现在的mesh圈再做一套方案，还要跟istio，envoy，linkerd，sofamosn等积累比较长的项目竞争了，dubbo-mesh的意义要结合具体设想来探讨，是否有必要也打个问号。
- 在考虑dubbo-go这个团队中长期的发展规划，可能更需要考虑实际情况，依赖于go本身的特性和生态来出发，并且能够有落地的，dubbo-go的开发资源有限，更要把力量集中，个人建议未来可以考虑两个方向:1.照着spring cloud 做一套生态出来，往标准化做，并配合社区化运营，针对企业机构去落地方案，Go在并发方面的口碑会吸引第一波这类用户，如果做好会扩大自身影响力。2.想办法抢先支持OAM（Open Application Model），SpingCloud或者Dubbo用起来其实还是透明的，没有真的利用起K8S的特性和优势，OAM是一个趋势性标准，目前来看这是一个有可能产生红利的方向，当然跟随新标准也有很多不确定性，这个有待社区团队做进一步调研，了解OAM的具体规划和方向是否合适。
- dubbo-go对开发者的用户体验可以进一步完善，目前来看由于资源不足，对多层次的用户进入体验不是特别丝滑，建议是否考虑寻找其他开源社区合作，利用其他项目资源做自身的运营和推广。门户网站，命令行一键启动和一些起手demo有助于增加初级用户和初级企业的使用，降低dubbo-go的准入门槛，多鼓励外部开发者发布基于dubbo-go的第三方项目，初级发展可以针对性的指定一些方案和场景切入，找适合自身的产品形态作为突破，比如物联网，工业管理系统。

**Comment by flycash** [comment]
如果说我们其实并不是做一个完整的mesh，而仅仅是考虑适配过去istio等，就是说允许用户单纯将dubbogo作为微服务框架，但是可以使用mesh来作为服务治理的东西呢？虽然这样看上去有点奇怪，产出比也不高的样子；
我觉得往标准化做是一个很好的思路。做生态对设计和实现都有比较高的要求，也是一个不小的挑战；
接入教程之类的这种入门的东西，的确还需要进一步提高。我感觉在用户在选型的时候，这种教程文档类的会是一个比较大的考虑的点。
