### ISSUE TITLE
concurrent map writes for dubbo attachment

### ISSUE THREAD

**Issue by xujianhai666** [apache/dubbo-go#287]
fatal error: concurrent map writes
goroutine 38 [running]:
runtime.throw(0x9519b1, 0x15)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:617 +0x72 fp=0xc0001dcf38 sp=0xc0001dcf08 pc=0x42ed02
runtime.mapassign_faststr(0x8b1800, 0xc0015608a0, 0x94be5e, 0x7, 0xc00015d6c8)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/map_faststr.go:211 +0x41a fp=0xc0001dcfa0 sp=0xc0001dcf38 pc=0x41462a
github.com/apache/dubbo-go/protocol/invocation.(*RPCInvocation).SetAttachments(...)
	/home/travis/gopath/src/github.com/apache/dubbo-go/protocol/invocation/rpcinvocation.go:97
github.com/apache/dubbo-go/protocol/dubbo.(*DubboInvoker).Invoke(0xc0001ddea8, 0xa00ba0, 0xc001566480, 0x5, 0xc0001cc678)
	/home/travis/gopath/src/github.com/apache/dubbo-go/protocol/dubbo/dubbo_invoker.go:66 +0xfc8 fp=0xc0001dd990 sp=0xc0001dcfa0 pc=0x82db58
github.com/apache/dubbo-go/protocol/dubbo.TestDubboInvoker_Invoke(0xc0000b8c00)
	/home/travis/gopath/src/github.com/apache/dubbo-go/protocol/dubbo/dubbo_invoker_test.go:78 +0xa6a fp=0xc0001ddfa8 sp=0xc0001dd990 pc=0x83ce6a
testing.tRunner(0xc0000b8c00, 0x96b260)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/testing/testing.go:865 +0xc0 fp=0xc0001ddfd0 sp=0xc0001ddfa8 pc=0x4eb7c0
runtime.goexit()
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0001ddfd8 sp=0xc0001ddfd0 pc=0x45d911
created by testing.(*T).Run

**Comment by fangyincheng** [comment]
https://github.com/apache/dubbo-go/pull/288
