### ISSUE TITLE
Discussion on the high memory of ZK registry

### ISSUE THREAD

**Issue by pantianying** [apache/dubbo-go#300]
my service has been running online for some time. Recently, I found that the module of zookeeper registry takes up a lot of memory and has a growing trend。

![image](https://user-images.githubusercontent.com/20589945/71648813-203b3a80-2d44-11ea-8d2d-bbaaaf0d56f5.png)

So I started to analyze the source code：
#### this is where  memory is big：
![image](https://user-images.githubusercontent.com/20589945/71648833-5d073180-2d44-11ea-8005-9693c4d614e0.png)
![image](https://user-images.githubusercontent.com/20589945/71648854-950e7480-2d44-11ea-9c93-8936fd979ea9.png)

At first, I thought that there was a place where ZK. Conn.close() was not executed when zoopeep was reconnected, or ZK. Conn.close() did not release memory properly. But after many local tests, the memory can be released correctly.
Does Conn. watchers really take up so much memory in the server? At this point I noticed when we would add watcher.
![image](https://user-images.githubusercontent.com/20589945/71649073-a6588080-2d46-11ea-82e9-2bbafe0ebb05.png)

We know that when the Dubbo provider is restarted, the timestamp of the Dubbo path in the registry will change，like that：
![image](https://user-images.githubusercontent.com/20589945/71649156-47473b80-2d47-11ea-9198-373bbc39bafd.png)
At this time, the program will listen to the same Dubbo provider interface twice at the same time. As the number of reboots of Dubbo provider increases, the program will execute addwatcher multiple times,and cause high memory

**Comment by hxmhlt** [comment]
So when dubbo provider offline, the listener of the path can not stop?

**Comment by pantianying** [comment]
> So when dubbo provider offline, the listener of the path can not stop?

I think that when consumers perceive that the same interface has a new Dubbo path (details or timestamp changes), they should turn off the old subscription and delete the content in addWatcher.

I don't kown how java dubbo does , maybe we can learn from it

**Comment by pantianying** [comment]
Maybe we can use the above code：https://github.com/samuel/go-zookeeper/pull/110
