### ISSUE TITLE
Proposal: RESTful支持

### ISSUE THREAD

**Issue by flycash** [apache/dubbo-go#315]
目前dubbo已经支持将服务暴露成为RESTful服务，我们也需要支持该功能。
**What would you like to be added**:
总体设计：
![image](https://user-images.githubusercontent.com/9923838/72138142-1f02b100-33c7-11ea-8277-31cb229400f8.png)

一切问题的核心都在于建立RESTful和Service之间的映射关系。例如:
```go
type UserService interface {
    GetUser(id int) User
}
```
到http://localhost:8080/userService/{id}之间的映射。
对于服务端来说，是将收到的http请求映射到具体的Service上；
对于客户端来说，则是将调用Service的请求转化为http请求；

上面的图是客户端发起调用和服务端注册服务的过程。关键步骤是：
Invoker：
1. 首先，将本地调用和ReferRestConfig，结合在一起，到这一步完成了Service -> Rest的绑定；
2. 第一步完成的产物是一份metadata和请求参数，本步骤将利用metadata和请求参数来构造http请求，包括参数序列化，header设定；其中参数序列化可以是Json，也可以是XML，后续可以扩展到多媒体等；
3. http client发送请求。该步骤要允许用户自定义其连接参数，例如超时时间等；

当客户端收到响应的时候，只是上面三个步骤的逆转。

Exporter：
1. 当用户注册一个服务的时候，根据ExporterConfig和服务实现，完成Service -> Rest的绑定。注意此处是Service -> Rest，因为此时我们是暴露服务。当收到请求的时候，恰好是暴露服务的反向，即Rest -> Service；
2. Server在Export的时候并不做什么事情。但是在接受到请求的时候，它需要负责执行反序列化的过程;
3. http server是一个抽象隔离层。它内部允许使用beego或者gin来作为web服务器，接收请求，用户可以扩展自己的实现；

当服务端收到请求之后，其步骤则是：
1. http server收到http request，转交给server；
2. server根据RestService metadata找到Service，并将请求反序列化，构造好Service调用的上下文；
3. RequestMapper这时候将不会处理什么事情，而是直接转交给Service的实现。

另外一个核心是配置。我们将允许用户通过多种方式来配置RESTful信息，包括url, 连接参数等。默认情况下是从yml文件中读取。同时我们会实现通过二次编译（@张慧仁）、代码直接写入等方式。配置分成全局、interface级别、function级别。细粒度的覆盖粗粒度。

我们将支持以下几种场景：
1. 某个interface下的所有方法都暴露成为RESTful；
2. 某个interface下的部分方法暴露成为RESTful；
3. 某个interface下除去某些方法，其余方法暴露成为RESTful；

并且支持以下几种调用：
1. non-dubbo -> dubbo rest;
2. dubbo rest -> dubbo rest;
3. dubbo rest -> non-dubbo;
**Why is this needed**:

**Comment by kangkangv5** [comment]
请问这个功能大概多久可以实现并可以使用呢?

**Comment by zouyx** [comment]
@kangkangv5 you can check this PR : https://github.com/apache/dubbo-go/pull/352

**Comment by hbinr** [comment]
1. 请问如果暴露的REST接口多了，REST配置文件会写很长，后期维护管理很麻烦，开发人员看到一大坨配置，头都大了。
2. 开发这个REST的时候，有没有想过用户(开发者)的感受？ 越写月想tu
