### ISSUE TITLE
TODO List - 2020

### ISSUE THREAD

**Issue by flycash** [apache/dubbo-go#334]
No. | Task | Desc | Owner | status |  
-- | -- | -- | -- | -- | --
1 | Prometheus |   | @flixgithub | Processing |  
2 | metrics — Reservoir | we had developed some types of Reservoir, but there are two types, SlidingWindowReservoir and SlidingTimeWindowReservoir waiting for developing |   |   |  
3 | metrics — ClusterHistogram | A metric to calculate cluster histogram |   |   |  
4 | metrics — Timer | A timer metric which aggregates timing durations and provides duration statistics |   |   |  
5 | Opentracing |   | @flycash | done |  
6 | OpenTelemetry |   |   |   |  
7 | Istio | It’s a complicated task, we should split it into small tasks |   |   |  
8 | k8s — registry | using k8s as registry | @sxllwx | done |  
9 | k8s | It’s a complicated task, we should split it into small tasks |   |   |  
10 | Context support - jsonrpc protocol | We should allow user transfer their context end to end. For example, when we try to using opentracing, the key point is that how to transfer the traceId between client and server. | @flycash | done |  
11 | Context support - grpc protocol | @flixgithub | Processing |  
12 | Context support - dubbo protocol | @flycash | done |  
13 | tcp + protobuf v3 |   | @skyitachi | Processing |  
14 | thrift support |   |   |   |  
15 | callback parameter |   |   |   |  
16 | connections & concurrency control |   |   |   |  
17 | lazy connection |   | @CodingSinger |   |  
18 | sticky connection |   | @CodingSinger |   |  
19 | Restful protocol |   | @Patrick0308 @王凯 | Processing |  
20 | support generic invocation | Now users can invoke Java generic interface by dubbo-go, but dubbo-go doesn’t support generic service, which means that user can not expose their dubbo-go service as generic service. It’s much similar with Restful protocol. |   |   |  
21 | Dynamic rate limit  — BBR | Doing rate limit by collecting and calculating the system status. Like BBR |   |   |  
22 | Dynamic load balance | Doing load balance by collecting and calculating the system status. |   |   |  
23 | load balance - ConsistentHash |   | @imxyb | done |  
24 | configure center - nacos |   | @amudong | Processing |  
25 | configure center - consul |   |   |   |  
26 | configure center - etcd |   |   |   |  
27 | compatible with dubbo 2.7 | It’s a complicated task, we should split it into small tasks |   |   |  
28 | dubbo 2.7.5 - metadata center |   | @pantianying @hxmhlt | Processing |  
29 | adapt to dubbo admin |   |   |   |  
30 | code coverage | any PR writing unit tests to improve the code coverage will be helpful |   |   |  
31 | benchmarks & performance test |   |   |   |  
32 | samples |   |   |   |  
33 | Doc and blog |   |   |   |  
34 | user guide outline |   |   |   |  
35 | load balance - Healthy instance fitst | #337 | @CodingSinger | Processing |  
36 | base registry abstract | #339 | @hxmhlt |   |  
37 | dubbo 2.7.5 -new registrt model( application level) |   | @flycash | Processing |  
38 | dubbo 2.7.5 -TLS support |   |   |   |  
39 | dubbo 2.7.5 - TagRouter|   | @pantianying   |  Processing |

**Comment by CodingSinger** [comment]
I plan to develop a routing function similar to the health-first instance.

**Comment by AlexStocks** [comment]
out of date now.
