### ISSUE TITLE
Bug: config_center/nacos unit test not passed

### ISSUE THREAD

**Issue by hxmhlt** [apache/dubbo-go#362]
**What happened**:

Unit test of  github.com/apache/dubbo-go/config_center/nacos return error randomized：

2020/02/17 17:40:49 [InitLog] warn: log configure file name is nil
2020/02/17 17:40:49 [INFO] logDir:<logs/nacos/log>   cacheDir:</var/folders/2f/8mj4pf8d101300jmfbz431yw0000gn/T/go-build855660475/b216/cache>
2020-02-17T17:40:49.654+0800    WARN    nacos/client.go:216     nacosClient{name:nacos config_center, nacos addr:[127.0.0.1:65216]} exit now.
github.com/apache/dubbo-go/common/logger.Warnf
        /Users/hunter/01-GitProject/go_workspace/go-for-apache-dubbo/dubbo-go/common/logger/logging.go:47
github.com/apache/dubbo-go/config_center/nacos.(*NacosClient).Close
        /Users/hunter/01-GitProject/go_workspace/go-for-apache-dubbo/dubbo-go/config_center/nacos/client.go:216
github.com/apache/dubbo-go/config_center/nacos.HandleClientRestart
        /Users/hunter/01-GitProject/go_workspace/go-for-apache-dubbo/dubbo-go/config_center/nacos/facade.go:70
2020-02-17T17:40:49.654+0800    WARN    nacos/client.go:216     nacosClient{name:nacos config_center, nacos addr:[127.0.0.1:65216]} exit now.
github.com/apache/dubbo-go/common/logger.Warnf
        /Users/hunter/01-GitProject/go_workspace/go-for-apache-dubbo/dubbo-go/common/logger/logging.go:47
github.com/apache/dubbo-go/config_center/nacos.(*NacosClient).Close
        /Users/hunter/01-GitProject/go_workspace/go-for-apache-dubbo/dubbo-go/config_center/nacos/client.go:216
github.com/apache/dubbo-go/config_center/nacos.Test_newNacosClient
        /Users/hunter/01-GitProject/go_workspace/go-for-apache-dubbo/dubbo-go/config_center/nacos/client_test.go:28
testing.tRunner
        /usr/local/go/src/testing/testing.go:865
--- FAIL: Test_newNacosClient (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x14e324d]

goroutine 6 [running]:
testing.tRunner.func1(0xc00012a300)
        /usr/local/go/src/testing/testing.go:830 +0x392
panic(0x1575040, 0x1b4ed70)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/apache/dubbo-go/config_center/nacos.(*NacosClient).Done(...)
        /Users/hunter/01-GitProject/go_workspace/go-for-apache-dubbo/dubbo-go/config_center/nacos/client.go:176
github.com/apache/dubbo-go/config_center/nacos.Test_newNacosClient(0xc00012a300)
        /Users/hunter/01-GitProject/go_workspace/go-for-apache-dubbo/dubbo-go/config_center/nacos/client_test.go:29 +0x2dd
testing.tRunner(0xc00012a300, 0x1650500)
        /usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:916 +0x35a
FAIL    github.com/apache/dubbo-go/config_center/nacos  0.030s
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by hxmhlt** [comment]
@amudong

**Comment by zouyx** [comment]
![image](https://user-images.githubusercontent.com/3828072/74654552-7c0f3500-51c5-11ea-9050-e2ac2f52e4b7.png)
 
I guess the root cause in line 28 , c.client will be set to null at that line.

**Comment by amudong** [comment]
https://github.com/apache/dubbo-go/pull/363
