### ISSUE TITLE
Unit test error:  github.com/apache/dubbo-go/cluster/router/chain

### ISSUE THREAD

**Issue by hxmhlt** [apache/dubbo-go#407]
**What happened**:
Mac os  RUN UT :

--- FAIL: TestNewAppRouter (0.00s)
    app_router_test.go:49: 
                Error Trace:    app_router_test.go:49
                Error:          Received unexpected error:
                                zk: unable to find server jar
                                zk.Connect
                Test:           TestNewAppRouter
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1318076]

goroutine 8 [running]:
testing.tRunner.func1(0xc0000de400)
        /usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x13a08a0, 0x16f71b0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:74
github.com/apache/dubbo-go/remoting/zookeeper.(*ZookeeperClient).Create(0x0, 0x142959c, 0x33, 0xc00000ebc0, 0x0)
        /Users/hunter/01-GitProject/go_workspace/go-for-apache-dubbo/dubbo-go/remoting/zookeeper/client.go:406 +0x246
github.com/apache/dubbo-go/cluster/router/condition.TestNewAppRouter(0xc0000de400)
        /Users/hunter/01-GitProject/go_workspace/go-for-apache-dubbo/dubbo-go/cluster/router/condition/app_router_test.go:50 +0xed
testing.tRunner(0xc0000de400, 0x1433480)
        /usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:960 +0x350
FAIL    github.com/apache/dubbo-go/cluster/router/condition     0.033s
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by zouyx** [comment]
![image](https://user-images.githubusercontent.com/3828072/76695590-673a9a00-66bc-11ea-8277-1ac4b439ad8b.png)

i think base cause is the directory which is called  ```zookeeper-4unittest```  not exits. You should run before_ut.sh on mac/linux or before_ut.bat on windows

**Comment by hxmhlt** [comment]
I pull the latest code and it works well.
