### ISSUE TITLE
Proposal: rest protocol add filter support by gorestful

### ISSUE THREAD

**Issue by hxmhlt** [apache/dubbo-go#412]
**What would you like to be added**:

Rest protocol add filter support by gorestful.

**Why is this needed**:

Gorestful support filter .

**Comment by hxmhlt** [comment]
@Patrick0308

**Comment by Patrick0308** [comment]
See PR #414

**Comment by zouyx** [comment]
this issue has done or not ？

**Comment by Patrick0308** [comment]
@zouyx done
