### ISSUE TITLE
服务暴露，只能通过配置文件吗？

### ISSUE THREAD

**Issue by libra1010** [apache/dubbo-go#416]
如题，如果我需要暴露N个服务
都需要在配置文件 一个一个的暴露吗？
这样的话，配置文件不会很长吗？

**Comment by zouyx** [comment]
是的，目前只能通过配置文件。在暴露多的情况下不排除有你所提到的可能性，如果有更好的方案。可以通过 issue ，PR 或者钉钉交流群提出。

**Comment by flycash** [comment]
我觉得一个可以改进的方案是允许配置文件引用别的配置文件，这样可以方便用户组织配置。比如说所有用户相关的服务放在一个配置文件，订单相关的服务放在另外一个配置晚间。但是它们是一起部署的单一实例。

**Comment by fangyincheng** [comment]
当前是可以通过直接构造 ConsumerConfig  以代码的方式 Load  配置的。

**Comment by hetianxia** [comment]
get,set 可以替换references & services

**Comment by flycash** [comment]
@hetianxia 我没太理解你的意思。你是想达成一个什么样最终效果？可以举例说明吗？

**Comment by hetianxia** [comment]
@flycash 大明哥，我是回答题主的问题，
func SetProviderConfig(p ProviderConfig) {
	providerConfig = &p
}
在Load() config之前，通过SetProviderConfig 方法，引入其他途径配置的Services & References

**Comment by cityiron** [comment]
WIP

**Comment by AlexStocks** [comment]
same as issue https://github.com/apache/dubbo-go/issues/1140
