### ISSUE TITLE
Imp: change k8s labels

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go#458]
**What would you like to be added**:

![image](https://user-images.githubusercontent.com/7959374/77813142-26da1380-70e1-11ea-8d9e-c4d17e1f1bf0.png)

If the provider wanna register to k8s, its label should be `"dubbo.io/label":"dubbo.io.provider"` while the consumer label should be `"dubbo.io/label":"dubbo.io.consumer"`.

**Why is this needed**:

To get less data while consumer list&watch api server.

**ref doc**:
[What's new of dubbogo v1.4](https://juejin.im/post/5e7cc8466fb9a009a0575c1a)

**Comment by AlexStocks** [comment]
cc @sxllwx

**Comment by sxllwx** [comment]
Hello, although the separate registration of Provider and Consumer can reduce the number of long connections maintained by kube-apiserver, but I think that the Kubernetes registry is highly coupled with the upper-level business and reduces the amount of information available on the provider side. Homogenous other registration centers, such as etcdv3, Zookeeper do not provide different interfaces for Provider and Consumer.
