### ISSUE TITLE
Example: zookeeper test steps

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go#464]
**What you expected to happen**:

服务端我们使用dubbo-sample中的go-service，客户端使用dubbogo/dubbo-go-proxy,这个proxy可以手动控制和调用你要调用的接口，不需要写额外的测试代码。具体使用参见dubbogo/dubbo-go-proxy README。注意，测试前先保证provider和consumer的dubbo-go版本已经是你想测试的版本。

Test steps

case1 
测试目的：本测试的目的是观察先启动consumer后启动provider的时候，dubbogo是否能在provider启动后及时观察到provider。
测试步骤：
Step1 启动 zk；
Step2: 启动 consumer；
Step3: 启动 provider；
Step4: 手动调用 观察结果；

Case2
目的：有新添加的服务时，consumer 能否及时感知
测试步骤：
Step1 启动 zk；
Step2: 启动 consumer；
Step3: 启动 provider；
Step4: 手动调用 观察结果；
Step5: 启动一个新的 provider；
Step6: 手动调用新的provider 观察结果；
观测结果：

Case3:
目的：有服务挂掉时，consumer 能否及时感知
测试步骤：
Step1 启动 zk；
Step2: 启动 consumer；
Step3: 启动 两个 provider；
Step4: 关闭其中一个 provider；
Step5: 手动调用两个provider 观察结果；

Case4:
目的：zk 挂掉时，consumer 能否继续调用服务
测试步骤：
Step1 启动 zk；
Step2: 启动 consumer；
Step3: 启动 两个 provider；
Step4: 杀死 zk；
Step5: 手动调用两个provider 观察结果；
Step6: 10分钟后再次启动 zk，在 10 分钟内 consumer 多次手动调用服务，观察结果；

Case5:
目的：zk 重启时，consumer 能否继续调用服务，是否能继续监听到provider端变化
测试步骤：
Step1 启动 zk；
Step2: 启动 consumer；
Step3: 启动 两个 provider；
Step4: 手动调用两个provider 观察结果；
Step5: 杀死 zk；
Step6: 手动调用两个provider 观察结果；
Step7: 1分钟后再次启动 zk
Step8: 关闭其中一个 provider；手动调用两个provider 观察结果；
Step9: 启动关闭的provider；手动调用两个provider 观察结果；

**Comment by pantianying** [comment]
1. Use Dubbo-go to provide more then two interface interfaces. Here you can use go-server in Dubbo-sample. If you want to only test go-client, you can also use java-server. Configure the ZK address to start the provider.

2. We use dubbogo/dubbo-go-proxy on the client side, which is very convenient for testing and calling. You need to configure the corresponding ZK address to start the service. Please refer to project readme.md for the starting method

3. Call the provider through dubbogo/dubbo-go-proxy by calling the http interface manually, and observe whether the call is enabled. See readme.md for specific call methods

4. Stop zookeeper, repeat (3)

5. Start zookeeper, repeat (3)

6. Stop provider, repeat (3)

7. Start provider, repeat (3)
