### ISSUE TITLE
Ftr: When will the generalization call be supported

### ISSUE THREAD

**Issue by Sharember** [apache/dubbo-go#47]
like java GenericService

**Comment by hxmhlt** [comment]
@CFMystery generic service & reference will be supported in next version. You can keep your focus on the go-for-apache-dubbo project through the [roadmap](https://github.com/dubbo/go-for-apache-dubbo/wiki/Roadmap). TKS!

**Comment by hxmhlt** [comment]
This issue is same as #47

**Comment by AlexStocks** [comment]
https://github.com/apache/dubbo-go/pull/122
