### ISSUE TITLE
Optimize the design of Router

### ISSUE THREAD

**Issue by flycash** [apache/dubbo-go#477]
Now the Router has two key interfaces:
![image](https://user-images.githubusercontent.com/9923838/79312764-f04e2680-7f31-11ea-9c87-63f6833c2bb5.png)

![image](https://user-images.githubusercontent.com/9923838/79312774-f5ab7100-7f31-11ea-9d0d-0144eb75d35e.png)

However, we use `Chain` interface in our codes as the entrance, like:
![image](https://user-images.githubusercontent.com/9923838/79312936-3a370c80-7f32-11ea-9df5-dcb7118a5d5d.png)

We should notice that, the Router is the top abstraction. Using `Chain` in codes will reduce the expandability.

So I proposal to refactor the design.

Firstly, we keep the `Router` interface, but remove the `Priority` method;
Secondly,  we keep `Chain` interface, but it will implement `Router` interface, which means that `Chain` is a `Router` too but it's more complicated.
Thirdly, we define `PriorityRouter` which is the `Router` interface + `Priority` method;
Finally, we will replace `Chain` with `Router` in our codes. The `Router` instance should be fetched from `extension`;

The class diagram is:
 
![image](https://user-images.githubusercontent.com/9923838/79318081-25aa4280-7f39-11ea-9534-d2656384a689.png)

The benefit is that:
1. User can schedule many routers by their own way, not just Chain;
2. Only `Router` interface are exposed outside the Router module;

**Comment by zouyx** [comment]
i will check it later
