### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by hxmhlt** [apache/dubbo-go#49]
No|Task|owner|Status
----|------------|-------------|------
1|cluster strategy: Failfast/Failsafe/Failback|@xujianhai666|done
2|loadbalance: RoundRobin/LeastActive|诣极|done
3|filter :AccessLogFilter|@flycash |done
4|routing rule|@aliiohs| doing
5|default monitor(prometheus)|晓冬|doing
6|trace(jeager impl)|晓冬
7|asynchronous call | @zouyx  | done
8|callback parameter|
9|delay pubilsh|deprecated
10|connections & concurrency control|
11|lazy connection|@CodingSinger
12|sticky connection|@CodingSinger
13|Token Authorization|@xujianhai666|done
14|Service-Downgrade|@YGrylls|done
15|graceful exit|@flycash|done
16|user guide outline |
17|generic invoke|@pantianying|done
18|TPS limit|@flycash |done
19|loadbalance: ConsistentHash|@imxyb |
20|support java generics|
21|appollo config center|@xujianhai666|done
22|http restful|@yiduwangkai|
23|thrift supportl|@aliiohs|
24|etcd/consul config center impl|@xujianhai666|
25|nacos config center impl|@amudong|done
26|setLoggerLevel function|@fangyincheng|doing
27|k8s as registry|@yiduwangkai|doing
28|grpc|@xujianhai666|doing
29|protocol buffer| @skyitachi |doing
30|Adapt to Dubbo admin|
31|generic implement|@Patrick0308|done

**Comment by zonghaishang** [comment]
2. 我练下手

**Comment by Xiaoweixianbin** [comment]
1.我接了

**Comment by AlexStocks** [comment]
@Xiaoweixianbin Pls join DingDing group 23331795.

**Comment by hxmhlt** [comment]
1，2，3都已经有人接了。

**Comment by hxmhlt** [comment]
@Xiaoweixianbin 可以先加QQ群，群号:196953050

**Comment by zonghaishang** [comment]
RoundRobin & LeastActive 开发完成，正在测试，预计31号之前提交测试通过后的mr.

**Comment by AlexStocks** [comment]
@zonghaishang sounds a good news for me. thx for ur good work.

**Comment by aliiohs** [comment]
I will impl 4th

**Comment by yiduwangkai** [comment]
12和13我来做吧

**Comment by hxmhlt** [comment]
> 11和12我来做吧

ok owner is change

**Comment by xujianhai666** [comment]
6 、13、14 我认领下

**Comment by hxmhlt** [comment]
@xujianhai666 6和14已经有人领了，我先把13owner给你。

**Comment by xujianhai666** [comment]
asynchronous call 我own下，我的第一个任务已经提交pr了

**Comment by flycash** [comment]
18. TPS limit, I will add this feature.

**Comment by xujianhai666** [comment]
21 appollo config center:  认领

**Comment by hxmhlt** [comment]
@flycash @xujianhai666 owner changed

**Comment by Patrick0308** [comment]
我想做19

**Comment by flycash** [comment]
I would like to do 15.

**Comment by Patrick0308** [comment]
claim the task of 31 generic implement

**Comment by skyitachi** [comment]
claim the task of 29  protobuf

**Comment by flycash** [comment]
It had been move to #334
