### ISSUE TITLE
Samples collation and integration testing

### ISSUE THREAD

**Issue by fangyincheng** [apache/dubbo-go#498]
**What would you like to be added**:

This issue is to get a solutioin for samples collation and integration testing. After that, we will start it.

**Why is this needed**:

1. experience of dubbo-go's samples is not very good. 
2. dubbo-go need a complete integration testing.

**Comment by zouyx** [comment]
https://github.com/apache/dubbo-go-samples

**Comment by zouyx** [comment]
done
