### ISSUE TITLE
API design problem causes lock copy

### ISSUE THREAD

**Issue by cch123** [apache/dubbo-go#511]
Currently,  dubbo-go NewURL returns a non-ptr instance of URL，NewURLWithOptions returns a ptr of URL, 

```go
func NewURL(urlString string, opts ...option) (URL, error) {

func NewURLWithOptions(opts ...option) *URL {
```

and Register API uses a non-ptr instance of URL:

```go
func (r *BaseRegistry) Register(conf common.URL) error {
```

This will cause a lock copy, because URL contains a mutex field:

```go
type baseUrl struct {
	Protocol string
	Location string // ip+port
	Ip       string
	Port     string

	paramsLock   sync.RWMutex   <------ here
	params       url.Values
	PrimitiveURL string
}
```

The Register API should accept a pointer to avoid this

**Comment by AlexStocks** [comment]
Basically, why copy a this var?

**Comment by flycash** [comment]
We should think about removing the lock from baseUrl

**Comment by AlexStocks** [comment]
> We should think about removing the lock from baseUrl

agree with u.
