### ISSUE TITLE
[Imp] modify codes by code review of gitee

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go#514]
**What would you like to be added**:

improve the code quality scanned by gitee, from  the following two links,

[gitee_scans](https://gitee.com/dubbogo/dubbo-go/gitee_scans/report?task_id=723471)
[quality_analyses](https://gitee.com/dubbogo/dubbo-go/quality_analyses?platform=sonar_qube)

**Why is this needed**:

Improve the code quality.

**Comment by AlexStocks** [comment]
to [georgehao](github.com/georgehao)

**Comment by zouyx** [comment]
@georgehao
