### ISSUE TITLE
[Enhance] improve code coverage for config_center

### ISSUE THREAD

**Issue by zouyx** [apache/dubbo-go#518]
**What would you like to be added**:

* improve code coverage for config_center, ref : [config_center coverage](https://codecov.io/gh/zouyx/dubbo-go/tree/master/config_center)
![image](https://user-images.githubusercontent.com/3828072/82203789-59acc500-9936-11ea-9439-e47ae94911b5.png)

**Why is this needed**:

**Comment by zouyx** [comment]
@georgehao

**Comment by Patrick0308** [comment]
Now the code coverage of config_center is more than 80%.
