### ISSUE TITLE
ASOC: dubbo-go API-Gateway

### ISSUE THREAD

**Issue by sxllwx** [apache/dubbo-go#540]
# dubbo-go API-Gateway

基于[1.4.0](https://github.com/apache/dubbo-go/tree/v1.4.0) 版本发布的应用级服务发现与注册模型，实现 dubbo-go API-Gateway 。

## 背景

 API-Gateway 是整个服务集群的唯一入口点，它类似于面向对象设计模式中的 Facade 模式。API-Gateway对客户端隐藏了服务集群的具体实现，给客户端提供了一个唯一的接入点。 API-Gateway 可完成的众多功能大多都建立在以下两点:

* 可以劫持所有客户端的所有流量，并对流量进行处理以及路由。
* API-Gateway 可以对接服务注册中心，并通过注册中心获得所有最终服务进程的 IP/Port 的信息。

基于以上两点， 我们期望以下特性（REQUIRED必须实现， OPTIONAL 实现越多越好）:

* 动态的发现服务【REQUIRED】
* 路由请求【REQUIRED】
* 协议转换【REQUIRED】
* 负载均衡 【OPTIONAL】
* TLS加解密【OPTIONAL】
* 监控【OPTIONAL】
* 追踪【OPTIONAL】
* 限流【OPTIONAL】

## 实现方案（目标）

对接已实现的任何一个已有的注册中心( zookeeper , consul , nacos , etcd , kubernetes ) 实现 API-Gateway 。

**Comment by YuzeZhang** [comment]
HI！
I've finished my proposal on this.

**Comment by jack15083** [comment]
暴露出的网关接口希望可以做到动态配置 

- 可以支持动态配置网关接口的上下线

- 可以支持动态配置网关接口的限流、熔断

- 可以支持动态配置网关接口的参数、路由

后期可以考虑做一个网关配置管理界面，来配置管理及监控网关服务接口。

**Comment by judong** [comment]
1. 能够配合ZK,或NACOS 动态发现服务。
2. 能够根据发现的服务，自动生成rest，grpc 等其它服务。
3. 动态分析出服务的接口名，参数等配置。

**Comment by pantianying** [comment]
本质上第一期可以实现x协议到dubbo协议的网关。使得应用可以用通用协议调用dubbo-go-proxy来访问dubbo集群中任意的接口。客户端不需要接入dubbo的任何组件。像上面说的“能够配合ZK,或NACOS 动态发现服务。”目前已经实现。
1.代码模块化,打好基础。入口流量协议解析，中间filter、metric层以及调用层解耦。
2.入口流量协议解析（http,http2,grpc）,先把代码解耦，先实现http，把接口预留出来以后实现其他协议。
3.filter层实现一种（限流 熔断都可）
4.优化目前调用dubbo-go的能力。在目前基础上增加动态路由、配置指定dubbo-url访问接口。

**Comment by sanxun0325** [comment]
1：流量染色进行灰度发布
2：分组隔离
3：可以参考spring-cloud-gateway filter 链。
4：全局filter,路由filter
5：动态路由
6:   统一认证/鉴权

**Comment by chai2010** [comment]
1. 描述rest：name，req结构，resp结构，args和req结构对应
2. 根据api描述生成路由代码

https://github.com/chai2010/pbgo#example-rest-api
