### ISSUE TITLE
ASOC: dubbo-go Sidecar

### ISSUE THREAD

**Issue by sxllwx** [apache/dubbo-go#541]
# dubbo-go Sidecar

基于[1.4.0](https://github.com/apache/dubbo-go/tree/v1.4.0) 版本发布的应用级服务发现与注册模型与配置中心，实现 dubbo-go Sidecar 。

## 背景

[sidecar模式](https://docs.microsoft.com/en-us/azure/architecture/patterns/sidecar)是目前服务网格数据平面代理实现的常规手段，使用本地劫持的方式代理客户端的请求，可以通过对用户请求的整形后再将请求路由到本地提供服务的进程所监听的端口。sidecar进程以入侵 runtime 少量入侵或不入侵 code 的原则进行设计和实现，具体如 envoy mosn 等。

基于 dubbo-go 已有的配置中心和服务注册中心， 我们期望实现的sidecar具有以下特性（REQUIRED必须实现， OPTIONAL 实现越多越好）:

* 自愈，能够在业务进程宕机时自动重新拉起，并将之前的请求进行重放【REQUIRED】
* TLS加解密【REQUIRED】
* 能够将不同的协议进行转换， dubbo 协议与HTTP一些的互相切换【OPTIONAL】
* 监控【OPTIONAL】
* 追踪【OPTIONAL】

## 实现方案（目标）

对接已实现的任何一个已有的配置中心以及注册中心( zookeeper , consul , nacos , etcd , kubernetes ) 实现 Sidecar 。

**Comment by zouyx** [comment]
翔哥，版本号写错了，是：基于 v1.4.0
