### ISSUE TITLE
How to debug dubbogo with Goland ?

### ISSUE THREAD

**Issue by georgehao** [apache/dubbo-go#546]
**What would you like to be added**:

The tutorial of how to debug dubbgo with goland 

**Why is this needed**:

I want debug dubbogo with Goland to analysis the program details

**Comment by AlbumenJ** [comment]
https://github.com/dubbogo/dubbo-samples/blob/master/golang/README.md

![image](https://user-images.githubusercontent.com/9292748/84624151-6c092700-af13-11ea-8ff6-856dc7d2d1a7.png)
