### ISSUE TITLE
Why not use the default client

### ISSUE THREAD

**Issue by mark1995** [apache/dubbo-go#585]
**About dubbo-go call** 
The referf method invoker in dubbo_protocol will generate a client each time, and the client is bound to two goroutines. There may be a memory leak. _code_:

```
`
        invoker := NewDubboInvoker(url, NewClient(Options{
		ConnectTimeout: config.GetConsumerConfig().ConnectTimeout,
		RequestTimeout: requestTimeout,
	}))
`
```

**Comment by flycash** [comment]
#256 
We reuse the connection in getty.
please check https://github.com/apache/dubbo-go/pull/482/files

**Comment by mark1995** [comment]
> it is the same as #256.
> We reuse the connection in getty.
> please check https://github.com/apache/dubbo-go/pull/482/files


Thank you for your reply, but I haven't seen such processing in the latest branch and master branch. Is there any new consideration? In the code, we still see that the new client will create a new connection pool.

```
func (p *gettyRPCClientPool) getGettyRpcClient(protocol, addr string) (*gettyRPCClient, error) {
	conn, err := p.get()
	if err == nil && conn == nil {
		// create new conn
		rpcClientConn, err := newGettyRPCClientConn(p, protocol, addr)
		return rpcClientConn, perrors.WithStack(err)
	}
	return conn, perrors.WithStack(err)
}
```


In the example given by the official, this operation will cause a memory leak about goroutine:
```
     referenceConfig.GetRPCService().(*config.GenericService).Invoke([]interface{}{"GetUser",[]string{"java.lang.String"}, []interface{}{"A003"}})
```

**Comment by AlexStocks** [comment]
hey, guy. u can get the right pr is [pr-495](https://github.com/apache/dubbo-go/pull/495).

If any other problems, ur suggestions or prs  are welcome.

**Comment by pantianying** [comment]
> > it is the same as #256.
> > We reuse the connection in getty.
> > please check https://github.com/apache/dubbo-go/pull/482/files
> 
> Thank you for your reply, but I haven't seen such processing in the latest branch and master branch. Is there any new consideration? In the code, we still see that the new client will create a new connection pool.
> 
> ```
> func (p *gettyRPCClientPool) getGettyRpcClient(protocol, addr string) (*gettyRPCClient, error) {
> 	conn, err := p.get()
> 	if err == nil && conn == nil {
> 		// create new conn
> 		rpcClientConn, err := newGettyRPCClientConn(p, protocol, addr)
> 		return rpcClientConn, perrors.WithStack(err)
> 	}
> 	return conn, perrors.WithStack(err)
> }
> ```
> 
> In the example given by the official, this operation will cause a memory leak about goroutine:
> 
> ```
>      referenceConfig.GetRPCService().(*config.GenericService).Invoke([]interface{}{"GetUser",[]string{"java.lang.String"}, []interface{}{"A003"}})
> ```

refer method will  do NewDubboInvoker, but  refer

**Comment by pantianying** [comment]
> **About dubbo-go call**
> The referf method invoker in dubbo_protocol will generate a client each time, and the client is bound to two goroutines. There may be a memory leak. _code_:
> 
> ```
> `
>         invoker := NewDubboInvoker(url, NewClient(Options{
> 		ConnectTimeout: config.GetConsumerConfig().ConnectTimeout,
> 		RequestTimeout: requestTimeout,
> 	}))
> `
> ```

refer只会在加载配置的时候执行一边，不清楚你说的'generate a client each time',啥意思。如果可以的话可以加我们钉钉群 一起讨论下。

**Comment by mark1995** [comment]
感谢，我们这边使用姿势有问题，直接照搬了demo中的调用方式，每次call的时候都调用这段函数，导致多次调用Refer,进而生成了很多client。
```
func (c *ReferenceConfig) GenericLoad(id string) {
	genericService := NewGenericService(c.id)
	SetConsumerService(genericService)
	c.id = id
	c.Refer(genericService)
	c.Implement(genericService)
	return
}
```

**Comment by mark1995** [comment]
> > **About dubbo-go call**
> > The referf method invoker in dubbo_protocol will generate a client each time, and the client is bound to two goroutines. There may be a memory leak. _code_:
> > ```
> > `
> >         invoker := NewDubboInvoker(url, NewClient(Options{
> > 		ConnectTimeout: config.GetConsumerConfig().ConnectTimeout,
> > 		RequestTimeout: requestTimeout,
> > 	}))
> > `
> > ```
> 
> refer只会在加载配置的时候执行一边，不清楚你说的'generate a client each time',啥意思。如果可以的话可以加我们钉钉群 一起讨论下。#51

感谢，我们这边使用姿势有问题，直接照搬了demo中的调用方式，每次call的时候都调用这段函数，导致多次调用Refer,进而生成了很多client。
```

func (c *ReferenceConfig) GenericLoad(id string) {
	genericService := NewGenericService(c.id)
	SetConsumerService(genericService)
	c.id = id
	c.Refer(genericService)
	c.Implement(genericService)
	return
}
```
