### ISSUE TITLE
Aligh with Dubbo: IDL support

### ISSUE THREAD

**Issue by flycash** [apache/dubbo-go#595]
**What would you like to be added**:

The feature that allows users to use IDL(Interface definition language) to define RPC service

**Why is this needed**:

**Comment by xianlezheng** [comment]
i can try to do  this issue. :）

**Comment by zouyx** [comment]
Reference : https://github.com/apache/dubbo/tree/master/compiler

**Comment by hxmhlt** [comment]
![image](https://user-images.githubusercontent.com/13016899/88784437-a0cef600-d1c2-11ea-88c1-f1fb4d74d0fe.png)

**Comment by zouyx** [comment]
won't support
