### ISSUE TITLE
Align with Dubbo: Nearest first for multiple registry

### ISSUE THREAD

**Issue by flycash** [apache/dubbo-go#597]
**What would you like to be added**:

wait for detail design and proposal

**Why is this needed**:

**Comment by DogBaoBao** [comment]
I want to do this, but I not sure what this meaning?

**Comment by zouyx** [comment]
> I want to do this, but I not sure what this meaning?

It’s ok,contact us with dingding group as below. We can explain how to implement it. 
“dubbogo社区”群的钉钉群号： 23331795

Thanks.

**Comment by zouyx** [comment]
Reference: https://blog.csdn.net/weixin_45583158/article/details/103900690

The seventh section in the article
