### ISSUE TITLE
Group and version key compatibility with dubbo-java

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo-go#606]
**What happened**:
Dubbo comsumer in Java unable to discovery provider provided by Dubbo-go.

**How to reproduce it (as minimally and precisely as possible)**:
- run provider as https://github.com/AlbumenJ/dubbogo-helloworld
- run comsumer as https://github.com/AlbumenJ/dubbo-helloworld

Provider's properties is under dev folder. Run comsumer as springboot program and it will automaticly execute CommandLineRunner.

**Anything else we need to know?**:

- What dubbo-go register to Nacos
![image](https://user-images.githubusercontent.com/9292748/84626177-4120d200-af17-11ea-9882-6718703cf8b8.png)
![image](https://user-images.githubusercontent.com/9292748/84626221-50078480-af17-11ea-9e8f-542885447fc0.png)

- What dubbo-java get from Nacos

  - 2.7.3 2.7.5 version
    
  Comsumer expect to get instances with serviceName `providers:cn.albumenj.demo.UserProvider::`, but provider only register `providers:cn.albumenj.demo.UserProvider`

![image](https://user-images.githubusercontent.com/9292748/84626339-7c230580-af17-11ea-8d90-fe626d542754.png)

  - 2.7.7 version

  Because of the metadata get from registry contains group key and version key, when getting parameter from provider url the result is empty, not null. Empty string is not equal with null string.

![image](https://user-images.githubusercontent.com/9292748/84626691-213dde00-af18-11ea-8570-4a8c7d22612e.png)

**Comment by zouyx** [comment]
I had confirmed nacos registry is great.

Use `https://github.com/apache/dubbo-samples/tree/master/golang/registry/nacos`

Dubbo version is 2.6.5(required)

I think dubbo has changed namespace in 2.7.x . 

Compatible version is still developing as below 

https://github.com/apache/dubbo-go/pull/604

**Comment by zouyx** [comment]
If has any question you can reopen it.
