### ISSUE TITLE
兼容dubbo 2.7.3 注册nacos时serviceName最后多出来一个冒号的临时解决方案

### ISSUE THREAD

**Issue by coffeehc** [apache/dubbo-go#642]
在references里面的服务配置的version变量值最后面加上一个冒号即可解决，原因如下：

https://github.com/apache/dubbo-go/blob/b568e86aa37b30687b9fc9dc21ec7d5fb045ddb1/registry/nacos/registry.go#L136-L142

这里面的都是直接拼接的，由于group为空，所以不会有最后的冒号，为了兼容新老版本的拼接策略差异，建议直接在配置的版本号的时候直接在版本号后面带上冒号来解决这个问题。呃，也许不一定说清楚了，请开发组的同学补充一下吧。

**Comment by hxmhlt** [comment]
@gaoxinge
