### ISSUE TITLE
data race

### ISSUE THREAD

**Issue by zhaoche27** [apache/dubbo-go#649]
/remoting/zookeeper/facade.go
r.ZkClient().Done().    

func (r *zkRegistry) ZkClient() *zookeeper.ZookeeperClient {
	return r.client
}

registry/zookeeper/registry.go
r.client.Close().     
r.client=nil

**Comment by AlexStocks** [comment]
@zhaoche27 U can describe ur problem in Chinese to let us know it clearly.

**Comment by AlexStocks** [comment]
can not get reply in so long time. close it.
