### ISSUE TITLE
Raise the version of consul and client-go

### ISSUE THREAD

**Issue by cvictory** [apache/dubbo-go#656]
The latest version of consul is v1.8.0 (github.com/hashicorp/consul)  and we should raise the version of client-go to v0.16.9 or v0.17.0.

After raising the version, we should do some unit test and function test.

**Comment by gaoxinge** [comment]
I have updated

- consul version to 1.8.0
- client-go version to v0.16.9

in develop branch, which can be checked in [go.mod](https://github.com/apache/dubbo-go/blob/develop/go.mod).
