### ISSUE TITLE
Data in cache  is not synchronized after the provider updates in zk

### ISSUE THREAD

**Issue by wenxuwan** [apache/dubbo-go#660]
Hi all 

I meet an problem, i update my provider service, but the dubbo-go still try to make connection with old provider address.

the old ip address is different with new ip.

After i update my service:

Dubbo-go still visits the old address as shown in first picture .

I can only restart the service measured by dubbo-go to restore.

**Comment by welcome112s** [comment]
i hava the same   problem

**Comment by wenxuwan** [comment]
> i hava the same problem

I will try to fix the problem
