### ISSUE TITLE
Imp: some improvements need to do in v1.5.

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go#661]
**What would you like to be added**:

1 delete the github.com/aliyun/aliyun-oss-go-sdk / github.com/baiyubin/aliyun-sts-go-sdk in the go.mod, which are useless.
2 "Apache Dubbo Go" should be  "Apache Dubbo-go" in NOTICE.
3 pls add "nolint" for EventType.String() and Event.String() remoting/listener.go.
4 Pls add comment for registry/servicediscovery/synthesizer/subscribed_urls_ synthesizer.go:SubscribedURLsSynthesizer.
5 Pls add comment or "nolint" for SequenceType and DubboPackage in protocol/dubbo/codec.go.
6 change the wrong word "dncode" in comment of protocol/dubbo/codec.go:DubboPackage.Unmarshal.
7 Pls add comment or "nolint" for GrpcExporter in protocol/grpc/grpc_exporter.go.
8 Pls add comment or "nolint" for all structs/funcs in protocol/grpc/grpc_invoker.go.
9 Pls add comment or "nolint" for struct Requst in protocol/jsonrpc/http.go.
10 Pls add comment or "nolint" for var Version in protocol/jsonrpc/json.go.
11 Pls add comments for func GetProtocol and FilterInvoker and its funcs in protocol/protocolwrapper/protocol_filter_wrapper.go.
12 Pls add comment or "nolint" for all structs/funcs in protocol/rest/config/rest_config.go.
13 Pls add comment or "nolint" for all structs/funcs in protocol/rest/rest_exporter.go.
14 Pls add comment or "nolint" for all structs/funcs in protocol/rest/rest_invoker.go.
15 Pls add comment or "nolint" for all structs/funcs in protocol/rest/rest_protocol.go.
16 Pls add comment or "nolint" for const FixedWindowKey in filter/filter_impl/tps/tps_limit_fix_window_stategy.go
17 Pls split the import block in filter/filter_impl/tps/tps_limit_strategy_mock.go.
18 Pls add comments  or "nolint" for consts in filter/filter_impl/access_log_filter.go.
19 Pls add comments  or "nolint" for func GetFilter() in filter/filter_impl/echo_filter.go.
20 Pls add comments  or "nolint" for struct ExecuteState in filter/filter_impl/execute_limit_filter.go.
21 Pls add comments  or "nolint" for struct GenericFilter in filter/filter_impl/generic_filter.go.
22 Pls add comments  or "nolint" for all consts/funcs/vars in filter/filter_impl/generic_service_filter.go.
23 Pls add comments  or "nolint" for struct GenericFilter in filter/filter_impl/generic_service_filter_test.go.
24 Pls add comments  or "nolint" for consts in filter/filter_impl/hystrix_filter.go.
25 Pls add comments  or "nolint" for consts in filter/filter_impl/token_filter.go.
26 Pls merge the third/forth import block in filter/filter_impl/tracing_filter_test.go.
27 Pls add comment for apolloConfigurationFactory.GetDynamicConfiguration() in config_center/apollo/factory.go.
28 Pls add comments for consts/vars/funcs in config_center_parser/configuration_parser.go.
29 Pls add comment for struct CacheListener in config_center/zookeeper/listener.go.
30 Pls add comment for struct MockDynamicConfigurationFactory/MockDynamicConfiguration/MockDynamicConfiguration.MockServiceConfigEvent/MockDynamicConfiguration.MockApplicationConfigEvent in config_center/mock_dynamic_config.go.
31 Pls add comment for MethodConfig in config/method_config.go.
32 Pls add "nolint" for consts in common/constant/env.go.
33 Pls add "nolint" for broadcastClusterInvoker.Invoke in cluster/cluser_impl/broadcast_cluster_invoker.go.
34 Pls add comment for broadcastCluster.Join in cluster/cluser_impl/broadcast_cluster.go.
35 Pls add "nolint" for failbackClusterInvoker.Invoke in cluster/cluser_impl/failback_cluster_invoker.go.
36 Pls add comment for failbackCluster.Join in cluster/cluser_impl/failback_cluster.go.
37 Pls add "nolint" for failfastClusterInvoker.Invoke in cluster/cluser_impl/failfast_cluster_invoker.go.
38 Pls add comment for failfastCluster.Join in cluster/cluser_impl/failfast_cluster.go.
39 Pls add "nolint" for failoverClusterInvoker.Invoke in cluster/cluser_impl/failover_cluster_invoker.go.
41 Pls add "nolint" for vars/funcs/structs in cluster/cluser_impl/failover_cluster_test.go.
42 Pls add comment for failoverCluster.Join in cluster/cluser_impl/failover_cluster.go.
43 Pls add "nolint" for failsafeClusterInvoker.Invoke in cluster/cluser_impl/failsafe_cluster_invoker.go.
44 Pls add comment for failsafeCluster.Join in cluster/cluser_impl/failsafe_cluster.go.
45 Pls add "nolint" for forkingClusterInvoker.Invoke in cluster/cluser_impl/forking_cluster_invoker.go.
46 Pls add comment for forkingCluster.Join in cluster/cluser_impl/forking_cluster.go.
47 Pls add "nolint" for mockCluster.Join in cluster/cluser_impl/mock_cluster.go.
48 Pls add "nolint" for registryAwareClusterInvoker.Invoke in cluster/cluser_impl/registry_aware_cluster_invoker.go.
49 Pls add comment or "nolint" for registryAwareCluster.Join in cluster/cluser_impl/registry_aware_cluster.go.
50 Pls add "nolint" for contants in cluster/loadbalance/consistent_hash.go.
51 Pls add comment for leastActiveLoadBalance.Select in cluster/loadbalance/least_active.go.
52 Pls add "nolint" for contants in cluster/loadbalance/round_robin.go.
53 Pls add "nolint" for structs/funcs in cluster/router/healthcheck/fatory_test.go.
54 Pls add comment for struts/funcs in cluster/router/tag/tag_router.go.

**Comment by Howie66** [comment]
i will do this

**Comment by AlexStocks** [comment]
> i will do this

Thank u. Pls fork the github.com/apache/dubbo-go from its develop branch. After u finish this task, pls submit ur pr to the develop branch too.

And What's more, pls let me know the deadline of ur plan to finish this task.
