### ISSUE TITLE
hystrix filter initHystrixConfigProvider incorrect

### ISSUE THREAD

**Issue by seasidesky** [apache/dubbo-go#666]
**What happened**:
https://github.com/apache/dubbo-go/blob/master/filter/filter_impl/hystrix_filter.go#L237
```
filterConfig := config.GetConsumerConfig().FilterConf.(map[interface{}]interface{})[HYSTRIX]
```
there is a misuse of config.GetConsumerConfig()

**What you expected to happen**:
https://github.com/apache/dubbo-go/blob/master/filter/filter_impl/hystrix_filter.go#L237
is expected to like this
```
filterConfig := config.GetProviderConfig().FilterConf.(map[interface{}]interface{})[HYSTRIX]
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by hxmhlt** [comment]
Hi，Hystrix is a fuse solution. As we know, fuses are defined on the consumer side, because fusing is an active protection from the perspective of the client.

**Comment by seasidesky** [comment]
I got it, but https://github.com/apache/dubbo-go/blob/master/filter/filter_impl/hystrix_filter.go#L234 and https://github.com/apache/dubbo-go/blob/master/filter/filter_impl/hystrix_filter.go#L237 is a little confusing.

as https://github.com/apache/dubbo-go/blob/master/filter/filter_impl/hystrix_filter.go#L237
```
if config.GetProviderConfig().FilterConf == nil
```

**Comment by zouyx** [comment]
the same to #710

**Comment by YGrylls** [comment]
@seasidesky Thank you for mention this. Yes, this is a known bug. Will be fixed this weekend and included in the next release at about mid September. #710
