### ISSUE TITLE
Fix: panic when function args list is empty

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go#67]
![image](https://user-images.githubusercontent.com/7959374/58848837-8e3e5700-86ba-11e9-84ea-7f3089a62cc9.png)
It should not panic when the function args list is empty.

**Comment by fangyincheng** [comment]
this issue include these cases:
1. args list is empty
2. returns list is empty
3. arg is nil
4. return nil(eg: need []interface{}{}, but return nil)

**Comment by pantianying** [comment]
test code:
```
	println("\n\n\nstart to test dubbo - GetUsers")
	ret1, err := conMap["com.ikurento.user.UserProvider"].GetRPCService().(*UserProvider).QueryDeviceStatus()
	if err != nil {
		panic(err)
	}
	println("response result: %v", ret1)
```
