### ISSUE TITLE
grpc protoc-gen-dubbo base.GetProxyImpl().Invoke(invo)

### ISSUE THREAD

**Issue by shijiebei2014** [apache/dubbo-go#675]
After generate the file by protoc-gen-dubbo, the error is that base.GetProxyImpl().Invoke(invo), the right should be that base.GetProxyImpl().Invoke(**context.TODO()**, invo)

**Comment by zouyx** [comment]
Any problems now?

**Comment by AlexStocks** [comment]
@watermelo

**Comment by zouyx** [comment]
There is no problem i think

https://github.com/apache/dubbo-go/blob/22107248cc73da8e01f540165dc4025d5234a738/protocol/grpc/protoc-gen-dubbo/plugin/dubbo/dubbo.go#L284
