### ISSUE TITLE
Bug: java-client can not get error message when go-server return error

### ISSUE THREAD

**Issue by chenleirr** [apache/dubbo-go#68]
My code is as follows

**go-server**
![image](https://user-images.githubusercontent.com/21357605/58855769-71624d80-86d3-11e9-98de-da8a5f2c5940.png)

**java-client**
![image](https://user-images.githubusercontent.com/21357605/58855859-b1c1cb80-86d3-11e9-885e-40e6e06918a4.png)

The problem  is that  exception  java catched  is not contain the go error message which should be ‘_invalid params: uid, name, cert could not be empty_’.

**In fact, java-client always catch as follows**:

Failed to invoke the method Init in the service com.xxx.service.go.base.certify.api.CertifyService. Tried 1 times of the providers [10.71.8.70:20001] (1/1) from the registry 10.71.8.70:2181 on the consumer 10.71.8.70 using the dubbo version 2.6.3. Last error is: Failed to invoke remote method: Init, provider: dubbo://10.71.8.70:20001/com.xxx.service.go.base.certify.api.CertifyService?anyhost=true&app.version=1.0&application=consumer-of-certify-app&category=providers&check=false&cluster=failover&dubbo=dubbo-provider-golang-2.6.0&environment=dev&group=&interface=com.xxx.service.go.base.certify.api.CertifyService&ip=192.168.99.1&loadbalance=random&methods=Init&methods.Init.loadbalance=random&methods.Init.retries=3&methods.Init.weight=0&module=dubbogo+certify+server&name=CertifyService&organization=test.com&owner=raychen&pid=71023&register.ip=10.71.8.70&remote.timestamp=1559621785&retries=0&service.filter=echo&side=consumer&timestamp=1559622450690&version=&warmup=100, cause: 0

**Comment by hxmhlt** [comment]
We can discuss in here.  @fangyincheng @wongoo

**Comment by hxmhlt** [comment]
related issue:  https://github.com/dubbogo/hessian2/issues/53

**Comment by hxmhlt** [comment]
Can we convert error in Go to exception in Java otherwise Golang developers have to register a java pojo 'Exception' in Java.  I think both error in Go & Exception in Java is basic type .

**Comment by fangyincheng** [comment]
Now, I think there are two ways: 
1. In hessian2, we can decode it as error when decoding a exception. 
2. RegisterPOJO! Define some Exception struct(eg: IOException、RemotingException etc.).  We can define a Exception struct named Exception, and then, users need to define their own XxxException. But many exception class of java SDK will must be define by users.

What do you think?

**Comment by hxmhlt** [comment]
May we can do both. User can define the java exception mojo in go and register it. Also we can provide POJOs that are often used instead of all of them. If Hessian2 finds neither the standard POJO corresponding to exception nor the user-defined-registered one, then Hessian2 can decode exception as `error` in go through the rules we define.
