### ISSUE TITLE
Error when do command go fmt 

### ISSUE THREAD

**Issue by Patrick0308** [apache/dubbo-go#682]
**What happened**:
When do `go fmt ./... && [[ -z `git status -s` ]]` will error
![image](https://user-images.githubusercontent.com/5486149/88919492-c41aa380-d29d-11ea-8d9a-8bf38d87804b.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by AlexStocks** [comment]
cc @gaoxinge

**Comment by gaoxinge** [comment]
我暂时无法在下面的环境下重现这个问题：

- 操作系统：windows 10
- golang版本：1.33
- 代码：https://github.com/apache/dubbo-go
- 分支：develop

我看你的报错里面访问了库，这个库在go mod中缓存`pkg/mod/cache/vcs`里面，要不清除go mod的缓存试一下。

@Patrick0308

**Comment by gaoxinge** [comment]
调查了一下这个报错，得到以下结果：

- 不知道为什么我的电脑上能跑，照理来说应该也会报错，因为我也没有`bzr`命令，手动狗头
- `bzr`是类似`git`的版本控制工具。早期的`launchpad.net/gocheck`是基于`bzr`管理的，根据[官网](https://launchpad.net/gocheck)的说法现在已经迁移到了github上，地址位于[go-check/check](https://github.com/go-check/check)上
- [hashicorp/consul/blob/v1.8.0/go.mod](https://github.com/hashicorp/consul/blob/v1.8.0/go.mod#L9)自身也使用`replace`把`bzr`替换成了`git`的版本

结论：

- @Patrick0308 你有空帮我测一下下面的命令在你本地能不能跑：

```shell
go mod edit -replace launchpad.net/gocheck=github.com/go-check/check@v0.0.0-20140225173054-eb6ee6f84d0a
go mod tidy 
go mod vendor
```
- 我先在 https://github.com/apache/dubbo-go/pull/702 里面把这个问题使用`replace`的方式fix掉

**Comment by gaoxinge** [comment]
I have fixed this issue in https://github.com/apache/dubbo-go/pull/702.
