### ISSUE TITLE
替代springcloud gateway中的一个微服务

### ISSUE THREAD

**Issue by duanzonglong** [apache/dubbo-go#684]
**What would you like to be added**:当前dubbo已经实现了rest协议是否能代替springcloud gateway中的一个微服务

**Why is this needed**:需要将springcloud中的微服务项目逐渐的go语言化，不能无缝迁移前，只能先每个微服务dubbo化。

**Comment by zouyx** [comment]
> **What would you like to be added**:当前dubbo已经实现了rest协议是否能代替springcloud gateway中的一个微服务
> 
> **Why is this needed**:需要将springcloud中的微服务项目逐渐的go语言化，不能无缝迁移前，只能先每个微服务dubbo化。

You want replace the gateway of `springcloud` ? or a micro service in `springcloud`?

If a micro service in `springcloud`, i think is ok.

**Comment by DogBaoBao** [comment]
I think rest protocol can do this. Others I plan the dubbogoproxy in the next days can do this too.

**Comment by PhilYue** [comment]
Mark！
