### ISSUE TITLE
Reference Interface return value

### ISSUE THREAD

**Issue by legend9999** [apache/dubbo-go#699]
**What happened**:
func (u *UserProvider) Reference() string {
	return "UserProvider"
}

在官方例子中，Reference是必须要实现的接口，但在github.com/apache/dubbo-go@v1.4.1/common/rpc_service.go:299中会判断是否有第二个返回值，但这个接口不能有两个返回值 ，打印出大量的警告日志

**Comment by zouyx** [comment]
Got it ,i will check this problem in this few days

**Comment by fangyincheng** [comment]
Logs are used to prompt functions that do not meet the conditions. I think some default interface methods can be filtered.
@zouyx
