### ISSUE TITLE
幻科

### ISSUE THREAD

**Issue by legend9999** [apache/dubbo-go#700]
* 组织：幻科
* 地点：中国北京
* 联系方式：
* 场景：新技术选项期

**Comment by AlexStocks** [comment]
hi guy. thank u so much for ur appreciation. however, pls submit this info to github.com/apache/dubbo-go/issues/2 . thanks again.

**Comment by AlexStocks** [comment]
> * 组织：幻科
> * 地点：中国北京
> * 联系方式：
> * 场景：新技术选项期

 hi guy. thank u so much for ur appreciation. however, pls submit this info to https://github.com/apache/dubbo-go/issues/2 . thanks again.
