### ISSUE TITLE
出参是基本类型要怎么写

### ISSUE THREAD

**Issue by iamhyz** [apache/dubbo-go#706]
本人搞java的，go不太懂。有没有大佬教一下，如果响应是String，这句 hessian.RegisterPOJO(&User{}) 要改成啥？

**Comment by zouyx** [comment]
> 本人搞java的，go不太懂。有没有大佬教一下，如果响应是String，这句 hessian.RegisterPOJO(&User{}) 要改成啥？

`String` only or `String` in entity?

**Comment by iamhyz** [comment]
> `String` only

String only

**Comment by AlexStocks** [comment]
cc @fangyincheng 

这是个好问题，我是不是需要在 dubbo-go-hessian2 里面内之下 java Sting/Integer 等基本 class 的实现？

**Comment by fangyincheng** [comment]
string不需要registrypojo，默认已经支持了的

**Comment by zouyx** [comment]
@iamhyz any problems？
