### ISSUE TITLE
initHystrixConfigProvider初始化错误

### ISSUE THREAD

**Issue by whitekeyboard** [apache/dubbo-go#710]
**What happened**:

[dubbo-go/filter/filter_impl/hystrix_filter.go ]

func initHystrixConfigProvider() error {
	if config.GetProviderConfig().FilterConf == nil {
		return perrors.Errorf("no config for hystrix")
	}
	filterConfig := config.**GetConsumerConfig**().FilterConf.(map[interface{}]interface{})[HYSTRIX]

**What you expected to happen**:
如上，initHystrixConfigProvider函数初始化会出错，此处是否调用错误，initHystrixConfigProvider应该调用config.GetProviderConfig().FilterConf.(map[interface{}]interface{})[HYSTRIX]才对的吧

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by AlexStocks** [comment]
@whitekeyboard would u pls submit a pr?

**Comment by whitekeyboard** [comment]
@AlexStocks  just a normal developer, and find this bug , is it a BUG???

**Comment by AlexStocks** [comment]
@whitekeyboard would u pls submit a pr?

**Comment by hxmhlt** [comment]
@whitekeyboard It is not a BUG. Hystirx should read config in ConsumerConfig. Pls configure in ConsumerConfig with your consumer application.

**Comment by whitekeyboard** [comment]
@hxmhlt as Provder ，init to cal;l initHystrixConfigProvider, and initHystrixConfigProvider to call **ConsumerConfig**, not to call **GetProviderConfig**?????

**Comment by whitekeyboard** [comment]
@AlexStocks @hxmhlt 此处初始化提供者（initHystrixConfigProvider），实现中为啥要获取消费者的配置，（config.GetConsumerConfig()）此处个人感觉不是太合理啊。如果本身只是作为提供者，这此处没有消费者配置，这样处理不太对吧？

**Comment by hxmhlt** [comment]
@YGrylls

**Comment by hxmhlt** [comment]
Is this a bug ? @YGrylls 
![image](https://user-images.githubusercontent.com/13016899/91129127-08059a80-e6dc-11ea-9dee-e84510dfefc7.png)

**Comment by YGrylls** [comment]
Yes, it's a bug. My bad. **GetProviderConfig()** should be called here. @whitekeyboard A pr is welcome, or let me fix this this weekend

**Comment by whitekeyboard** [comment]
@YGrylls ths!

**Comment by zouyx** [comment]
#666
