### ISSUE TITLE
dubbo-go对接配置中心，是否支持自定义配置

### ISSUE THREAD

**Issue by whitekeyboard** [apache/dubbo-go#712]
1、dubbo-go对接配置中心，修改provider或者consumer的配置，都是dubbo-go的配置
2、新增自定义的配置，以及对接配置中心，是否需要自己实实现？如果dubbo-go不支持，这个功能是否可以在后续功能中加入。

**Comment by zouyx** [comment]
> 1、dubbo-go对接配置中心，修改provider或者consumer的配置，都是dubbo-go的配置
> 2、新增自定义的配置，以及对接配置中心，是否需要自己实实现？如果dubbo-go不支持，这个功能是否可以在后续功能中加入。

1. Correct
2. Can you provide your sence clearly?
For if you want to use custom configuration and your configuration center is zookeeper, do something as below.

* Extends `ConfigurationListener` and inject into DynamicConfiguration
https://github.com/apache/dubbo-go/blob/aaa8be31fea3c0fe7ebbc1247cb273e74eaeb83b/config_center/zookeeper/impl_test.go#L204

Now you can get your custom configuration in dubbo-go

Or you can make a new `zookeeper` client for this requirement.

**Comment by whitekeyboard** [comment]
ths
