### ISSUE TITLE
go-hessian2报错 error:decObject illegal object type tag:121 请求帮助

### ISSUE THREAD

**Issue by jjhewlett** [apache/dubbo-go#717]
go-hessian2报错 error:decObject illegal object type tag:121

我是Java服务端，dubbo-go是客户端。
现在Data是java下发的一个List，list里每一个元素，都是实体对象
下发单个没问题，下发list的就go-hessian2抛异常

hessian.RegisterPOJO(&ResponseData{})
type ResponseData struct {
	Code string
	Msg  string
	Data interface{}
}

**Comment by jjhewlett** [comment]
hessian.RegisterPOJO(&ResponseData{})
我的DATA是一个JAVA泛型

**Comment by jjhewlett** [comment]
@AlexStocks

**Comment by jjhewlett** [comment]
@wongoo

**Comment by AlexStocks** [comment]
u have submit the same question as https://github.com/apache/dubbo-go-hessian2/issues/220.

**Comment by jjhewlett** [comment]
@wongoo 我都已经定义了。
![image](https://user-images.githubusercontent.com/69667512/90460790-3fea6c00-e137-11ea-873e-8a000f5a9ba9.png)
