### ISSUE TITLE
support default config, config in code, and config from command line parameterss

### ISSUE THREAD

**Issue by wongoo** [apache/dubbo-go#723]
**What would you like to be added**:

- support default config, minimal user config
- support config directly in code
- support load config from command line parameters

**Why is this needed**:
dubbogo now only support config from file, it's not friendly for debug. 
And I'd like to compile code to one binary file to deploy, not need to add some other config file. 
Command line parameters is easy to add for some environment, while config file not.

**Comment by AlexStocks** [comment]
@wongoo maybe u should discuss with @cvictory who wanna add the API funcs for startup.

**Comment by AlexStocks** [comment]
“support default config, minimal user config” 
cc @fangyincheng
