### ISSUE TITLE
泛化调用支持jsonrpc协议吗？

### ISSUE THREAD

**Issue by whitekeyboard** [apache/dubbo-go#728]
泛化调用使用dubbo协议时，可以正常通信；当使用jsonrpc协议的时候，总是报以下错误：
`2020-08-25T10:12:41.813+0800	ERROR	filter_impl/generic_service_filter.go:95	[Generic Service Filter] wrong serialization`
泛化调用只支持dubbo协议吗？？

**Comment by zouyx** [comment]
could you provide your case？

**Comment by whitekeyboard** [comment]
@zouyx  我使用的是如下的示例：
1、https://github.com/apache/dubbo-samples/tree/master/golang/generic
2、将此示例中的dubbo协议更换为jsonrpc，验证时，go-server端总是报如下错误，和警告
`2020-08-25T10:12:41.813+0800 ERROR filter_impl/generic_service_filter.go:95 [Generic Service Filter] wrong serialization
 2020-08-26T09:00:46.012+0800	WARN	jsonrpc/server.go:125	[ReadRequest] error: EOF
`

**Comment by fangyincheng** [comment]
当前的泛化实现只支持了hessian，见https://github.com/apache/dubbo-go/blob/master/filter/filter_impl/generic_service_filter.go

**Comment by whitekeyboard** [comment]
@fangyincheng 意思底层通信协议只能支持dubbo???如果不支持，建议后续增加以下如jsonrp等以及其他协议的支持，本身这个应该是对于上层不感知，可以相互配置。这样支持应该比较好！！！

**Comment by whitekeyboard** [comment]
而且从使用的角度来说，一个server端配置了jsonrpc，则客户端只能使用标准的rpc方式调用，泛化调用的客户端就无法使用，这样的应用场景下，就必须强制使用dubbo协议了。这样看来jsonrpc等其他协议的使用限制太多了。

**Comment by whitekeyboard** [comment]
@fangyincheng @zouyx 按照我的理解hessian应该不属于序列化协议吧？既然可以支持dubbo，是否也可以支持其他的协议，如jsonrpc等？？？

**Comment by fangyincheng** [comment]
> @fangyincheng @zouyx 按照我的理解hessian应该不属于序列化协议吧？既然可以支持dubbo，是否也可以支持其他的协议，如jsonrpc等？？？

泛化的实现归根结底只是客户端和服务端的两个filter分别做了适应，理论上是可以添加其他协议支持的。在filter的支持下，dubbo-go是允许用户自定义filter并通过配置引入的。比如替换generic_filter.go 和generic_service_filter.go

**Comment by whitekeyboard** [comment]
@fangyincheng 那是否可以帮忙看一下我说的问题？多谢！
