### ISSUE TITLE
registry为service-discovery与nacos、zookeeper有啥区别和关联

### ISSUE THREAD

**Issue by whitekeyboard** [apache/dubbo-go#745]
```
https://github.com/apache/dubbo-samples/tree/master/golang/registry/servicediscovery/nacos
https://github.com/apache/dubbo-samples/tree/master/golang/registry/nacos
```
这两个例子，第一个事例，注册中心为service-discovery，service_discovery配置为nacos，第二个事例注册中心直接配置为nacos，
请问注册中心为service-discovery和，注册中心配置为nacos、zookeeper有啥区别？？

**Comment by watermelo** [comment]
区别在这里 https://github.com/apache/dubbo-samples/blob/master/golang/registry/servicediscovery/nacos/go-client/app/client.go#L50，service-discovery 是应用级注册的例子。

**Comment by whitekeyboard** [comment]
@watermelo 我看了一下啊，还是没太明白你的意思？？？我看示例的调用没太大区别，区别主要就是配置中心的配置不同？所以感觉还是懵懵懂懂的

**Comment by watermelo** [comment]
@whitekeyboard  https://github.com/apache/dubbo-samples/blob/master/golang/registry/servicediscovery/nacos/go-client/app/client.go#L50  的 `init` 方法，会将 `newServiceDiscoveryRegistry` 方法注册到 registry extension 扩展。
你运行一下例子就能看到区别了。调用顺序如下
```
1. config.Load()
2. loadProviderConfig()
3. config.(*ServiceConfig).Export
4. registry/protocol.(*registryProtocol).Export
5. registry/protocol.getRegistry
6. extension.GetRegistr
7. registry/servicediscovery.newServiceDiscoveryRegistry   // init 注册到 extension 的方法
```
如果后续没有其他问题，将关闭这个 issue
