### ISSUE TITLE
i hope dubbo.comsumer.xml & dubbo.provider.xml read from remote configCenter,not only local 

### ISSUE THREAD

**Issue by thinmonkey** [apache/dubbo-go#76]
func consumerInit(confConFile string) error {
	if confConFile == "" {
		return perrors.Errorf("application configure(consumer) file name is nil")
	}
	if path.Ext(confConFile) != ".yml" {
		return perrors.Errorf("application configure file name{%v} suffix must be .yml", confConFile)
	}
        // when configCenter is apollo,configfile is remote config,can't read config.So hope provider read config through http.
	confFileStream, err := ioutil.ReadFile(confConFile)
	if err != nil {
		return perrors.Errorf("ioutil.ReadFile(file:%s) = error:%v", confConFile, perrors.WithStack(err))
	}
	consumerConfig = &ConsumerConfig{}
	err = yaml.Unmarshal(confFileStream, consumerConfig)
	if err != nil {
		return perrors.Errorf("yaml.Unmarshal() = error:%v", perrors.WithStack(err))
	}
        xxx
}

我们的服务运行在docker里，配置中心是携程的apollo。配置内容在配置中心上，通过配置中心来区分环境的。这里初始化直接读取本地的文件，实际上用不了。建议能够初始化时读取远程配置中心的配置，例如：apollo,etcd。

**Comment by hxmhlt** [comment]
@thinmonkey  I'm writing the code for the configuration center. But zookeeper needs to be supported as the configuration center first , then the apollo, etcd and so on. If you are interested and have time, you can participate in the code contribution of the configuration center module.

**Comment by thinmonkey** [comment]
oh，how can i participate in the code contribution ?

**Comment by hxmhlt** [comment]
@thinmonkey Join the ding talk group(钉钉群) :23331795

**Comment by hxmhlt** [comment]
@thinmonkey Hi, the good news is that dubbo-go now supports getting bootstrap configurations from third-party configuration center, and can also use third-party configuration center as service management configurator.
Now there is a complete implementation of zookeeper as a third-party configuration center. Has this met your needs? If not ,let me know if you want to write the other third-party configuration center such as apollo . （All the logic of getting configuration at startup has been completed. You just need to implement the interface according to the dynamic configuration interface definition as follow.

`
type DynamicConfiguration interface {
	Parser() parser.ConfigurationParser
	SetParser(parser.ConfigurationParser)
	AddListener(string, ConfigurationListener, ...Option)
	RemoveListener(string, ConfigurationListener, ...Option)
	GetConfig(string, ...Option) (string, error)
	GetConfigs(string, ...Option) (string, error)
}
`

**Comment by AlexStocks** [comment]
@thinmonkey pls watch this pr [pull/240](https://github.com/apache/dubbo-go/pull/240)

**Comment by zouyx** [comment]
@fangyincheng  should it close?

**Comment by hxmhlt** [comment]
Resolved and I will close the issue.
