### ISSUE TITLE
merge package import 

### ISSUE THREAD

**Issue by songjiayang** [apache/dubbo-go#762]
**What happened**:

 import  with multiple times, for example https://github.com/apache/dubbo-go/blob/master/config_center/configurator/override_test.go#L19

```golang
import (
	"testing"
)

import (
	"github.com/stretchr/testify/assert"
)

import (
	"github.com/apache/dubbo-go/common"
	"github.com/apache/dubbo-go/common/constant"
	"github.com/apache/dubbo-go/common/extension"
)
```

**What you expected to happen**:
import once, after refactor:

```golang
import (
	"testing"

        "github.com/stretchr/testify/assert"

        "github.com/apache/dubbo-go/common"
	"github.com/apache/dubbo-go/common/constant"
	"github.com/apache/dubbo-go/common/extension"
)
```

The rules to follow:

1. import once.
2. different section with blank line.
3. system library import first, then third party, internal last.

**Comment by AlexStocks** [comment]
thx for ur suggestions. this code format is dubbo-go coding style.
