### ISSUE TITLE
【optimize】optimize url params default value is "" 

### ISSUE THREAD

**Issue by christophe-liwei** [apache/dubbo-go#768]
```
type baseUrl struct {
	Protocol     string
	Location     string // ip+port
	Ip           string
	Port         string
	params       url.Values
	PrimitiveURL string
}

```

dubbo-go在构建URL的时候`params`属性使用的是go sdk 的net.url.url.Values。他的Set方法没有校验插入的value值是否为空串“”，如下

```
func (v Values) Set(key, value string) {
	v[key] = []string{value}
}

```

这样导致两个问题：

1. 和dubbo互通时由于dubbo在没有配置group和verison的时候不在注册中心添加group、verison（使用的是StringBuilder拼），这种情况下dubbo-go由于url中的`group=""`无法通过dubbo 订阅url时的校验，而导致dubbo不能调用dubbo-go

2. 缺省的配置是`“”`时没有必要向注册中心上报，这样导致url变长。增加了注册中心的压力。如果消费者没有获取到该项配置，可以通过`url.GetParam(key,default)`获取缺省配置。减小注册中心压力

**Comment by AlexStocks** [comment]
@hongfan @hequn

**Comment by AlexStocks** [comment]
@hongfan @hequn
