### ISSUE TITLE
registry为service-discovery时，修改配置文件端口为20003后，多出一个20000的监听端口

### ISSUE THREAD

**Issue by whitekeyboard** [apache/dubbo-go#774]
如以下示例中
”https://github.com/apache/dubbo-samples/tree/master/golang/registry/servicediscovery/nacos/go-server”
如果将配置文件的监听端口20000改为20003后，运行发现，20000和20003都会监听，看代码
tryInitMetadataService ->  (exporter *MetadataServiceExporter) Export() ，此处的Export函数会设置默认的端口为20000，此处有两个疑问：
1. 对于注册中心为service-discovery，此处的Export函数，会监听默认的20000，如果20000是特殊用处，则这个参数应该动态可配置的吧，否则同一台主机，多个不同服务启动的时候，不是只有一个20000能使用吗？
2. 如果此20000是为了配置文件中没有配置监听端口时，默认监听使用，那当前配置了监听端口20003，依然会监听20000，这样应该不合理吧？
请帮忙解答一下

**Comment by AlexStocks** [comment]
cc [sanxun](https://github.com/sanxun0325)

**Comment by sanxun0325** [comment]
i will solve it

**Comment by AlexStocks** [comment]
has been fixed at [pr 784](https://github.com/apache/dubbo-go/pull/784)
