### ISSUE TITLE
go-client直连dubbo java-server  遇到的奇怪问题

### ISSUE THREAD

**Issue by milerL** [apache/dubbo-go#783]
这是配置go-client 配置

references:
  "UserGoService":
    interface : "com.jjl.dxz.module.user.service.UserGoService"
    url: "dubbo://192.168.26.111:21782"
    group: "dxz"
    version: "1.0.0"
    methods :
    - name: "FindById"
      retries: 3

调试时 发现一个奇怪的问题 
系统返回报错
java exception:org.apache.dubbo.remoting.RemotingException: Not found exported service: dxz/UserGoService:1.0.0:21782 in[dxz/com.jjl.dxz.module.user.service.UserGoService:1.0.0:21782]

我这边是 dxz/UserGoService:1.0.0:21782
java-server的是 dxz/com.jjl.dxz.module.user.service.UserGoService:1.0.0:21782

java-server 从spring dubbo升级了两次到现在的 springcloud dubbo

为什么对方的是 com.jjl.dxz.module.user.service.UserGoService
我的是UserGoService

**Comment by milerL** [comment]
补充
dubbo 官方文档 说明注册服务时是这样的
Register: dubbo://192.168.99.1:20880/com.alibaba.dubbo.samples.api.GreetingService?anyhost=true&application=dubbo-annotation-provider&default.timeout=1000&dubbo=2.6.2&generic=false&interface=com.alibaba.dubbo.samples.api

但是我调用的接口是这样的
dubbo://192.168.26.111:21782/UserGoService?app.version=1.0.0&application=DXZ-user-service&async=false&bean.name=UserGoService&cluster=&environment=dev&generic=false&group=dxz&interface=com.jjl.dxz.module.user.service.UserGoService&loadbalance=&methods.FindById.loadbalance=&methods.FindById.retries=3&methods.FindById.sticky=false&module=dubbogo+user-info+client&name=DXZ-user-service&organization=user.dxzjjl.com&owner=ZX&provided-by=&reference.filter=cshutdown&registry.role=0&release=dubbo-golang-1.3.0&retries=&side=consumer&sticky=false&timestamp=1601450721&version=1.0.0


我在/protocol/dubbo_protocol.go 86行
强制修改url.Path="/com.jjl.dxz.module.user.service.UserGoService"

就可以了

**Comment by milerL** [comment]
com.jjl.dxz.module.user.service.UserGoService
这个值是我的 interface参数

**Comment by hxmhlt** [comment]
你在go client写的UserGoService，实现的JavaClassName方法返回的字符串是否正确？

**Comment by milerL** [comment]
> 你在客户端写的UserGoService，实现的JavaClassName方法返回的字符串是否正确？

修改了url.path 以后是正常的

**Comment by milerL** [comment]
> 你在客户端写的UserGoService，实现的JavaClassName方法返回的字符串是否正确？

返回的字符串没问题

**Comment by AlexStocks** [comment]
@lizhixin
