### ISSUE TITLE
nacos 服务名相关问题

### ISSUE THREAD

**Issue by milerL** [apache/dubbo-go#785]
我是go client端
对方是 java server端  是spring cloud

对方向nacos注册服务 并修改注册的服务名为 userProviders
在nacos页面中展示出来的服务名也就是 userProviders

但是我只接触过
providers:com.test.module.service.UserService:1.0.0
这种

如果服务名只是userProviders
我该怎么配置？

**Comment by milerL** [comment]
对方修改服务名的方式，是直接改的配置文件
spring:
   application:
        name: userProviders

**Comment by AlexStocks** [comment]
this issue has no feedback in such a long time. so closed it now.
