### ISSUE TITLE
Get v1.5.2 failed

### ISSUE THREAD

**Issue by kennethkongiw** [apache/dubbo-go#789]
Execute the command `go get github.com/apache/dubbo-go@v1.5.2` then got the following result.

![image](https://user-images.githubusercontent.com/13694747/96033645-f007f700-0e92-11eb-9a63-5fc63ef6dc46.png)

**Comment by zouyx** [comment]
> Execute the command `go get github.com/apache/dubbo-go@v1.5.2` then got the following result.
> 
> ![image](https://user-images.githubusercontent.com/13694747/96033645-f007f700-0e92-11eb-9a63-5fc63ef6dc46.png)

That‘s a problem, i will fix it today.

**Comment by zouyx** [comment]
@kennethkongiw I have created a new version which is called [v1.5.3](https://github.com/apache/dubbo-go/releases/tag/v1.5.3) . v1.5.2 has discard, try again pls.

Here is integration test report : https://travis-ci.org/github/apache/dubbo-go-samples/builds/736242126

**Comment by kennethkongiw** [comment]
nice, it works.
