### ISSUE TITLE
sentinel-golang error on windows

### ISSUE THREAD

**Issue by kennethkongiw** [apache/dubbo-go#795]
dubbo-go version: v1.5.3

**github.com/alibaba/sentinel-golang** depends on **github.com/shirou/gopsutil**, but  the **load.Avg()** method of it  is not implemented on windows, resulting the following error after init.

![image](https://user-images.githubusercontent.com/13694747/96242221-cc999500-0fd5-11eb-8d87-b23cf2e845a3.png)

![image](https://user-images.githubusercontent.com/13694747/96242319-edfa8100-0fd5-11eb-8ac9-efb5167fd3ee.png)

**Comment by sanxun0325** [comment]
@kennethkongiw Yes, sentinel-golang currently uses gopsutil, and gopsutil doesn't support windows load yet. 
sentinel-golang is working on a solution.
