### ISSUE TITLE
Usage Problem: sprintboot communication with dubbogo

### ISSUE THREAD

**Issue by wghdir** [apache/dubbo-go#796]
怎么在java上的服务名多了两个点，用的dubbo-spring-boot-starter 2.7.5,java的客户端调不到go的服务端，java之间是可以调用。希望能支持springboot,用官方的例子是可以互调的。
![image](https://user-images.githubusercontent.com/19346934/96325100-b502f080-1057-11eb-9bdc-7e095d715646.png)

**Comment by wghdir** [comment]
指定version及group已解决,我说怎么go的服务上没有：：，java的有，原来那是version同group
go的服务上加:
    version: "1.0.0"
    group: "wgh"
java的注解上加:
version = "1.0.0",group = "wgh"

**Comment by zouyx** [comment]
Provide registry center's name and version.

**Comment by AlexStocks** [comment]
dubbo java 向 nacos 和 dubbogo 向 nacos 注册时不统一。后来已经fix掉该问题，在1.5.6 中已经支持这两种方式。
