### ISSUE TITLE
Provider在注册中心无故消失

### ISSUE THREAD

**Issue by yeabow** [apache/dubbo-go#805]
我们测试环境，周末两天服务没有被调用，provider没有panic，日志输出：

![image](https://user-images.githubusercontent.com/2017715/97147169-0885e480-17a4-11eb-903d-2e06efb5546c.png)

重启服务后，consumer正常连接(前提是已修过provider重启导致consumer报No provider的问题)。

生产环境没有发现此问题。

dubbo-go 版本：1.5.0

**Comment by AlexStocks** [comment]
@yeabow pls check it using v1.5.3

**Comment by jack15083** [comment]
感觉跟我这个有点类似，不知道是不是用的zk作为注册中心  https://github.com/apache/dubbo-go/issues/956

**Comment by kzhan** [comment]
请问注册中心是什么，听说zk这货有点问题
