### ISSUE TITLE
升级go-zookeeper解决死锁问题

### ISSUE THREAD

**Issue by whitekeyboard** [apache/dubbo-go#810]
问题：zookeeper不断重启时，dubbo-go概率性会出现死锁的情况
解决：
本人在本地merge以下commiter后，此问题不复现
https://github.com/go-zookeeper/zk/commit/7f9aac4e7f04fa6cbcec019645f94480aa72d064
建议升级go-zookeeper v1.0.2版本修复此问题。
谢谢！

**Comment by AlexStocks** [comment]
cc @pantianying
