### ISSUE TITLE
initWatchSet存在死代码

### ISSUE THREAD

**Issue by whitekeyboard** [apache/dubbo-go#813]
https://github.com/apache/dubbo-go/blob/master/remoting/kubernetes/registry_controller.go ：Line 170
initWatchSet函数：
```
for ns := range c.needWatchedNamespace {
		pods, err := c.kc.CoreV1().Pods(ns).List(metav1.ListOptions{
			LabelSelector: req.String(),
		})
如上needWatchedNamespace 为空，此for循环永远无法进入。needWatchedNamespace 在initPodInformer赋值，而initPodInformer却在initWatchSet后执行。

```
newDubboRegistryController函数如下：
```
	if err := c.initWatchSet(); err != nil {
		return nil, perrors.WithMessage(err, "init watch set")
	}

	if err := c.initPodInformer(); err != nil {
		return nil, perrors.WithMessage(err, "init pod informer")
	}
```

不知道本人分析的是否准确？请帮忙确认一下！谢谢！

**Comment by sxllwx** [comment]
你说的是对的。我尽快提交PR fix这个bug. 

> 这个bug，应该不会影响到整体的运行。

**Comment by whitekeyboard** [comment]
这个我也不清楚是否影响K8S的功能。但是我使用https://github.com/apache/dubbo-samples/tree/master/golang/registry/kubernetes提供的镜像，基于dubbo-1.5.3重新编译后，发现无法运行。也不知道是否与此问题有关系。此示例也比较老了，是基于dubbo-go 1.3.0的。
我个人感觉K8S的代码可能还存在BUG，由于本人对此组件不太熟悉。尚不能说明问题原因。
建议此问题修复后，可以基于最新版本，提一下一下K8S镜像。
多谢！

**Comment by sxllwx** [comment]
The image has been updated based on [Commit](https://github.com/sxllwx/dubbo-go/commit/9d9a13a2bebad54aa4bcb87f01dcdf7134db8d05). You can use the latest image for testing. I have passed the test～

**Comment by sxllwx** [comment]
The image has been updated based on [Commit](https://github.com/sxllwx/dubbo-go/commit/9d9a13a2bebad54aa4bcb87f01dcdf7134db8d05). You can use the latest image for testing. I have passed the test.

> 这个我也不清楚是否影响K8S的功能。但是我使用[https://github.com/apache/dubbo-samples/tree/master/golang/registry/kubernetes提供的镜像，基于dubbo-1.5.3重新编译后，发现无法运行。也不知道是否与此问题有关系。此示例也比较老了，是基于dubbo-go](https://github.com/apache/dubbo-samples/tree/master/golang/registry/kubernetes%E6%8F%90%E4%BE%9B%E7%9A%84%E9%95%9C%E5%83%8F%EF%BC%8C%E5%9F%BA%E4%BA%8Edubbo-1.5.3%E9%87%8D%E6%96%B0%E7%BC%96%E8%AF%91%E5%90%8E%EF%BC%8C%E5%8F%91%E7%8E%B0%E6%97%A0%E6%B3%95%E8%BF%90%E8%A1%8C%E3%80%82%E4%B9%9F%E4%B8%8D%E7%9F%A5%E9%81%93%E6%98%AF%E5%90%A6%E4%B8%8E%E6%AD%A4%E9%97%AE%E9%A2%98%E6%9C%89%E5%85%B3%E7%B3%BB%E3%80%82%E6%AD%A4%E7%A4%BA%E4%BE%8B%E4%B9%9F%E6%AF%94%E8%BE%83%E8%80%81%E4%BA%86%EF%BC%8C%E6%98%AF%E5%9F%BA%E4%BA%8Edubbo-go) 1.3.0的。
> 我个人感觉K8S的代码可能还存在BUG，由于本人对此组件不太熟悉。尚不能说明问题原因。
> 建议此问题修复后，可以基于最新版本，提一下一下K8S镜像。
> 多谢！

The image has been updated based on [Commit](https://github.com/sxllwx/dubbo-go/commit/9d9a13a2bebad54aa4bcb87f01dcdf7134db8d05). You can use the latest image for testing. I have passed the test.

**Comment by AlexStocks** [comment]
@whitekeyboard pr [977](https://github.com/apache/dubbo-go/pull/977) has been merged into br develop. u can test it now.
