### ISSUE TITLE
[Enhancement] the cpu usage can be optimized when there is no invocation happened  

### ISSUE THREAD

**Issue by cvictory** [apache/dubbo-go#814]
![image](https://user-images.githubusercontent.com/4089452/97419510-1c1c8100-1945-11eb-8e29-567ab306051a.png)

more detail as follow: 
![image](https://user-images.githubusercontent.com/4089452/97419542-276fac80-1945-11eb-8094-3211b5a76542.png)

1. MayBe GetUrl should return pointer type.
2. To check the invoker is changed is very busy.

**Comment by zouyx** [comment]
Agree, i think rebuild cache should based on notification.

**Comment by zouyx** [comment]
What do you think? @AlexStocks @fangyincheng @hxmhlt

**Comment by cvictory** [comment]
Firstly I will optimize getUrl logic

**Comment by zouyx** [comment]
> Firstly I will optimize getUrl logic

It is ok
