### ISSUE TITLE
How to call the service of spring cloud

### ISSUE THREAD

**Issue by romantictravel01** [apache/dubbo-go#833]
**What would you like to be added**:
      Where are the examples
**Why is this needed**:
   I want to call the spring cloud service through Dubbo go

**Comment by zouyx** [comment]
There is not support call the spring cloud service .
Because there is some problems in go-client of eureka .

**Comment by zouyx** [comment]
Any question?

**Comment by AlexStocks** [comment]
dubbogo spring cloud client 无法保证数据一致性

**Comment by AlexStocks** [comment]
cc @Patrick0308 @chickenlj

**Comment by PhilYue** [comment]
Mark
