### ISSUE TITLE
Security:Incorrect conversion between integer types

### ISSUE THREAD

**Issue by zouyx** [apache/dubbo-go#839]
**What happened**:

**What you expected to happen**:

Fix the security problems as below:

![image](https://user-images.githubusercontent.com/3828072/98075659-bb8ec600-1ea7-11eb-9adc-b609e673dd32.png)

![image](https://user-images.githubusercontent.com/3828072/98075735-dbbe8500-1ea7-11eb-970b-3c1dc3489e8f.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by kedadiannao220** [comment]
may be i can do this......

**Comment by zouyx** [comment]
> may be i can do this......

thx
