### ISSUE TITLE
 Dynamic create go-client，without code like「javabean config code」 

### ISSUE THREAD

**Issue by pantianying** [apache/dubbo-go#85]
**What would you like to be added**:

在dubbo协议下，go-client能通过传入配置参数的形式实例化一个dubbo客户端。

**Why is this needed**:
当go-client调用dubbo接口时，必须代码实现一个javabean的描述。这个使业务端如果要动态调用十分不方便。
比如服务端新增了一个接口，客户单必须更改代码，不能通过更改配置实现。
比如go服务要做一个网关形式的服务，无法完成一些透传接口的工作
比如接口过多，go客户端将会需要很多代码描述。

**Comment by hxmhlt** [comment]
Is it means dubbo-go need  support generic reference like dubbo in consumer? @pantianying

**Comment by pantianying** [comment]
yes

**Comment by pantianying** [comment]
> Is it means dubbo-go need support generic reference like dubbo in consumer? @pantianying

yes
