### ISSUE TITLE
graceful exit

### ISSUE THREAD

**Issue by gaoxinge** [apache/dubbo-go#86]
https://github.com/apache/dubbo-go/blob/4f7ef9ddef1de6dc7cb121947357234a0202c056/examples/dubbo/go-server/app/server.go#L69-L90

**What would you like to be added**:

The code above may be placed in dubbo-go's code better than in user's code.

**Why is this needed**:

Does code above mean graceful exit? If this code is used frequently, we can move it to the dubbo-go's code so that users need not write it every time.

**Comment by hxmhlt** [comment]
ok, Sounds good. I think I need add the 'graceful exit' in task list.

**Comment by gaoxinge** [comment]
Link to https://github.com/apache/dubbo-go/issues/49.
