### ISSUE TITLE
泛化调用hessian解析map[int]int的问题

### ISSUE THREAD

**Issue by jack15083** [apache/dubbo-go#865]
**What happened**:
provider 
![image](https://user-images.githubusercontent.com/2142066/98635857-a52db200-2360-11eb-9bc6-fa8ef15fce16.png)
泛化调用返回
 {"<int Value>": 1001}
![image](https://user-images.githubusercontent.com/2142066/98635980-df974f00-2360-11eb-9905-fd183fc509a9.png)

**What you expected to happen**:
期望返回{1:1001}

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
dubbo-go version 1.5.1

**Comment by jack15083** [comment]
这里的代码问题，map会被强制转成map[string]interface{}
![image](https://user-images.githubusercontent.com/2142066/98657144-80473800-237c-11eb-8ac7-9f88be276640.png)

**Comment by fangyincheng** [comment]
这个map的case转换逻辑没有完善，这里应该是继续递归解析map的key和value
