### ISSUE TITLE
consumer的methodConfig能否添加一个方法名映射功能，解决go-client调用java-server方法名首字母大小写不一致的问题

### ISSUE THREAD

**Issue by rainbell** [apache/dubbo-go#869]
**What would you like to be added**: 如题（如果现在已经有了其它解决方案也请赐教）

**Why is this needed**: 新的go-client调原有的java服务，java规范方法名首字母都是小写，go对外暴露的方法名首字母则要求大写，希望增加一个配置能在go-client这边避免这个问题，不然个人理解需要在java端多包一套不符合规范命名的方法

**Comment by zouyx** [comment]
I think this is a good question. Reference #257

**Comment by zouyx** [comment]
Is it helpful?

**Comment by rainbell** [comment]
> Is it helpful?

yes, it works. Thanks!

**Comment by zouyx** [comment]
> > Is it helpful?
> 
> yes, it works. Thanks!

If no more questions, u can close this issue.
