### ISSUE TITLE
go-client调用java-server，java方法参数中有包装类型如Integer时无法正常调用

### ISSUE THREAD

**Issue by rainbell** [apache/dubbo-go#872]
如题。试了下对于Integer，传值和指针，java端decode出来的参数desc都不对。

**Comment by zouyx** [comment]
Reference : https://github.com/apache/dubbo-go-hessian2/issues/238

If no more questions , you can close this issue

**Comment by AlexStocks** [comment]
@zouyx maybe we can  reopen issue 238 and set it a label "good first issue"?

**Comment by zouyx** [comment]
> @zouyx maybe we can reopen issue 238 and set it a label "good first issue"?

I think keep this issue opening and relate to 238 is enough.
