### ISSUE TITLE
dubbogo 使用 grpc 协议暴露服务 在使用 nacos 作为 registries 的时候 报告 panic: service GrpcGreeterImpl export failed! err: Registry protocol new exporter error

### ISSUE THREAD

**Issue by kms9** [apache/dubbo-go#873]
dubbogo 使用 grpc 协议暴露服务 在使用 nacos 作为 registries 的时候

**What happened**:
注册服务失败  报告 
 panic: service GrpcGreeterImpl export failed! err: Registry protocol new exporter error

**What you expected to happen**:

注册服务成功  使用zookeeper可以注册成功

**How to reproduce it (as minimally and precisely as possible)**:

# dubbo server yaml configure file

# application config
application:
  organization : "zhiqu.com"
  name : "BDTService1"
  module : "dubbogo say-hello server"
  version : "0.0.1"
  owner : "ZX"
  environment : "dev"

registries :
  "nacos1":
    protocol: "nacos"
    timeout	: "3s"
    address: "127.0.0.1:8848"

services:
  "GrpcGreeterImpl":
    # 可以指定多个registry，使用逗号隔开;不指定默认向所有注册中心注册
    registry: "nacos1"
    protocol : "grpc"
    # 相当于dubbo.xml中的interface
    interface : "io.grpc.examples.helloworld.GreeterGrpc$IGreeter"
    loadbalance: "random"
    warmup: "100"
    cluster: "failover"
    methods:
    - name: "SayHello"
      retries: 1
      loadbalance: "random"
protocols:
  "grpc":
    name: "grpc"
    port: 20001

protocol_conf:
  grpc:
    session_number: 700
    session_timeout: "20s"
    getty_session_param:
      compress_encoding: false
      tcp_no_delay: true
      tcp_keep_alive: true
      keep_alive_period: "120s"
      tcp_r_buf_size: 262144
      tcp_w_buf_size: 65536
      pkg_rq_size: 1024
      pkg_wq_size: 512
      tcp_read_timeout: "1s"
      tcp_write_timeout: "5s"
      wait_timeout: "1s"
      max_msg_len: 1024
      session_name: "server"

**Anything else we need to know?**:

**Comment by LaurenceLiZhixin** [comment]
Nacos doesn't support special charactor like '$' in your interface field.
Pls change interface : "io.grpc.examples.helloworld.GreeterGrpc$IGreeter" in your config to interface : "io.grpc.examples.helloworld.GreeterGrpc.IGreeter".

**Comment by YeRuyi** [comment]
折磨我一晚上的东西原来在这查到了。。
