### ISSUE TITLE
config.Load()加载client.yml时偶尔会出现错误：fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by bonake** [apache/dubbo-go#884]
config.Load()加载client.yml时偶尔会出现如下错误：fatal error: concurrent map read and map write, 应该是内部使用map时的不安全调用引起的。
调用堆栈如下：
2020-11-19T18:12:48.718+0800	INFO	Connect to zookeeper successfully, name{zk registry}, zk address{127.0.0.1:2181}
fatal error: concurrent map iteration and map write

goroutine 25 [running]:
runtime.throw(0x46548ef, 0x26)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0002284d0 sp=0xc0002284a0 pc=0x403bf92
runtime.mapiternext(0xc000228578)
	/usr/local/go/src/runtime/map.go:853 +0x554 fp=0xc000228550 sp=0xc0002284d0 pc=0x4015b14
github.com/apache/dubbo-go/common.(*URL).RangeParams(0xc000228918, 0xc000228780)
	/Users/lizhh/Documents/prj/goexample/pkg/mod/github.com/apache/dubbo-go@v1.5.4/common/url.go:424 +0x91 fp=0xc0002285e8 sp=0xc000228550 pc=0x4427a51
github.com/apache/dubbo-go/registry.(*BaseRegistry).processURL(0xc000158140, 0xc0001e4c30, 0x5, 0x4640b86, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc000292630, ...)
	/Users/lizhh/Documents/prj/goexample/pkg/mod/github.com/apache/dubbo-go@v1.5.4/registry/base_registry.go:258 +0x9a fp=0xc000228910 sp=0xc0002285e8 pc=0x4436e7a
github.com/apache/dubbo-go/registry.(*BaseRegistry).register(0xc000158140, 0xc0001e4c30, 0x5, 0x4640b86, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc000292630, ...)
	/Users/lizhh/Documents/prj/goexample/pkg/mod/github.com/apache/dubbo-go@v1.5.4/registry/base_registry.go:235 +0xf8 fp=0xc000228a18 sp=0xc000228910 pc=0x4436c78
github.com/apache/dubbo-go/registry.(*BaseRegistry).Register(0xc000158140, 0xc0001e4c30, 0x5, 0x4640b86, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc000292630, ...)
	/Users/lizhh/Documents/prj/goexample/pkg/mod/github.com/apache/dubbo-go@v1.5.4/registry/base_registry.go:150 +0x1d8 fp=0xc000228ca8 sp=0xc000228a18 pc=0x4435a58
github.com/apache/dubbo-go/registry/protocol.(*registryProtocol).Refer(0xc00010ec80, 0xc00029a3a0, 0x8, 0xc0001add40, 0x13, 0xc00029a3ab, 0xe, 0xc00029a3ba, 0x4, 0xc000292690, ...)
	/Users/lizhh/Documents/prj/goexample/pkg/mod/github.com/apache/dubbo-go@v1.5.4/registry/protocol/protocol.go:157 +0x535 fp=0xc000229390 sp=0xc000228ca8 pc=0x44e83f5
github.com/apache/dubbo-go/config.(*ReferenceConfig).Refer(0xc0001da9a0, 0x4591d80, 0xc000124658)
	/Users/lizhh/Documents/prj/goexample/pkg/mod/github.com/apache/dubbo-go@v1.5.4/config/reference_config.go:138 +0xbf5 fp=0xc000229860 sp=0xc000229390 pc=0x44547f5
github.com/apache/dubbo-go/config.loadConsumerConfig()
	/Users/lizhh/Documents/prj/goexample/pkg/mod/github.com/apache/dubbo-go@v1.5.4/config/config_loader.go:138 +0x609 fp=0xc000229a50 sp=0xc000229860 pc=0x444cea9
github.com/apache/dubbo-go/config.Load()
	/Users/lizhh/Documents/prj/goexample/pkg/mod/github.com/apache/dubbo-go@v1.5.4/config/config_loader.go:328 +0x13a fp=0xc000229aa8 sp=0xc000229a50 pc=0x444eefa

**Comment by bonake** [comment]
github.com/apache/dubbo-go@v1.5.4/common/url.go 中的map访问是否可以考虑加锁
// RangeParams will iterate the params
// it's not thread-safe
func (c *URL) RangeParams(f func(key, value string) bool) {
	for k, v := range c.params {
		if !f(k, v[0]) {
			break
		}
	}
}

// GetParam gets value by key
func (c URL) GetParam(s string, d string) string {
	r := c.params.Get(s)
	if len(r) == 0 {
		r = d
	}
	return r
}

**Comment by AlexStocks** [comment]
@bonake pls check pr https://github.com/apache/dubbo-go/pull/876 whether it can fix this bug.
