### ISSUE TITLE
从Apollo加载配置后构造配置对象失败的问题

### ISSUE THREAD

**Issue by xuchenncepu** [apache/dubbo-go#887]
假设Apollo中有一行配置为：dubbo.service.user_provider.protocol=dubbo
而在构造ServiceConfig的过程中，Prefix中获取了InterfaceName，未能与properties的key匹配，导致构造失败
``
// Prefix returns dubbo.service.${interface}.
func (c *ServiceConfig) Prefix() string {
	return constant.ServiceConfigPrefix + c.InterfaceName + "."
}
``
同样的问题也处在构造ReferenceConfig的过程中
``
// nolint
func (c *ReferenceConfig) Prefix() string {
	return constant.ReferenceConfigPrefix + c.InterfaceName + "."
}
``
建议在相应ConfigPrefix之后去掉InterfaceName 后缀。

**Comment by AlexStocks** [comment]
@zouyx pls answer this question.

**Comment by ztelur** [comment]
I will check and fix it

**Comment by AlexStocks** [comment]
> I will check and fix it

thx

**Comment by ztelur** [comment]
@xuchenncepu 你好，根据我的实验、源码阅读以及和其他人讨论，apollo作为配置中心的配置刷新功能没有问题，apollo中有关services的配置可以覆盖更新本地的services中的配置。

可能你的实验场景中，将本地yaml文件中有关services的配置完全删除了，目前版本的配置中心和配置刷新功能并不支持根据远端配置数据新增或删除services，它只能进行对应属性的覆盖更新。

这一取舍具有其合理性：
- services的配置，因为诸如interface，method等属性，和本地代码强关联，只有当本地代码变化时，才需要进行对应的更改，不需要使用配置中心动态修改。诸如 timeout、warmup、loadbalance等才可能需要动态修改。或许只有Java热更新等场景需要这一特性，但是 Go 目前来说我暂时想不到具体场景。
- service的新增或删除需要重新进行Export等一系列复杂操作。

有关配置刷新的实现，具体可以查看base_config.go的fresh方法，特别是setFieldValue函数和其内部的setBaseValue函数。

不过，还是希望你可以提供更多信息，我们再进一步讨论。
