### ISSUE TITLE
升级nacos-sdk-go，解决配置中心配置不存在时，dubbo-go与nacos的连接反复断开和连接问题

### ISSUE THREAD

**Issue by whitekeyboard** [apache/dubbo-go#895]
问题：dubbo-go对接nacos配置中心时，当nacos配置中心没有新增配置，dubbo-go默认会获取和订阅全局和应用配置，
nacos-sdk-go会反复获取配置，nacos服务器经过一定次数的报错请求后，就会断开连接，此处dubbo-go会重新连接。由此
导致dubbo-go和nacos之间反复连接和断开。
dubbo-go版本：dubbo-go-v1.5.4 依赖github.com/nacos-group/nacos-sdk-go v1.0.0
example: https://github.com/apache/dubbo-go-samples/tree/master/configcenter/nacos/dubbo/go-server

解决方法：
本人升级github.com/nacos-group/nacos-sdk-go v1.0.1，验证此版本已经修复此问题，请升级nacos-sdk-go版本。
修复的pr为：
https://github.com/nacos-group/nacos-sdk-go/pull/115
Listening for non-existent configuration files invalidates long polling goroutine. #115

**Comment by AlexStocks** [comment]
U can submit ur pr to fix this problem.

**Comment by AlexStocks** [comment]
dubbogo has updated its nacos sdk version now.
