### ISSUE TITLE
org.apache.dubbo 升级2.7.7 不兼容dubbo-go 参数反序列化问题

### ISSUE THREAD

**Issue by kzhan** [apache/dubbo-go#900]
**场景角色**:
 consumer - dubb-go
 provider - Java( org.apache.Dubbo v2.7.7)

consumer 调用 provider情况下, 请求参数类型未设置，导致provider 反序列化找不到方法调用失败(参数类型为struct有问题，string、int正常)
![image](https://user-images.githubusercontent.com/9359993/100715210-ce86ae80-33f1-11eb-9327-60a955a2a133.png)

org.apache.Dubbo v2.7.7 增强代码部分
org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java
附链接：
https://github.com/apache/dubbo/pull/5733/files/effd4a25d8dadcd08a30589109c97d86cbd607d2#diff-a32630b1035c586f6eae2d778e19fc172e986bb0be1d4bc642f8ee79df48ade0

**Comment by cityiron** [comment]
WIP
