### ISSUE TITLE
URLEqual 未比较IP Address

### ISSUE THREAD

**Issue by JiaLiangoooo** [apache/dubbo-go#905]
**What happened**: 
注册中心：consul
环境：k8s
因为consul的上下线，是全量推的，目前代码逻辑中存在，如果有服务上线或者下线都会往Listener发送Event.
目前存在一种场景，如果先上线的，会同时出现2个provider，因为对比逻辑存在问题，导致上下线Event发送不出去. Invoker更新不了，服务不可用

**What you expected to happen**:  修改URLEqual，新增一个比较IP的操作

**How to reproduce it (as minimally and precisely as possible)**:  平凡上下线会导致这个问题.

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/10085817/100982562-256fbd80-3583-11eb-8723-b1cc34b07673.png)

**Comment by JiaLiangoooo** [comment]
![image](https://user-images.githubusercontent.com/10085817/101111098-6b756180-3615-11eb-8662-4139d23b2b97.png)
1. 我能否删除上面的IP与Port的赋值？
2. Copy这份代码，在registry consul listener.go里面增加这个判断？

**Comment by georgehao** [comment]
`common.IsEquals`应该能满足你的需求.

**Comment by JiaLiangoooo** [comment]
@georgehao 😆 这个方法在后续版本中有，当前版本中没有，如果在将比较换成 `common.IsEquals`, 确实能解决这个问题.

**Comment by gaoxinge** [comment]
@JiaLiangoooo @georgehao 

- 提交了一个pr https://github.com/apache/dubbo-go/pull/911 ，有空看看有没有问题。
- 其他的注册中心也检查了一下，他们的比较都是基于url的全量比较（使用`url.String()`, `reflect.DeepEqual()`比较，或者注册中心返回的消息带有删除或更新），所以应该不会有类似consul的问题。

**Comment by JiaLiangoooo** [comment]
@gaoxinge  应该没问题了.

**Comment by gaoxinge** [comment]
修改已经合并到develop分支了。
