### ISSUE TITLE
使用etcd注册服务，运行一会手动结束几乎百分百会报错

### ISSUE THREAD

**Issue by Owen-Zhang** [apache/dubbo-go#951]
错误信息如下:

panic: sync: negative WaitGroup counter

goroutine 181 [running]:
sync.(*WaitGroup).Add(0xc000074030, 0xffffffffffffffff)
        c:/go/src/sync/waitgroup.go:74 +0x140
sync.(*WaitGroup).Done(...)
        c:/go/src/sync/waitgroup.go:99
github.com/apache/dubbo-go/registry/etcdv3.(*configurationListener).Close(0xc00048a020)
        D:/Code/golang/src/dubbo-go-read/registry/etcdv3/listener.go:123 +0x44
github.com/apache/dubbo-go/registry.(*BaseRegistry).Subscribe(0xc000074000, 0xc0002ac300, 0xf70740, 0xc00053e390, 0x0, 0x0)
        D:/Code/golang/src/dubbo-go-read/registry/base_registry.go:413 +0x36a
created by github.com/apache/dubbo-go/registry/protocol.(*registryProtocol).Export
        D:/Code/golang/src/dubbo-go-read/registry/protocol/protocol.go:215 +0x728
exit status 2

**Comment by Owen-Zhang** [comment]
dubbo-go-read 是我本地clone下来的代码文件目录

**Comment by Owen-Zhang** [comment]
而且出现异常后，注册中心的节点没有删除，只有等其自动过期

**Comment by watermelo** [comment]
@Owen-Zhang 是否有调用的例子，以及用的那个dubbo-go版本

**Comment by JiaLiangoooo** [comment]
version：v1.5.5-rc1

![image](https://user-images.githubusercontent.com/10085817/103170039-175c4680-487c-11eb-9210-f82161b60033.png)
![image](https://user-images.githubusercontent.com/10085817/103170043-2e029d80-487c-11eb-807a-b009427d50bb.png)
![image](https://user-images.githubusercontent.com/10085817/103170067-57232e00-487c-11eb-9d62-008fb1a25554.png)
![image](https://user-images.githubusercontent.com/10085817/103170113-be40e280-487c-11eb-9a50-70a447c7660a.png)


最终程序跑完后，sync.waitGroup 是负数.

**Comment by watermelo** [comment]
@Owen-Zhang @JiaLiangoooo 已修复
