### ISSUE TITLE
consumer端zk断开重连后调不通provider服务

### ISSUE THREAD

**Issue by jack15083** [apache/dubbo-go#956]
**What happened**:
开发环境zk不太稳定，经连接经常断开发现一断开重连所有的consumer references 就调不能通了，必须重启才能调通，重启consumer端或重启服务端都可以

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
调试发现invokers服务被清空
![image](https://user-images.githubusercontent.com/2142066/102964900-a806ef80-4527-11eb-9b8c-1956682b88eb.png)

**Comment by jack15083** [comment]
zk 监听逻辑这里  zk连接丢失不应该close，这样会导致整个zk监听 goroutine exit掉，服务就会一直调不通了，这里应该改成重连比较好 

![image](https://user-images.githubusercontent.com/2142066/103164459-6091a380-4846-11eb-99a4-6fac1dbd88c6.png)

**Comment by Patrick0308** [comment]
@jack15083 we handle zookeeper reconnect in `HandleClientRestart` function in remoting/zookeeper/facade.go:44. Please supply a simple demo to reproduce this issue.

**Comment by jack15083** [comment]
> @jack15083 we handle zookeeper reconnect in `HandleClientRestart` function in remoting/zookeeper/facade.go:44. Please supply a simple demo to reproduce this issue.
只要报zk connect is nil 这个问题必现

![Uploading image.png…]()

**Comment by jack15083** [comment]
> @jack15083 we handle zookeeper reconnect in `HandleClientRestart` function in remoting/zookeeper/facade.go:44. Please supply a simple demo to reproduce this issue.

你可以强制将服务端的zk连接断掉，然后重连，消费端这个报错会必现

**Comment by jack15083** [comment]
fix https://github.com/apache/dubbo-go/pull/940
