### ISSUE TITLE
sentinel-golang 版本兼容性问题

### ISSUE THREAD

**Issue by kzhan** [apache/dubbo-go#957]
**What would you like to be added**:
sentinel-golang 版本兼容性问题

**Why is this needed**:
在目前项目开发中引入了sentinel-golang 版本为v1.0.1，目前最新稳定版本，但发现dubbo-go v1.5.4 所集成采用的 sentinel-golang 版本较老 v0.6.2，通过版本记录发现 sentinel-golang 0.x 到 1.x 之间存在较大的差异，故导致目前在使用高版本 dubbo-go中无法正常使用现有项目新版本 sentinel-golang

就目前遇到问题截图
![image](https://user-images.githubusercontent.com/9359993/103069099-9db52600-45f9-11eb-922f-beffb0ed8185.png)

高版本无法兼容 dubbo-go中   filter/filter_impl/sentinel_filter.go 文件  init() 下 logging.ResetGlobalLogger(DubboLoggerWrapper{Logger: logger.GetLogger()}) 的使用异常问题

本想自己处理，但考虑到修改文件覆盖率无法评估，还望社区专员帮忙看看

**Comment by louyuting** [comment]
I will upgrade sentinel golang to v1.0.1
Thanks

**Comment by AlexStocks** [comment]
@kzhan pls checkout this pr https://github.com/apache/dubbo-go/pull/961/files code and check it runnable or not.
