### ISSUE TITLE
The consumer Config retry is not right

### ISSUE THREAD

**Issue by georgehao** [apache/dubbo-go#982]
**What happened**:
The retry of consumer is 3, but invoke the failoverCluster the real retry is 1

![image](https://user-images.githubusercontent.com/6947653/103476017-29defe80-4ded-11eb-9361-270e287ad346.png)

![image](https://user-images.githubusercontent.com/6947653/103476018-2cd9ef00-4ded-11eb-9c30-589331061bbc.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by cityiron** [comment]
getRetries:
```go	
        if retries > len(invokers) {
		retries = len(invokers)
	}
```

pls check your invokers count.
