### ISSUE TITLE
关于启动初始化Filter获取filter name一点优化建议

### ISSUE THREAD

**Issue by kzhan** [apache/dubbo-go#991]
**What would you like to be added**:
这里是关于一点dubbo-go启动初始化过程中获取 filter配置的建议
场景:
这是我的filter配置，多个filter配置，注意我带了个小空格
![image](https://user-images.githubusercontent.com/9359993/104158577-9929a380-5428-11eb-92b9-10d64361cf53.png)

加载过程中没有任何问题，获取 filter name 时候也有一个小空格
![image](https://user-images.githubusercontent.com/9359993/104158694-d8f08b00-5428-11eb-9748-ac59c138e5cc.png)

但是我在定一个 filter name ，进行extension.SetFilter 配置是不可能加空格的
![image](https://user-images.githubusercontent.com/9359993/104158800-1228fb00-5429-11eb-844f-f96be4cd7853.png)

结果可想而知，panic了

**Why is this needed**:
配置上的美观差异，建议 trim 下，小建议，希望能在帮助dubbo-go完善的道路上精益求精

**Comment by cityiron** [comment]
Thank you for your suggestion, you can submit the PR or our community will have someone to improve.

**Comment by fangyincheng** [comment]
pr#1003
