### ISSUE TITLE
Get weird error message: `pkg.Unmarshal(len(@data):0) = error:get wrong attachments: <nil>` in the server

### ISSUE THREAD

**Issue by spacewander** [apache/dubbo-go#993]
**What happened**:
Get weird error message: `pkg.Unmarshal(len(@data):0) = error:get wrong attachments: <nil>` in the server code.

**What you expected to happen**:
Server works as expected.

**How to reproduce it (as minimally and precisely as possible)**:
1. use tengine as http2dubbo proxy, with configuration in the example: https://github.com/alibaba/tengine/tree/master/modules/mod_dubbo
2. write a dubbo server with dubbo-go
3. request with `curl http://127.0.0.1:8080/dubbo -i`

**Anything else we need to know?**:
The same thing doesn't happen with the tengine's Java example. It works as the document states.

**Comment by AlexStocks** [comment]
sorry, we have not tested our dubbogo with tengine. maybe u can try to fix this problem and submit a pr. thx.

**Comment by spacewander** [comment]
Hi, @AlexStocks, any updates?

**Comment by rockXiaofeng** [comment]
@spacewander Hi, just now we used dubbo-samples (helloworld/go-server) to debug the program, and obtained the following information in the apisix error_log:
```
2021/03/09 10:36:45 [error] 2080#23919: *527208 dubbo: parse exception failed unsupported type readObjectDefinition
2021/03/09 10:36:45 [warn] 2080#23919: *527208 dubbo: response decode result failed �Ccom.ikurento.user.User�idnameagetime`A001
                                                                                                                               Alex Stocks�Jx�N
2021/03/09 10:36:45 [warn] 2080#23919: *527208 multi: parse get error 00007F9A50025E50
```

**Comment by rockXiaofeng** [comment]
What is the version of apisix dubbo plugin?

**Comment by spacewander** [comment]
Do you mean the dubbo protocol version? It is "2.0.2".

**Comment by rockXiaofeng** [comment]
Yes,  and pls take a look at the above error log.

**Comment by rockXiaofeng** [comment]
Hi @spacewander , as you said, it does not support object,  and just now we changed the provider response from object to string,  called twice with curl, and then we got an error from apisix error_log:
```
2021/03/10 15:10:17 [warn] 2391#27190: *2669171 multi: multi connection detach not empty 00007FB4FAC3F950
2021/03/10 15:10:17 [error] 2391#27190: *2669170 upstream timed out (60: Operation timed out) while connecting to upstream, client: ::1, server: , subrequest: "/app", upstream: "dubbo://127.0.0.1:20000"

2021/03/10 15:10:19 [error] 2391#27190: *2669456 dubbo: parse result map failed �N
2021/03/10 15:10:19 [warn] 2391#27190: *2669456 dubbo: response decode result failed �N
2021/03/10 15:10:19 [warn] 2391#27190: *2669456 multi: parse get error 00007FB4FB060050
```
Can you analyze the reasons for this?

**Comment by spacewander** [comment]
> dubbo: parse result map failed

The response body needs to be a map. Will you give it a try after converting string to map?

BTW, how you get rid of `pkg.Unmarshal(len(@data):0) = error:get wrong attachments: <nil>`?

**Comment by rockXiaofeng** [comment]
> > dubbo: parse result map failed
> 
> The response body needs to be a map. Will you give it a try after converting string to map?

okay, when i changed the response string to map, there are no output logs in the apisix error_log, but i still got the  HTTP/1.1 502 Bad Gateway  in the console:
```
HTTP/1.1 502 Bad Gateway
Date: Wed, 10 Mar 2021 08:29:50 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
demo: test
Server: APISIX/2.3
X-APISIX-Upstream-Status: 502
``` 
and u can see the header 'demo: test' , it is the map value returned by the provider. Why it is in the response header?

**Comment by spacewander** [comment]
My bad! My previous word is confusing.

The response body needs to be a map. This map should contain status and body and other headers. The map should be something like this:
```
status: 200 // map to HTTP status
header1: value
header2: value
body: blahblah // map to HTTP body
```

You can take a look at: https://github.com/api7/mod_dubbo/blob/3f7034ac607d7caf85b8d3b74f2e80842e0ea717/ngx_http_dubbo_module.c#L1371

**Comment by rockXiaofeng** [comment]
> > dubbo: parse result map failed
> BTW, how you get rid of `pkg.Unmarshal(len(@data):0) = error:get wrong attachments: <nil>`?
Through a series of debugging, we found that the provder did not resolve to attchments (the reason should be that the client did not pass the relevant parameters), so i gave an initialized value:
(dubbo-go/protocol/dubbo/impl/hessian.go 
```
attachments, err := decoder.Decode()
...
if attachments == nil {
	attachments = map[interface{}]interface{}{"interface": target}
}
```
ps: the above code is only a preliminary judgment and ultimately needs to be discussed with the developers.

**Comment by rockXiaofeng** [comment]
> My bad! My previous word is confusing.
> 
> The response body needs to be a map. This map should contain status and body and other headers. The map should be something like this:
> 
> ```
> status: 200 // map to HTTP status
> header1: value
> header2: value
> body: blahblah // map to HTTP body
> ```
> 
> You can take a look at: https://github.com/api7/mod_dubbo/blob/3f7034ac607d7caf85b8d3b74f2e80842e0ea717/ngx_http_dubbo_module.c#L1371

I just tried and the response map val is :  rsp:main.User{"body":"OK", "foo":"bar", "status":200}, then called by curl and got error msg from error_log:
```
2021/03/10 16:58:54 [alert] 3221#49005: worker process 4021 exited on signal 11
2021/03/10 16:58:54 [warn] 4038#69795: *232937 [lua] plugin.lua:173: load(): new plugins: {"cors":true,"traffic-split":true,"batch-requests":true,"dubbo-proxy":true,"api-breaker":true,"key-auth":true,"echo":true,"uri-blocker":true,"serverless-post-function":true,"sls-logger":true,"http-logger":true,"prometheus":true,"limit-conn":true,"request-id":true,"proxy-mirror":true,"authz-keycloak":true,"wolf-rbac":true,"consumer-restriction":true,"ip-restriction":true,"request-validation":true,"proxy-rewrite":true,"limit-count":true,"grpc-transcode":true,"zipkin":true,"jwt-auth":true,"limit-req":true,"basic-auth":true,"serverless-pre-function":true,"server-info":true,"udp-logger":true,"tcp-logger":true,"syslog":true,"response-rewrite":true,"openid-connect":true,"hmac-auth":true,"kafka-logger":true,"fault-injection":true,"referer-restriction":true,"proxy-cache":true,"redirect":true}, context: init_worker_by_lua*
2021/03/10 16:58:54 [warn] 4038#69795: *232937 [lua] plugin.lua:221: load_stream(): new plugins: {"mqtt-proxy":true}, context: init_worker_by_lua*
2021/03/10 16:58:54 [warn] 4038#69795: *232939 [lua] init.lua:290: sync_local_conf_to_etcd(): sync local conf to etcd, context: ngx.timer

console:
curl: (52) Empty reply from server
```

**Comment by rockXiaofeng** [comment]
It is not clear why the following information is often obtained from the apisix error log:
```
2021/03/10 17:06:17 [warn] 4038#69795: *289190 multi: multi connection detach not empty 00007F8676C00E10
2021/03/10 17:06:17 [error] 4038#69795: *289189 upstream timed out (60: Operation timed out) while connecting to upstream, client: ::1, server: , subrequest: "/app", upstream: "dubbo://127.0.0.1:20000"
```
just called five times, four of them.

**Comment by spacewander** [comment]
@rockXiaofeng 
Would you package everything as docker-compose or docker so that I can analyze it closer? Thanks!

**Comment by rockXiaofeng** [comment]
> @rockXiaofeng
> Would you package everything as docker-compose or docker so that I can analyze it closer? Thanks!

Okay, try my best.

**Comment by rockXiaofeng** [comment]
Hi @spacewander , just made a docker image for provider-sample: 
```
docker pull 10520/dubbo-go-provider-app
```

docker-compose file like this:
```
version: "3"

services:
  provider:
    image: 10520/dubbo-go-provider-app
    restart: always
    volumes:
      - /${SERVER_CONF_PATH}/server.yml:/app/test/server.yml
    environment:
      CONF_PROVIDER_FILE_PATH: "/app/test/server.yml"
    ports:
      - "20000:20000/tcp"
    network_mode: host
```

You can try this and look forward to your reply~

**Comment by spacewander** [comment]
Can you make a container with APISIX too? I don't know your configuration yet. And how you access the route (HTTP method, request URI, request body, etc.)?

**Comment by spacewander** [comment]
You can package the configuration as YAML with the standalone mode: https://github.com/apache/apisix/blob/master/docs/en/latest/stand-alone.md

**Comment by rockXiaofeng** [comment]
For all configuration and version information, see:
#https://github.com/apache/apisix/issues/3725

```
curl http://127.0.0.1:9080/apisix/admin/upstreams/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "nodes": {
        "127.0.0.1:20000": 1
    },
    "type": "roundrobin"
}'

curl http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uris": [
        "/app"
    ],
    "plugins": {
        "dubbo-proxy": {
            "service_name": "com.ikurento.users.UsersProvider",
            "service_version": "1.0.0",
            "method": "GetUser"
        }
    },
    "upstream_id": 1
}'
```

Request with command:
```
curl localhost:9080/app -i
```

**Comment by spacewander** [comment]
Try to use string "200" instead of 200 for the status?

**Comment by rockXiaofeng** [comment]
> Try to use string "200" instead of 200 for the status?

 It was indeed successful after the change!

**Comment by spacewander** [comment]
I can't reproduce the timeout at my side. Is it because both services are running on my machine?

**Comment by rockXiaofeng** [comment]
> I can't reproduce the timeout at my side. Is it because both services are running on my machine?

 Both services are running on my machine too...

**Comment by rockXiaofeng** [comment]
Let's summarize, now there are two questions?
1) dubbo-go parsing attchments error.
2) For the dubbo plugin of apisix, the returned structure format specification problem. (like: map["status":"200", "body":"...")

**Comment by rockXiaofeng** [comment]
Hi @spacewander ,  Ask a question about the document: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/dubbo-proxy.md#runtime-attributes

What does `service_name` mean?   Is it equivalent to `interface` in the file(https://github.com/dubbogo/dubbo-samples/blob/master/golang/helloworld/dubbo/go-server/profiles/test/server.yml) ?

**Comment by spacewander** [comment]
> 
> 
> Hi @spacewander , Ask a question about the document: [https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/dubbo-proxy.md#runtime-attributes](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/dubbo-proxy.md?rgh-link-date=2021-03-15T09%3A41%3A39Z#runtime-attributes)
> 
> What does `service_name` mean? Is it equivalent to `interface` in the file([https://github.com/dubbogo/dubbo-samples/blob/master/golang/helloworld/dubbo/go-server/profiles/test/server.yml](https://github.com/dubbogo/dubbo-samples/blob/master/golang/helloworld/dubbo/go-server/profiles/test/server.yml?rgh-link-date=2021-03-15T09%3A41%3A39Z)) ?

Yes

**Comment by rockXiaofeng** [comment]
Ok, This Pull request has been submitted to the community just now

> > Hi @spacewander , Ask a question about the document: [https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/dubbo-proxy.md#runtime-attributes](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/dubbo-proxy.md?rgh-link-date=2021-03-15T09%3A41%3A39Z#runtime-attributes)
> > What does `service_name` mean? Is it equivalent to `interface` in the file([https://github.com/dubbogo/dubbo-samples/blob/master/golang/helloworld/dubbo/go-server/profiles/test/server.yml](https://github.com/dubbogo/dubbo-samples/blob/master/golang/helloworld/dubbo/go-server/profiles/test/server.yml?rgh-link-date=2021-03-15T09%3A41%3A39Z)) ?
> 
> Yes

This Pull request has been submitted to the community just now.

**Comment by spacewander** [comment]
I update the documentation of the dubbo-proxy plugin: https://github.com/apache/apisix/pull/3829
